// 中学3年 全問題データ
// （中1・中2と同様のデータ形式）
export const QUESTIONS_J3 = {
  j3_1: [
    {id:'j3_1_1', explanation:'be動詞「am」は主語Iに合わせる。from＋場所で出身地を表す。', japanese:'私は日本から来ました。', answer:['I','am','from','Japan','.']},
    {id:'j3_1_2', explanation:'「Ken and I」は複数主語なのでbe動詞はare。形容詞goodは名詞の前に置く。', japanese:'ケンと私はよい友達です。', answer:['Ken','and','I','are','good','friends','.']},
    {id:'j3_1_3', explanation:'過去の文なのでbe動詞はwere。「２日前」はtwo days ago。', japanese:'私のイヌたちは２日前に病気でした。', answer:['My','dogs','were','sick','two','days','ago','.']},
    {id:'j3_1_4', explanation:'過去の否定文はwas/were not。「先週」はlast week。', japanese:'ケンは先週大阪にいませんでした。', answer:['Ken','was','not','in','Osaka','last','week','.']},
    {id:'j3_1_5', explanation:'be動詞の過去疑問文はWas/Wereを主語の前に出す。', japanese:'彼女はきのう忙しかったですか。', answer:['Was','she','busy','yesterday','?']},
    {id:'j3_1_6', explanation:'When is your birthday?でWhenで時を尋ねる。', japanese:'私は神戸に住んでいます。', answer:['I','live','in','Kobe','.']},
    {id:'j3_1_7', explanation:'一般動詞liveは主語Iのとき原形のまま。場所はin＋地名。', japanese:'彼は英語をじょうずに話します。', answer:['He','speaks','English','well','.']},
    {id:'j3_1_8', explanation:'主語がHeなのでspeaks。副詞wellは動詞の後ろに置く。', japanese:'私の母は２台の車を持っています。', answer:['My','mother','has','two','cars','.']},
    {id:'j3_1_9', explanation:'主語が3人称単数なのでhaveはhasになる。数字＋複数名詞の語順。', japanese:'私たちは先週、京都を訪れました。', answer:['We','visited','Kyoto','last','week','.']},
    {id:'j3_1_10', explanation:'visit→visitedと規則動詞の過去形。last weekで「先週」。', japanese:'私の弟はピアノを弾けません。', answer:['My','brother','cannot','play','the','piano','.']},
    {id:'j3_1_11', explanation:'cannotは1語。play the pianoでtheをつける。', japanese:'彼らはきのう、数学を勉強しませんでした。', answer:['They','did','not','study','math','yesterday','.']},
    {id:'j3_1_12', explanation:'did not studyで過去の否定文。yesterdayで「きのう」。', japanese:'あなたは妹の宿題を手伝いましたか。', answer:['Did','you','help','your','sister','with','homework','?']},
    {id:'j3_1_13', explanation:'Did you help～?で過去の疑問文。help＋人＋with～で「人の～を手伝う」。', japanese:'お父さんは今、コンピュータを使っています。', answer:['My','father','is','using','a','computer','.']},
    {id:'j3_1_14', explanation:'is＋動詞ing形で現在進行形（今まさに～している）。', japanese:'テーブルの下に２ひきのネコがいます。', answer:['There','are','two','cats','under','the','table','.']},
    {id:'j3_1_15', explanation:'There are＋複数名詞で「～がいる・ある」。under the tableで「テーブルの下に」。', japanese:'あなたの町には図書館がありますか。', answer:['Are','there','any','libraries','in','your','town','?']},
    {id:'j3_1_16', explanation:'Are there any libraries～?でanyを使う疑問文。', japanese:'バスの中には何人の女の子がいますか。', answer:['How','many','girls','are','there','in','the','bus','?']},
    {id:'j3_1_17', explanation:'How many girls are there～?でHow many＋複数名詞で数を尋ねる。', japanese:'私たちは今とても忙しいです。', answer:['We','are','very','busy','now','.']},
    {id:'j3_1_18', explanation:'was in New York～でwasは過去のbe動詞。last Sundayで「先週の日曜日」。', japanese:'きのうは雨でした。', answer:['It','was','rainy','yesterday','.']},
    {id:'j3_1_19', explanation:'We are very busy.でbe動詞areを使う。veryで程度を強調。', japanese:'私は昨夜英語を勉強しました。', answer:['I','studied','English','last','night','.']},
    {id:'j3_1_20', explanation:'Tom and I wereで複数主語→were。two hours agoで「２時間前」。', japanese:'私たちは先週の土曜日にパーティーを開きました。', answer:['We','had','a','party','last','Saturday','.']},
    {id:'j3_1_21', explanation:'I am a studentでbe動詞am。Ken is a student, too.でtooは「も」。', japanese:'おじが２年前にこの自転車をくれました。', answer:['My','uncle','gave','me','this','bike','two','years','ago','.']},
    {id:'j3_1_22', explanation:'was tired last night.でbe動詞の過去形was。', japanese:'私はきのう友人に手紙を書きました。', answer:['I','wrote','a','letter','to','my','friend','yesterday','.']},
    {id:'j3_1_23', explanation:'It was rainy.でItを主語にして天気を表す。', japanese:'彼らはお昼ご飯を作って食べました。', answer:['They','made','lunch','and','ate','it','.']},
    {id:'j3_1_24', explanation:'When they see her.でwhenは接続詞「～のとき」。', japanese:'私の兄は土曜日はたいてい家にいます。', answer:['My','brother','usually','stays','at','home','on','Saturdays','.']},
    {id:'j3_1_25', explanation:'fifteen years oldで「15歳」。andで２つの文をつなぐ。', japanese:'その動物園にはトラが何頭いますか。', answer:['How','many','tigers','are','there','in','the','zoo','?']},
    {id:'j3_1_26', explanation:'argued that～で「～と主張した」。that節の中は過去形。', japanese:'ヨーコは学校へ歩いているとき、イヌを見ました。', answer:['Yoko','saw','a','dog','when','she','was','going','to','school','.']},
    {id:'j3_1_27', explanation:'study→studiedと規則変化の過去形。last nightで「昨夜」。', japanese:'ケンは床につく前に本を読みます。', answer:['Ken','reads','a','book','before','he','goes','to','bed','.']},
    {id:'j3_1_28', explanation:'when she was going to school.でWhen節に過去進行形。', japanese:'ブラウン氏は英語を教えてくれます。', answer:['Mr.','Brown','teaches','us','English','.']},
    {id:'j3_1_29', explanation:'before he goes to bed.でbeforeは接続詞「～の前に」。', japanese:'彼女は通りを歩いているとき、かわいい犬を見ました。', answer:['When','she','was','walking','on','the','street','she','saw','a','pretty','dog','.']},
    {id:'j3_1_30', explanation:'take a walkで「散歩をする」。took＝takeの過去形。', japanese:'私は15歳で、妹は17歳です。', answer:['I','am','fifteen','years','old','and','my','sister','is','seventeen','.']},
    {id:'j3_1_31', explanation:'have a partyで「パーティーを開く」。had＝haveの過去形。', japanese:'ここから駅までバスでどれくらいかかりますか。', answer:['How','long','does','it','take','from','here','to','the','station','by','bus','?']},
    {id:'j3_1_32', explanation:'teaches English to us.でteach＋人＋物（第4文型）。', japanese:'切符が機械から出てきませんでした。', answer:['The','ticket','didn\'t','come','out','of','the','machine','.']},
    {id:'j3_1_33', explanation:'gave me this bike.でgive＋人＋物（第4文型）。two years agoで「２年前」。', japanese:'あなたの誕生日はいつですか。', answer:['When','is','your','birthday','?']},
    {id:'j3_1_34', explanation:'write→wroteと不規則変化。wrote a letter to my friend.の語順。', japanese:'山田先生はその絵を見て立ち止まりました。', answer:['Ms.','Yamada','stopped','and','looked','at','the','picture','.']},
    {id:'j3_1_35', explanation:'get→gotと不規則変化。birthday presentで「誕生日プレゼント」。', japanese:'私たちは今とても忙しいです。', answer:['We','are','very','busy','now','.']},
    {id:'j3_1_36', explanation:'made lunch and ate it.でmake→made、eat→ate（不規則変化）。', japanese:'父のカメラは日本で作られました。', answer:['My','father\'s','camera','was','made','in','Japan','.']},
    {id:'j3_1_37', explanation:'stopped and looked at the picture.でstop→stoppedと規則変化。', japanese:'お父さんは昨夜疲れていました。', answer:['My','father','was','tired','last','night','.']},
    {id:'j3_1_38', explanation:'said goodbye and left the room.でsay→said、leave→left（不規則変化）。', japanese:'トムと私は２時間前に公園にいました。', answer:['Tom','and','I','were','in','the','park','two','hours','ago','.']},
    {id:'j3_1_39', explanation:'副詞usuallyは一般動詞の前に置く。on Saturdayで「土曜日に」。', japanese:'お父さんはきのう散歩をしました。', answer:['My','father','took','a','walk','yesterday','.']},
    {id:'j3_1_40', explanation:'When she was walking～でwhen節に過去進行形。主節は過去形（saw）。', japanese:'彼女はさようならと言って部屋を出ました。', answer:['She','said','goodbye','and','left','the','room','.']},
    {id:'j3_1_41', explanation:'How many tigers are there in the zoo?でHow many＋複数名詞。', japanese:'ユキは先週誕生日プレゼントをもらいました。', answer:['Yuki','got','a','birthday','present','last','week','.']},
    {id:'j3_1_42', explanation:'How long does it take from here to the station by bus?でHow longで時間を尋ねる。', japanese:'私は昨夜英語を勉強しました。', answer:['I','studied','English','last','night','.']},
    {id:'j3_1_43', explanation:'come out of～で「～から出てくる」。didn't＋原形で過去の否定。', japanese:'彼はこれらは正しいと主張しました。', answer:['He','argued','that','these','were','correct','.']},
  ],
  j3_2: [
    {id:'j3_2_1', explanation:'will＋動詞の原形で未来・意志を表す。next weekで「来週」。', japanese:'私は来週サッカーをするつもりです。', answer:['I','will','play','soccer','next','week','.']},
    {id:'j3_2_2', explanation:'willは主語の人称に関係なく同じ形。leaveは「～を出発する」。', japanese:'スミスさんはあした日本を出発するでしょう。', answer:['Mr.','Smith','will','leave','Japan','tomorrow','.']},
    {id:'j3_2_3', explanation:'will be free～でbe動詞の原形beをwillの後に使う。', japanese:'健は今度の日曜日はひまでしょう。', answer:['Ken','will','be','free','next','Sunday','.']},
    {id:'j3_2_4', explanation:'Will you～?で「～してくれませんか」と依頼。', japanese:'この箱を開けてくれませんか。', answer:['Will','you','open','this','box','?']},
    {id:'j3_2_5', explanation:'will not get up～でwillの否定はwill not（won't）。', japanese:'ユキはあした早起きをしないでしょう。', answer:['Yuki','will','not','get','up','early','tomorrow','.']},
    {id:'j3_2_6', explanation:'Will they visit～?で疑問文はwillを主語の前に出す。', japanese:'彼らは来年ロンドンを訪れるでしょうか。', answer:['Will','they','visit','London','next','year','?']},
    {id:'j3_2_7', explanation:'It will not rain.でItを主語にして天気を表す。', japanese:'あすは雨が降らないでしょう。', answer:['It','will','not','rain','tomorrow','.']},
    {id:'j3_2_8', explanation:'What time will the game start?でWhatのあとにwillを主語の前に出す。', japanese:'試合は何時に始まりますか。', answer:['What','time','will','the','game','start','?']},
    {id:'j3_2_9', explanation:'be going to＋動詞の原形で「～するつもり」。invite himの語順に注意。', japanese:'私たちは彼をパーティーに招くつもりです。', answer:['We','are','going','to','invite','him','to','the','party','.']},
    {id:'j3_2_10', explanation:'He is going to take his dog for a walk.でfor a walkは「散歩に」。', japanese:'私の母はあしたテニスをするつもりです。', answer:['My','mother','is','going','to','play','tennis','tomorrow','.']},
    {id:'j3_2_11', explanation:'主語がMy motherなのでisを使う。be going toの形に注意。', japanese:'私の父は来週、新しい車を買います。', answer:['My','father','will','buy','a','new','car','next','week','.']},
    {id:'j3_2_12', explanation:'I am going to see my uncle.でamを使う。', japanese:'トムはこのコンピュータを使うつもりです。', answer:['Tom','is','going','to','use','this','computer','.']},
    {id:'j3_2_13', explanation:'My father will buy a new car.でwill＋原形。', japanese:'あなたはパーティーで楽しく過ごすでしょう。', answer:['You','will','have','a','good','time','at','the','party','.']},
    {id:'j3_2_14', explanation:'Tom is going to use this computer.でisを使う。', japanese:'あすは東京では雪が降らないでしょう。', answer:['It','will','not','snow','in','Tokyo','tomorrow','.']},
    {id:'j3_2_15', explanation:'We are going to sing English songs.でareを使う。', japanese:'由紀は今夜彼に電話をかけるでしょうか。', answer:['Will','Yuki','call','him','this','evening','?']},
    {id:'j3_2_16', explanation:'The children are going to watch a soccer game on TV.でareを使う。', japanese:'彼女はあした朝食を作るつもりです。', answer:['She','is','going','to','make','breakfast','tomorrow','morning','.']},
    {id:'j3_2_17', explanation:'You will have a good time.でhave a good timeは「楽しく過ごす」。', japanese:'あなたはそこで写真を撮るつもりですか。', answer:['Are','you','going','to','take','pictures','there','?']},
    {id:'j3_2_18', explanation:'Are they going to climb～?でbe going toの疑問文はAreを前に出す。', japanese:'私は今晩、外出するつもりはありません。', answer:['I','am','not','going','to','go','out','this','evening','.']},
    {id:'j3_2_19', explanation:'It will not snow in Tokyo.でwill notで否定。', japanese:'あしたは寒くならないでしょう。', answer:['It','will','not','be','cold','tomorrow','.']},
    {id:'j3_2_20', explanation:'Will Yuki call him～?でwillを主語の前に出す。', japanese:'私はあなたのことばを忘れないでしょう。', answer:['I','will','never','forget','your','words','.']},
    {id:'j3_2_21', explanation:'She is going to make breakfast.でisを使う。', japanese:'健は母親に何を買うつもりですか。', answer:['What','is','Ken','going','to','buy','for','his','mother','?']},
    {id:'j3_2_22', explanation:'Are you going to take pictures?でbe going toの疑問文。', japanese:'あなたはあした何時にトムを訪ねるつもりですか。', answer:['What','time','are','you','going','to','visit','Tom','tomorrow','?']},
    {id:'j3_2_23', explanation:'What time will Ms. Green come to school?の語順。', japanese:'グリーン先生は何時に学校に来ますか。', answer:['What','time','will','Ms.','Green','come','to','school','?']},
    {id:'j3_2_24', explanation:'I am not going to go out.でam not going toで否定。', japanese:'どのくらいしたら出発の準備ができますか。', answer:['How','soon','will','you','be','ready','to','start','?']},
    {id:'j3_2_25', explanation:'It will not be cold.でwill not beでbe動詞の原形。', japanese:'私はあの楽しい日々を決して忘れません。', answer:['I','will','never','forget','those','happy','days','.']},
    {id:'j3_2_26', explanation:'I will never forget～.でneverはwillと原形の間。', japanese:'彼らは今年の夏に山に登るつもりですか。', answer:['Are','they','going','to','climb','the','mountain','this','summer','?']},
    {id:'j3_2_27', explanation:'What is Ken going to buy for his mother?の語順。', japanese:'子どもたちはテレビでサッカーの試合を見るつもりです。', answer:['The','children','are','going','to','watch','soccer','game','on','TV','.']},
    {id:'j3_2_28', explanation:'副詞neverはwillと動詞の原形の間に置く。those＋複数名詞で「あの～」。', japanese:'彼はきょうの午後、犬を散歩に連れて行くつもりです。', answer:['He','is','going','to','take','his','dog','for','a','walk','this','afternoon','.']},
    {id:'j3_2_29', explanation:'What time are you going to visit Tom?の語順。', japanese:'私はあした、おじさんに会うつもりです。', answer:['I','am','going','to','see','my','uncle','tomorrow','.']},
    {id:'j3_2_30', explanation:'take part in～で「～に参加する」。be going toの主語に合わせてisを使う。', japanese:'私たちはそこで英語の歌を歌うつもりです。', answer:['We','are','going','to','sing','English','songs','there','.']},
    {id:'j3_2_31', explanation:'I am going to leave London for Sydney.でfor＋目的地。', japanese:'今晩、ピアノの練習をするつもりはありません。', answer:['I','am','not','going','to','practice','the','piano','this','evening','.']},
    {id:'j3_2_32', explanation:'How soonで「どのくらいしたら」。ready to＋原形で「～する準備ができた」。', japanese:'あなたはこの手紙を彼女に送るつもりですか。', answer:['Are','you','going','to','send','this','letter','to','her','?']},
  ],
  j3_3: [
    {id:'j3_3_1', explanation:'can＋動詞の原形で「～できる」。副詞wellは動詞の後ろ。', japanese:'私は英語をじょうずに話すことができます。', answer:['I','can','speak','English','well','.']},
    {id:'j3_3_2', explanation:'Can Tom swim very fast?でcanを主語の前に出す。', japanese:'トムはとても速く泳ぐことができますか。', answer:['Can','Tom','swim','very','fast','?']},
    {id:'j3_3_3', explanation:'be able to＋動詞の原形で「～できる」（canと同じ意味）。', japanese:'お父さんは車を運転できません。', answer:['My','father','cannot','drive','a','car','.']},
    {id:'j3_3_4', explanation:'cannotは1語。drive a carで「車を運転する」。', japanese:'あなたの辞書を使ってもいいですか。', answer:['May','I','use','your','dictionary','?']},
    {id:'j3_3_5', explanation:'May I～?で「～してもいいですか」と許可を求める丁寧表現。', japanese:'この箱を運んでくれませんか。', answer:['Will','you','carry','this','box','?']},
    {id:'j3_3_6', explanation:'Will you carry this box?で依頼。', japanese:'今、テレビを見てもいいですか。', answer:['May','I','watch','TV','now','?']},
    {id:'j3_3_7', explanation:'May I watch TV now?でMay Iは許可を求める表現。', japanese:'あしたは雨かもしれません。', answer:['It','may','be','rainy','tomorrow','.']},
    {id:'j3_3_8', explanation:'It may be rainy tomorrow.でmayは「～かもしれない」（推量）。', japanese:'このコンピュータを使ってもいいですよ。', answer:['You','can','use','this','computer','.']},
    {id:'j3_3_9', explanation:'You can use this computer.でcanは許可を表す。', japanese:'彼は新入生かもしれません。', answer:['He','may','be','a','new','student','.']},
    {id:'j3_3_10', explanation:'He may be a new student.でmayは推量を表す。', japanese:'あなたは早く寝るべきです。', answer:['You','should','go','to','bed','early','.']},
    {id:'j3_3_11', explanation:'should＋動詞の原形で「～すべきだ」。go to bedで「寝る」。', japanese:'私は沖縄をまた訪れたいものです。', answer:['I','would','like','to','visit','Okinawa','again','.']},
    {id:'j3_3_12', explanation:'would like to＋動詞の原形で「～したい」の丁寧表現。', japanese:'お茶はいかがですか。', answer:['Would','you','like','some','tea','?']},
    {id:'j3_3_13', explanation:'Would you like～?で「～はいかがですか」と丁寧に勧める。', japanese:'私にその辞書を貸していただけませんか。', answer:['Could','you','lend','me','the','dictionary','?']},
    {id:'j3_3_14', explanation:'Could you～?でcanより丁寧な依頼。lend＋人＋物（第4文型）。', japanese:'あなたはうそをついてはいけません。', answer:['You','should','not','tell','a','lie','.']},
    {id:'j3_3_15', explanation:'should not tell a lie.でshould notは「～すべきでない」。', japanese:'私は彼を家に招待したいと思っています。', answer:['I','would','like','to','invite','him','to','my','house','.']},
    {id:'j3_3_16', explanation:'I'd like to invite him to my house.でwould like toは「～したい」（丁寧）。', japanese:'私はいつかあなたの国を訪れてみたいです。', answer:['I','would','like','to','visit','your','country','some','day','.']},
    {id:'j3_3_17', explanation:'would like to visit your country some day.でsome dayは「いつか」。', japanese:'私たちはその子どもたちのために何かするべきです。', answer:['We','should','do','something','for','the','children','.']},
    {id:'j3_3_18', explanation:'should do something for～でshouldの後は動詞の原形。', japanese:'あなたたちはまたそれらの動物を見ることができるでしょう。', answer:['You','will','be','able','to','see','those','animals','again','.']},
    {id:'j3_3_19', explanation:'Does your mother have to get up early～?でhave toの疑問文。', japanese:'何か飲み物はいかがですか。', answer:['Would','you','like','something','to','drink','?']},
    {id:'j3_3_20', explanation:'will be able to see～でwillの後にbe able toを使う。', japanese:'あなたの電話番号を教えてくれませんか。', answer:['Will','you','tell','me','your','phone','number','?']},
    {id:'j3_3_21', explanation:'Would you like something to drink?でsomething to drinkは「何か飲むもの」。', japanese:'私が彼女の子どもを探さなくてはいけないのですか。', answer:['Must','I','look','for','her','child','?']},
    {id:'j3_3_22', explanation:'You don't have to go with us if you don't want to.でdon't have toは「～しなくていい」。', japanese:'あなたのお母さんは毎朝早く起きなければなりませんか。', answer:['Does','your','mother','have','to','get','up','early','every','morning','?']},
    {id:'j3_3_23', explanation:'Will you tell me your phone number?で依頼。tell＋人＋物（第4文型）。', japanese:'行きたくなければ、行かなくてもいいですよ。', answer:['If','you','don\'t','want','to','go','you','don\'t','have','to','go','.']},
    {id:'j3_3_24', explanation:'Must I look for her child?でMustを主語の前に出す疑問文。', japanese:'あなたはお母さんのピアノが弾けますか。', answer:['Is','your','mother','able','to','play','the','piano','?']},
  ],
  j3_4: [
    {id:'j3_4_1', explanation:'get＋形容詞で「～になる」（第2文型）。gotはgetの過去形。', japanese:'父は病気になりました。', answer:['My','father','got','sick','.']},
    {id:'j3_4_2', explanation:'give＋人＋物（第4文型）。someは複数名詞の前で「いくつかの」。', japanese:'娘は私に美しい花をくれました。', answer:['My','daughter','gave','me','some','beautiful','flowers','.']},
    {id:'j3_4_3', explanation:'stay at～で「～に泊まる」。過去形stayedを使う。', japanese:'だれが壁を白く塗りましたか。', answer:['Who','painted','the','wall','white','?']},
    {id:'j3_4_4', explanation:'paint＋目的語＋形容詞で「～を…に塗る」（第5文型）。疑問詞Whoが主語。', japanese:'トムは川でたくさんの魚を捕まえました。', answer:['Tom','caught','a','lot','of','fish','in','the','river','.']},
    {id:'j3_4_5', explanation:'catch a lot of fish.でcatch→caught（不規則変化）。', japanese:'試合に勝ったあと、彼女はとても疲れたように感じました。', answer:['She','felt','very','tired','after','she','won','the','game','.']},
    {id:'j3_4_6', explanation:'feel＋形容詞で「～に感じる」（第2文型）。feltはfeelの過去形。', japanese:'そのケーキは食べてみると、とてもおいしかったです。', answer:['I','found','the','cake','delicious','.']},
    {id:'j3_4_7', explanation:'find＋目的語＋形容詞で「～が…だとわかる」（第5文型）。foundはfindの過去形。', japanese:'車は私たちの生活をよくし、楽しいものにします。', answer:['Cars','make','our','lives','good','and','happy','.']},
    {id:'j3_4_8', explanation:'show＋人＋that節で「人に～を示す」（第4文型）。', japanese:'彼女はなんてじょうずにピアノを弾くのでしょう。', answer:['How','well','she','plays','the','piano','!']},
    {id:'j3_4_9', explanation:'make＋目的語＋形容詞で「～を…にする」（第5文型）。', japanese:'あなたがこの学校の生徒であることを示してください。', answer:['Please','show','us','you','are','a','student','in','this','school','.']},
    {id:'j3_4_10', explanation:'look＋形容詞で「～に見える」（第2文型）。like＋名詞で「～のように」。', japanese:'あなたたちはとても幸せに見えますよ。', answer:['You','look','very','happy','.']},
  ],
  j3_5: [
    {id:'j3_5_1', explanation:'受け身はbe動詞＋過去分詞。by～で「～によって」。', japanese:'このペンはトムによって使われています。', answer:['This','pen','is','used','by','Tom','.']},
    {id:'j3_5_2', explanation:'see→seenと不規則変化。主語が複数なのでare。', japanese:'この公園ではたくさんの鳥が見られます。', answer:['Many','birds','are','seen','in','this','park','.']},
    {id:'j3_5_3', explanation:'過去の受け身はwas/were＋過去分詞。場所はin＋地名。', japanese:'父のカメラは日本で作られました。', answer:['My','father\'s','camera','was','made','in','Japan','.']},
    {id:'j3_5_4', explanation:'助動詞の受け身はmust be＋過去分詞。do→doneと不規則変化。', japanese:'その仕事は健によってなされなければなりません。', answer:['The','job','must','be','done','by','Ken','.']},
    {id:'j3_5_5', explanation:'sell→soldと不規則変化。at the shopで「その店で」。', japanese:'このお人形はその店で売られています。', answer:['This','doll','is','sold','at','the','shop','.']},
    {id:'j3_5_6', explanation:'find→foundと不規則変化。過去の受け身はwas。', japanese:'彼のかばんは部屋の中で見つかりました。', answer:['His','bag','was','found','in','the','room','.']},
    {id:'j3_5_7', explanation:'受け身の疑問文はWas/Were＋主語＋過去分詞～?', japanese:'この部屋はジェーンによって掃除されましたか。', answer:['Was','this','room','cleaned','by','Jane','?']},
    {id:'j3_5_8', explanation:'be made from～で原料から作られる場合（変化が起きるとき）。', japanese:'チーズは牛乳から作られます。', answer:['Cheese','is','made','from','milk','.']},
    {id:'j3_5_9', explanation:'be interested in～で「～に興味がある」。受け身の慣用表現。', japanese:'ジムは日本の歴史に興味があります。', answer:['Jim','is','interested','in','Japanese','history','.']},
    {id:'j3_5_10', explanation:'be covered with～で「～でおおわれている」。受け身の慣用表現。', japanese:'その山は雪でおおわれています。', answer:['The','mountain','is','covered','with','snow','.']},
    {id:'j3_5_11', explanation:'be filled with～で「～でいっぱいだ」。受け身の慣用表現。', japanese:'コップは水でいっぱいです。', answer:['The','glass','is','filled','with','water','.']},
    {id:'j3_5_12', explanation:'be surprised at～で「～に驚く」。受け身の慣用表現。', japanese:'その知らせにだれもが驚きました。', answer:['Everyone','was','surprised','at','the','news','.']},
    {id:'j3_5_13', explanation:'How many＋複数名詞で数を尋ねる。過去の受け身はwere＋過去分詞。', japanese:'昨年は何台の車が売れましたか。', answer:['How','many','cars','were','sold','last','year','?']},
    {id:'j3_5_14', explanation:'受け身の否定はwas/were not＋過去分詞。invent→inventedと規則変化。', japanese:'これらの機械は彼が発明したものではありません。', answer:['These','machines','were','not','invented','by','him','.']},
    {id:'j3_5_15', explanation:'No good books were found～でNoは「1つも～ない」。', japanese:'彼の本は世界の多くの人に読まれています。', answer:['His','books','are','read','by','many','people','in','the','world','.']},
    {id:'j3_5_16', explanation:'主語が複数なのでare＋過去分詞。by＋人で「～によって」。', japanese:'新しい本屋にはよい本がありませんでした。', answer:['No','good','books','were','found','at','the','new','bookstore','.']},
  ],
  j3_6: [
    {id:'j3_6_1', explanation:'経験を表す現在完了はhave/has＋過去分詞。several timesで「数回」。', japanese:'私たちは数回その都市を訪れたことがあります。', answer:['We','have','visited','the','city','several','times','.']},
    {id:'j3_6_2', explanation:'主語がKenなのでhas。once（一度）はhas＋過去分詞の後ろ。', japanese:'健はその本を一度読んだことがあります。', answer:['Ken','has','read','the','book','once','.']},
    {id:'j3_6_3', explanation:'see→seen（不規則変化）。beforeは「以前に」を表し文末に置く。', japanese:'私は以前その少女に会ったことがあります。', answer:['I','have','met','the','girl','before','.']},
    {id:'j3_6_4', explanation:'主語がHeなのでhas＋過去分詞。play→playedと規則変化。', japanese:'彼は以前ここでテニスをしたことがあります。', answer:['He','has','played','tennis','here','before','.']},
    {id:'j3_6_5', explanation:'主語がIなのでhave。many timesで「何度も」。', japanese:'私はこのコンピュータを何度も使ったことがあります。', answer:['I','have','used','this','computer','many','times','.']},
    {id:'j3_6_6', explanation:'主語がJaneなのでhas。twiceは「2度」で文末に置く。', japanese:'私たちは以前広島を訪れたことがあります。', answer:['We','have','visited','Hiroshima','before','.']},
    {id:'j3_6_7', explanation:'have visited Hiroshima beforeで「以前広島を訪れたことがある」。', japanese:'私はこの本を一度も読んだことがありません。', answer:['I','have','never','read','this','book','.']},
    {id:'j3_6_8', explanation:'neverは「一度も～ない」でhave/hasと過去分詞の間に置く。read→read（同形）。', japanese:'あなたは今までにエミに会ったことがありますか。', answer:['Have','you','ever','met','Emi','?']},
    {id:'j3_6_9', explanation:'have taken a picture of Mt. Fuji.でtake→takenと不規則変化。', japanese:'私は一度も富士山に登ったことがありません。', answer:['I','have','never','climbed','Mt.','Fuji','.']},
    {id:'j3_6_10', explanation:'経験の疑問文はHave/Has＋主語＋ever＋過去分詞～?。everは「今までに」。', japanese:'あなたは韓国の歴史についての本を読んだことがありますか。', answer:['Have','you','ever','read','a','book','about','Korean','history','?']},
    {id:'j3_6_11', explanation:'never climbedで「一度も登ったことがない」。climb→climbed規則変化。', japanese:'このような暑い夏は私には初めてです。', answer:['I','have','never','had','such','a','hot','summer','.']},
    {id:'j3_6_12', explanation:'Have you ever read～?で経験を尋ねる。aboutは「～について」。', japanese:'これまでにその川の写真を撮ったことがありますか。', answer:['Have','you','ever','taken','a','picture','of','the','river','?']},
    {id:'j3_6_13', explanation:'have been to～で「～に行ったことがある」（経験）。to不定詞で目的を表す。', japanese:'私はおじに会うためにロンドンに行ったことがあります。', answer:['I','have','been','to','London','to','see','my','uncle','.']},
    {id:'j3_6_14', explanation:'How oftenで「何回」と回数を尋ねる。主語がyour brotherなのでhas。', japanese:'私は以前富士山の写真を撮ったことがあります。', answer:['I','have','taken','a','picture','of','Mt.','Fuji','before','.']},
    {id:'j3_6_15', explanation:'such a hot summer.でsuch a＋形容詞＋名詞。neverで経験がないことを表す。', japanese:'ジェーンはその店で２度本を買ったことがあります。', answer:['Jane','has','bought','books','at','the','shop','twice','.']},
    {id:'j3_6_16', explanation:'take→takenと不規則変化。take a picture of～で「～の写真を撮る」。', japanese:'あなたは今年になってその都市を何度訪ねましたか。', answer:['How','often','have','you','visited','the','city','this','year','?']},
  ],
  j3_7: [
    {id:'j3_7_1', explanation:'完了を表す現在完了。justはhave/hasと過去分詞の間。eat→eaten。', japanese:'私はちょうど昼食を食べ終えたところです。', answer:['I','have','just','eaten','lunch','.']},
    {id:'j3_7_2', explanation:'We have just finished our homework.でjustは「ちょうど」。', japanese:'私たちはちょうど宿題を終えたところです。', answer:['We','have','just','finished','our','homework','.']},
    {id:'j3_7_3', explanation:'疑問文はHas＋主語＋過去分詞～?。read→read（発音はred）。', japanese:'彼は手紙を読みましたか。', answer:['Has','he','read','the','letter','?']},
    {id:'j3_7_4', explanation:'yet（疑問文で「もう」）は文末に置く。have had breakfastで「食事をした」。', japanese:'あなたはもうご飯を食べましたか。', answer:['Have','you','had','breakfast','yet','?']},
    {id:'j3_7_5', explanation:'have gone to～で「～へ行ってしまった」（結果）。go→gone。', japanese:'ヨーコはフランスへ行ってしまいました。', answer:['Yoko','has','gone','to','France','.']},
    {id:'j3_7_6', explanation:'lose→lostと不規則変化。結果として今も持っていないことを表す。', japanese:'サラはルームキーをなくしてしまいました。', answer:['Sarah','has','lost','her','room','key','.']},
    {id:'j3_7_7', explanation:'My father has just returned to the airport.でjustは完了を強調。', japanese:'お父さんはちょうど空港へ戻ってきたところです。', answer:['My','father','has','just','returned','to','the','airport','.']},
    {id:'j3_7_8', explanation:'alreadyは「すでに」でhave/hasと過去分詞の間に置く。hear→heard。', japanese:'私たちの子どもは、もうそのニュースを聞いてしまいました。', answer:['The','children','have','already','heard','the','news','.']},
    {id:'j3_7_9', explanation:'yetは疑問文で「もう」、否定文で「まだ」。文末に置く。sell→sold。', japanese:'あなたは、もうその家を売ってしまいましたか。', answer:['Have','you','sold','the','house','yet','?']},
    {id:'j3_7_10', explanation:'主語がHer sisterなのでhas。have gone to～で「～へ行ってしまった」。', japanese:'彼女の妹はロンドンに行ってしまいました。', answer:['Her','sister','has','gone','to','London','.']},
    {id:'j3_7_11', explanation:'finish＋動名詞で「～し終える」。justはhas/haveの直後。', japanese:'父は、ちょうどその絵を描き終えたところです。', answer:['My','father','has','just','finished','painting','the','picture','.']},
  ],
  j3_8: [
    {id:'j3_8_1', explanation:'継続を表す現在完了。forは「～の間（期間）」。', japanese:'私たちはここに３週間滞在しています。', answer:['We','have','been','here','for','three','weeks','.']},
    {id:'j3_8_2', explanation:'sinceは「～から（起点）」。last weekは過去の起点を表す。', japanese:'私の両親は先週からずっと忙しいです。', answer:['My','parents','have','been','busy','since','last','week','.']},
    {id:'j3_8_3', explanation:'主語がHis sisterなのでhas。for＋年数で継続期間を表す。', japanese:'彼のお姉さんは18年間ずっとオーストラリアに住んでいます。', answer:['His','sister','has','been','in','Australia','for','eighteen','years','.']},
    {id:'j3_8_4', explanation:'know→knownと不規則変化。for five yearsで「5年間」。', japanese:'私たちはトムと知り合って5年になります。', answer:['We','have','known','Tom','for','five','years','.']},
    {id:'j3_8_5', explanation:'現在完了進行形（have been＋ing）で動作の継続を表す。for two years。', japanese:'彼女は２年前からずっとテニスを練習しています。', answer:['She','has','been','practicing','tennis','for','two','years','.']},
    {id:'j3_8_6', explanation:'主語がMy fatherなのでhas。be in the hospitalで「入院している」。', japanese:'私の父は去年の夏からずっと入院しています。', answer:['My','father','has','been','in','the','hospital','since','last','summer','.']},
    {id:'j3_8_7', explanation:'know→knownと不規則変化。for four yearsで「4年間」。', japanese:'私は彼女と知り合ってから４年になります。', answer:['I','have','known','her','for','four','years','.']},
    {id:'j3_8_8', explanation:'現在完了進行形（has been talking）で動作の継続を表す。', japanese:'私の妹は30分ずっと電話で話しています。', answer:['My','sister','has','been','talking','on','the','phone','for','thirty','minutes','.']},
    {id:'j3_8_9', explanation:'現在完了進行形の疑問文。sinceの後に過去の時点（last night）。', japanese:'彼は昨夜からずっと眠っているのですか。', answer:['Has','he','been','sleeping','since','last','night','?']},
    {id:'j3_8_10', explanation:'How longで「どのくらいの間」と期間を尋ねる。', japanese:'あなたたちはロンドンに住んでどれくらいになるのですか。', answer:['How','long','have','you','lived','in','London','?']},
  ],
  j3_9: [
    {id:'j3_9_1', explanation:'to不定詞（形容詞的用法）がthingsを修飾。this afternoonは文末。', japanese:'私はきょうの午後、することがたくさんあります。', answer:['I','have','many','things','to','do','this','afternoon','.']},
    {id:'j3_9_2', explanation:'to不定詞の副詞的用法で目的を表す。left＝leaveの過去形。', japanese:'ボブは始発電車に乗るため、家を早く出ました。', answer:['Bob','left','home','early','to','catch','the','first','train','.']},
    {id:'j3_9_3', explanation:'to不定詞（副詞的用法）で感情の原因「～して」を表す。', japanese:'私はそのニュースを聞いて悲しかったです。', answer:['I','was','sad','to','hear','the','news','.']},
    {id:'j3_9_4', explanation:'to不定詞（副詞的用法）で目的「～するために」を表す。', japanese:'私は本を読みに図書館へ行きました。', answer:['I','went','to','the','library','to','read','books','.']},
    {id:'j3_9_5', explanation:'something hot to drink.でhot（形容詞）がsomethingの後ろに来る。', japanese:'彼はおじさんに会うためにニューヨークへ行きました。', answer:['He','went','to','New','York','to','see','his','uncle','.']},
    {id:'j3_9_6', explanation:'to不定詞の副詞的用法。went to＋場所、to see～で目的。', japanese:'私はあなたに言うことがあるのです。', answer:['I','have','something','to','say','to','you','.']},
    {id:'j3_9_7', explanation:'to不定詞（形容詞的用法）がsomethingを修飾。say to～で「～に言う」。', japanese:'彼が、その山を登った最初の日本人でした。', answer:['He','was','the','first','Japanese','to','climb','that','mountain','.']},
    {id:'j3_9_8', explanation:'to不定詞（形容詞的用法）でjobを修飾。take care of～で「～の世話をする」。', japanese:'友だちとおしゃべりしているひまはありませんよ。', answer:['You','have','no','time','to','talk','with','your','friends','.']},
    {id:'j3_9_9', explanation:'to不定詞（形容詞的用法）がdictionaryを修飾。withは「それを使って」の意。', japanese:'何かおもしろい読み物を貸してくれませんか。', answer:['Will','you','lend','me','something','interesting','to','read','?']},
    {id:'j3_9_10', explanation:'the first＋名詞＋to不定詞で「～する最初の人」。', japanese:'何か温かいものを飲みませんか。', answer:['Could','you','give','me','something','hot','to','drink','?']},
    {id:'j3_9_11', explanation:'to不定詞（形容詞的用法）がtimeを修飾。no＋名詞で「～がない」。', japanese:'英語を勉強するのによい辞書を探しています。', answer:['I\'m','looking','for','a','good','dictionary','to','study','English','with','.']},
    {id:'j3_9_12', explanation:'something＋形容詞＋to不定詞の語順。lend＋人＋物（第4文型）。', japanese:'ベビーシッティングは小さな子どもの面倒をみる仕事です。', answer:['Baby-sitting','is','a','job','to','take','care','of','small','children','.']},
  ],
  j3_10: [
    {id:'j3_10_1', explanation:'too＋形容詞＋to不定詞で「～すぎて…できない」。', japanese:'忙しすぎて、お会いできません。', answer:['I','am','too','busy','to','see','you','.']},
    {id:'j3_10_2', explanation:'形容詞＋enough＋to不定詞で「～するほど十分…」。how to＋動詞原形で「～の仕方」。', japanese:'彼は親切に私に踊り方を教えてくれました。', answer:['He','was','kind','enough','to','show','me','how','to','dance','.']},
    {id:'j3_10_3', explanation:'It is～for人＋to不定詞で「人が～するのは…だ」（形式主語構文）。', japanese:'その子どもにとって静かにしているのは困難なことでした。', answer:['It','was','difficult','for','the','child','to','keep','quiet','.']},
    {id:'j3_10_4', explanation:'what＋名詞＋to不定詞で「何の～を…すべきか」（疑問詞＋to不定詞）。', japanese:'彼は彼女に何の花を買えばいいかわかりませんでした。', answer:['He','didn\'t','know','what','flowers','to','buy','for','her','.']},
    {id:'j3_10_5', explanation:'too～for人＋to不定詞で「人には～すぎて…できない」。', japanese:'この質問は難しすぎて私には答えられません。', answer:['This','question','is','too','difficult','for','me','to','answer','.']},
    {id:'j3_10_6', explanation:'when to start making dinner.でwhen to＋原形は「いつ～すべきか」。', japanese:'あなたはいつ夕食を作り始めたらいいか知っていますか。', answer:['Do','you','know','when','to','start','making','dinner','?']},
    {id:'j3_10_7', explanation:'kind enough to help～で「親切にも～してくれる」。help＋人＋with～。', japanese:'健は親切にも私の宿題を手伝ってくれました。', answer:['Ken','was','kind','enough','to','help','me','with','my','homework','.']},
    {id:'j3_10_8', explanation:'It is～for人＋to不定詞の否定形（It wasn't）。', japanese:'どこで手を洗ったらいいか教えていただけませんか。', answer:['Would','you','tell','me','where','to','wash','my','hands','?']},
    {id:'j3_10_9', explanation:'Would you tell me where to wash my hands?でwhere to＋原形。', japanese:'それらの子どもたちにとって海で泳ぐことは難しくありませんでした。', answer:['It','wasn\'t','difficult','for','those','children','to','swim','in','the','sea','.']},
  ],
  j3_11: [
    {id:'j3_11_1', explanation:'want to＋動詞原形で「～したい」。主語がyour brotherなのでDoes。', japanese:'母は私に台所でお皿を洗うように頼みました。', answer:['Mother','asked','me','to','wash','the','dishes','in','the','kitchen','.']},
    {id:'j3_11_2', explanation:'ask＋人＋to不定詞で「人に～するよう頼む」。', japanese:'その歌を聞くといつも私は幸せな気分になります。', answer:['The','song','always','makes','me','feel','happy','.']},
    {id:'j3_11_3', explanation:'make＋人＋動詞原形（原形不定詞）で「人に～させる」（第5文型）。', japanese:'お母さんが帰宅したら、あなたに知らせます。', answer:['When','my','mother','comes','home','I\'ll','let','you','know','.']},
    {id:'j3_11_4', explanation:'let＋人＋動詞原形（原形不定詞）で「人に～させる」。時の副詞節はwill不可。', japanese:'トムに30分待ってもらえますか。', answer:['Will','you','ask','Tom','to','wait','for','thirty','minutes','?']},
    {id:'j3_11_5', explanation:'ask＋人＋to不定詞で「人に～するよう頼む」。', japanese:'子どもたちにこの公園で野球をさせないでください。', answer:['Don\'t','let','your','children','play','baseball','in','this','park','.']},
    {id:'j3_11_6', explanation:'let＋人＋動詞原形（原形不定詞）の否定形。Don't letで「～させないで」。', japanese:'美佳は私たちが教室のそうじをするのを手伝ってくれるでしょう。', answer:['Mika','will','help','us','clean','the','classrooms','.']},
    {id:'j3_11_7', explanation:'have＋人＋動詞原形（使役）で「人に～してもらう」。', japanese:'彼女は自分の宿題を終わらせるのを妹に手伝ってもらいました。', answer:['She','had','her','sister','help','finish','her','homework','.']},
    {id:'j3_11_8', explanation:'help＋人＋動詞原形（原形不定詞）で「人が～するのを手伝う」。', japanese:'きみはお兄さんに、いっしょに大阪に行ってもらいたいですか。', answer:['Does','your','brother','want','to','go','to','Osaka','with','you','?']},
  ],
  j3_12: [
    {id:'j3_12_1', explanation:'stop＋動名詞で「～するのをやめる」。stopの後はto不定詞ではなく動名詞。', japanese:'それは雨が降りやみました。', answer:['It','stopped','raining','.']},
    {id:'j3_12_2', explanation:'enjoy＋動名詞で「～するのを楽しむ」。listen to～で「～を聴く」。', japanese:'母は音楽を聴いて楽しみました。', answer:['My','mother','enjoyed','listening','to','music','.']},
    {id:'j3_12_3', explanation:'Thank you for calling me.でfor＋動名詞「電話してくれて」。', japanese:'先週電話してくれてありがとう。', answer:['Thank','you','for','calling','me','last','week','.']},
    {id:'j3_12_4', explanation:'finish＋動名詞で「～し終える」。Have you finished～?で現在完了の疑問文。', japanese:'あなたはそれを書き終えましたか。', answer:['Have','you','finished','writing','it','?']},
    {id:'j3_12_5', explanation:'be動詞＋動名詞で補語。playingがisの後ろに来る。', japanese:'私の趣味は友達とテニスをすることです。', answer:['My','hobby','is','playing','tennis','with','my','friends','.']},
    {id:'j3_12_6', explanation:'without＋動名詞で「～せずに」。look at～で「～を見る」。', japanese:'彼女は私を見ないで部屋を出て行きました。', answer:['She','left','the','room','without','looking','at','me','.']},
    {id:'j3_12_7', explanation:'be interested in＋動名詞で「～に興味がある」。', japanese:'私は野球を見ることに興味があります。', answer:['I\'m','interested','in','watching','baseball','.']},
    {id:'j3_12_8', explanation:'How about＋動名詞で「～しませんか」と提案。go to the moviesで映画鑑賞。', japanese:'きょう映画を見に行きませんか。', answer:['How','about','going','to','the','movies','today','?']},
    {id:'j3_12_9', explanation:'be afraid of＋動名詞で「～を恐れる」。Don't beで否定命令。', japanese:'英語を話すことを恐がってはいけません。', answer:['Don\'t','be','afraid','of','speaking','English','.']},
    {id:'j3_12_10', explanation:'before finishing your homework.でbefore＋動名詞「～する前に」。', japanese:'宿題を終えずにテレビゲームをしてはいけません。', answer:['You','can\'t','play','the','video','game','before','finishing','your','homework','.']},
    {id:'j3_12_11', explanation:'finish＋動名詞で「～し終える」。justは完了を表す現在完了と一緒に使う。', japanese:'父はちょうどその本を読み終えたところです。', answer:['My','father','has','just','finished','reading','the','book','.']},
    {id:'j3_12_12', explanation:'enjoy＋動名詞で「～するのを楽しむ」。ski→skiing。', japanese:'彼と話すことによって、私は彼を理解することができました。', answer:['By','talking','with','him','I','was','able','to','understand','him','.']},
    {id:'j3_12_13', explanation:'by＋動名詞で「～することによって」。was able toでcanの過去形。', japanese:'トモ子は先週、友人たちとスキーをして楽しみました。', answer:['Tomoko','enjoyed','skiing','with','her','friends','last','week','.']},
    {id:'j3_12_14', explanation:'動名詞が主語（単数扱い）→is。for＋人で「人にとって」。', japanese:'コンピュータゲームをすることは、子どもたちにとって楽しいことです。', answer:['Playing','computer','games','is','fun','for','children','.']},
  ],
  j3_13: [
    {id:'j3_13_1', explanation:'過去分詞の後置修飾。written by Susanがletterを修飾。', japanese:'これはスーザンによって書かれた手紙です。', answer:['This','is','the','letter','written','by','Susan','.']},
    {id:'j3_13_2', explanation:'過去分詞made in Japanが後置修飾でCamerasを修飾。', japanese:'カメラは日本で作られたものがよいです。', answer:['Cameras','made','in','Japan','are','good','.']},
    {id:'j3_13_3', explanation:'with＋名詞で後置修飾。「～を持った」の意味。', japanese:'長い髪をした少女は私の友達です。', answer:['The','girl','with','long','hair','is','my','friend','.']},
    {id:'j3_13_4', explanation:'過去分詞の後置修飾。spoken in this countryがlanguageを修飾。', japanese:'この国で話されている言語はフランス語です。', answer:['The','language','spoken','in','this','country','is','French','.']},
    {id:'j3_13_5', explanation:'現在分詞の後置修飾で「見える塔」を表す。seeing a famous temple over there。', japanese:'庭で写真を撮っている男性は父です。', answer:['The','man','taking','pictures','in','the','garden','is','my','father','.']},
    {id:'j3_13_6', explanation:'現在分詞の後置修飾。taking pictures in the gardenがmanを修飾。', japanese:'奈良は、多くの人々が訪れる古い都市です。', answer:['Nara','is','an','old','city','visited','by','many','people','.']},
    {id:'j3_13_7', explanation:'過去分詞の後置修飾。visited by many peopleがcityを修飾。', japanese:'そこで売られているもののほとんどは中古品です。', answer:['Most','of','the','things','sold','there','are','used','ones','.']},
    {id:'j3_13_8', explanation:'sold thereが過去分詞の後置修飾でthingsを修飾。used onesで「中古品」。', japanese:'日本で作られた車はアメリカで人気があります。', answer:['Cars','made','in','Japan','are','popular','in','America','.']},
    {id:'j3_13_9', explanation:'過去分詞の後置修飾。made in JapanがCarsを修飾。be popular inで「～で人気がある」。', japanese:'フランス語はカナダで話される言語の１つです。', answer:['French','is','one','of','the','languages','spoken','in','Canada','.']},
    {id:'j3_13_10', explanation:'one of the＋複数名詞。spoken in Canadaが過去分詞の後置修飾。', japanese:'彼女と踊っているあの男の子はとても幸せそうです。', answer:['That','boy','dancing','with','her','looks','very','happy','.']},
    {id:'j3_13_11', explanation:'現在分詞の後置修飾。dancing with herがboyを修飾。look＋形容詞。', japanese:'簡単な日本語で書かれた物語を読んでみたらどうですか。', answer:['How','about','reading','a','story','written','in','easy','Japanese','?']},
    {id:'j3_13_12', explanation:'How about＋動名詞で提案。written in easy Japaneseが過去分詞の後置修飾。', japanese:'向こうに有名なお寺が見える塔があります。', answer:['There','is','a','tower','from','which','you','can','see','a','famous','temple','over','there','.']},
  ],
  j3_14: [
    {id:'j3_14_1', explanation:'主格の関係代名詞who（先行詞が人）。who以下が先行詞teacherを修飾。', japanese:'私はギターが弾ける先生を知っています。', answer:['I','know','a','teacher','who','can','play','the','guitar','.']},
    {id:'j3_14_2', explanation:'who are walking over thereで現在進行形。関係代名詞whoが主格。', japanese:'私は地球について教えてくれる本を見つけました。', answer:['I','found','some','books','that','tell','us','about','earth','.']},
    {id:'j3_14_3', explanation:'主格の関係代名詞that（先行詞がもの）。some books that tell usの語順。', japanese:'命を持っているものすべてを愛しなさい。', answer:['Love','everything','that','has','life','.']},
    {id:'j3_14_4', explanation:'主格の関係代名詞that（先行詞がもの・こと）。everythingを修飾。', japanese:'彼女は自分を幸せにしてくれる人を探しています。', answer:['She','is','looking','for','a','person','who','makes','her','happy','.']},
    {id:'j3_14_5', explanation:'whoが主格でpersonを修飾。make＋人＋形容詞で「人を～にする」。', japanese:'私たちに宇宙のことをたくさん教えてくれるその本は、とてもおもしろいです。', answer:['The','book','which','tells','us','a','lot','about','space','is','very','interesting','.']},
    {id:'j3_14_6', explanation:'主格の関係代名詞which（先行詞がもの）。tell＋人＋物（第4文型）。', japanese:'あなたはこの本を書いた人を知っていますか。', answer:['Do','you','know','the','man','who','wrote','this','book','?']},
    {id:'j3_14_7', explanation:'whoが主格でmanを修飾。wrote＝writeの過去形。', japanese:'臓器移植を必要としているたくさんの人々がいます。', answer:['There','are','lots','of','people','who','need','organ','transplantation','.']},
    {id:'j3_14_8', explanation:'There are～構文。whoが主格でpeopleを修飾。organ transplantationで「臓器移植」。', japanese:'あちらで歩いているあの少女とそのイヌを見てください。', answer:['Look','at','that','girl','who','is','walking','over','there','and','her','dog','.']},
  ],
  j3_15: [
    {id:'j3_15_1', explanation:'目的格の関係代名詞thatは省略可能。you met～がboyを修飾。', japanese:'あなたが昨日会った少年はトムです。', answer:['The','boy','you','met','yesterday','was','Tom','.']},
    {id:'j3_15_2', explanation:'目的格の関係代名詞が省略。we visited～がparkを修飾。', japanese:'これは２年前に訪れた公園です。', answer:['This','is','the','park','we','visited','two','years','ago','.']},
    {id:'j3_15_3', explanation:'主格の関係代名詞who。knows English very wellがboyを修飾。', japanese:'これは今まで読んだ中で最も良い本です。', answer:['This','is','the','best','book','I\'ve','ever','read','.']},
    {id:'j3_15_4', explanation:'to do yesterdayが形容詞的用法でhomeworkを修飾。', japanese:'札幌は私が訪れたいと思っている都市の１つです。', answer:['Sapporo','is','one','of','the','cities','that','I','want','to','visit','.']},
    {id:'j3_15_5', explanation:'the best book I've ever readで目的格の関係代名詞が省略。I'veはI haveの短縮形。', japanese:'きのうテレビで見たニュースにぼくは腹が立ちました。', answer:['The','news','that','I','saw','on','TV','yesterday','made','me','angry','.']},
    {id:'j3_15_6', explanation:'目的格の関係代名詞that。one of the＋複数名詞で「～の1つ」。', japanese:'あなたがきのう買った本を見せてください。', answer:['Please','show','me','the','book','that','you','bought','yesterday','.']},
    {id:'j3_15_7', explanation:'thatが目的格でnewsを修飾。make＋人＋形容詞（第5文型）。', japanese:'私たちは彼女が飼っているネコを見たことがありません。', answer:['We','have','never','seen','the','cat','which','she','has','.']},
    {id:'j3_15_8', explanation:'thatが目的格でbookを修飾。show＋人＋物（第4文型）。', japanese:'あなたがコンサートに招待した少女は幸せそうです。', answer:['The','girl','you','invited','to','the','concert','looks','happy','.']},
    {id:'j3_15_9', explanation:'whichが目的格でcatを修飾。neverで経験がないことを表す。', japanese:'何か私にできることがありますか。', answer:['Is','there','anything','I','can','do','for','you','?']},
    {id:'j3_15_10', explanation:'目的格の関係代名詞が省略された形。look＋形容詞（第2文型）。', japanese:'ジョンは英語を非常によく知っているオーストラリア少年です。', answer:['John','is','an','Australian','boy','who','knows','English','very','well','.']},
    {id:'j3_15_11', explanation:'anythingを関係代名詞節が修飾。Is there～?で「～はありますか」。', japanese:'昨日する予定だった宿題はとても難しかったです。', answer:['The','homework','to','do','yesterday','was','very','difficult','.']},
  ],
  j3_16: [
    {id:'j3_16_1', explanation:'比較級はtall→tallerと-erをつける。than～で比較対象を示す。', japanese:'私の兄は母より背が高いです。', answer:['My','brother','is','taller','than','my','mother','.']},
    {id:'j3_16_2', explanation:'副詞の比較級fast→faster。thatはoneで繰り返しを避ける。', japanese:'この車はあの車より速く走れます。', answer:['This','car','can','run','faster','than','that','one','.']},
    {id:'j3_16_3', explanation:'more CDs than you.でCDsは比較対象がmoreで「より多くの」。', japanese:'私はあなたよりたくさんのCDを持っています。', answer:['I','have','more','CDs','than','you','.']},
    {id:'j3_16_4', explanation:'good→betterと不規則変化の比較級。mineは所有代名詞。', japanese:'あなたのコンピュータは私のより性能がよいです。', answer:['Your','computer','is','better','than','mine','.']},
    {id:'j3_16_5', explanation:'difficult→more difficultと長い形容詞はmore～で比較級。', japanese:'数学は私にとって英語より難しいです。', answer:['Math','is','more','difficult','than','English','for','me','.']},
    {id:'j3_16_6', explanation:'as＋形容詞/副詞＋asで「～と同じくらい…」。', japanese:'由美はマイクと同年です。', answer:['Yumi','is','as','old','as','Mike','.']},
    {id:'j3_16_7', explanation:'not as busy as～で「～ほど…でない」。', japanese:'私はあなたほど忙しくありません。', answer:['I\'m','not','as','busy','as','you','.']},
    {id:'j3_16_8', explanation:'twice as many books as Tom.でtwice as many＋名詞＋asで「2倍の…」。', japanese:'私はトムの２倍の数の本を持っています。', answer:['I','have','twice','as','many','books','as','Tom','.']},
    {id:'j3_16_9', explanation:'one of the＋最上級＋複数名詞で「最も～な…の1つ」。', japanese:'彼は世界で最も有名なピアニストの１人です。', answer:['He','is','one','of','the','most','famous','pianists','in','the','world','.']},
    {id:'j3_16_10', explanation:'Which＋do you like better, A or B?でAとBを比較。', japanese:'あなたは英語と数学ではどちらのほうが好きですか。', answer:['Which','do','you','like','better','English','or','math','?']},
    {id:'j3_16_11', explanation:'the best of all sports.でwell→bestと不規則最上級。of all～で「すべての～の中で」。', japanese:'私はすべてのスポーツの中でサッカーがいちばん好きです。', answer:['I','like','soccer','the','best','of','all','sports','.']},
    {id:'j3_16_12', explanation:'as＋副詞/形容詞＋as＋主語＋canで「できるだけ～」。', japanese:'できるだけ速く歩きなさい。', answer:['Walk','as','fast','as','you','can','.']},
  ],
  j3_17: [
    {id:'j3_17_1', explanation:'一般動詞の過去疑問文はDid＋主語＋動詞原形～?', japanese:'あなたはきのうの夜、お店に行きましたか。', answer:['Did','you','go','to','the','shop','last','night','?']},
    {id:'j3_17_2', explanation:'Is it an old movie?でbe動詞の疑問文はIsを主語の前に出す。', japanese:'それは古い映画ですか。', answer:['Is','it','an','old','movie','?']},
    {id:'j3_17_3', explanation:'Does Jun like baseball?で3単現の疑問文はDoesを使う。', japanese:'ジュンは野球が好きですか。', answer:['Does','Jun','like','baseball','?']},
    {id:'j3_17_4', explanation:'Let's go to the cafeteria.でLet'sは「～しましょう」。', japanese:'どの電車に乗ったのですか。', answer:['Which','train','did','you','take','?']},
    {id:'j3_17_5', explanation:'Which train did you take?でWhich＋名詞＋did＋主語＋動詞原形?', japanese:'あした公園を散歩しませんか。', answer:['How','about','taking','a','walk','in','the','park','tomorrow','?']},
    {id:'j3_17_6', explanation:'How about taking a walk in the park tomorrow?でHow about＋動名詞で提案。', japanese:'ひと月に何冊の本を読みますか。', answer:['How','many','books','do','you','read','a','month','?']},
    {id:'j3_17_7', explanation:'How many books do you read a month?でa monthは「1か月に」。', japanese:'由美は料理が好きですね。', answer:['Yumi','likes','cooking','doesn\'t','she','?']},
    {id:'j3_17_8', explanation:'付加疑問文：肯定文の後にコンマ＋否定の短縮形＋主語の代名詞?', japanese:'佐藤先生は歌いませんでしたね。', answer:['Mr.','Sato','didn\'t','sing','did','he','?']},
    {id:'j3_17_9', explanation:'否定文の付加疑問：否定文の後にコンマ＋肯定形＋主語の代名詞?', japanese:'彼らは昨晩、一睡もしなかったのですか。', answer:['Didn\'t','they','sleep','at','all','last','night','?']},
    {id:'j3_17_10', explanation:'at allは否定文で「全く～ない」を強調。付加疑問はdid they?', japanese:'食堂に行きましょうか。', answer:['Let\'s','go','to','the','cafeteria','.']},
  ],
  j3_18: [
    {id:'j3_18_1', explanation:'間接疑問文では疑問詞＋主語＋動詞の語順（疑問文の語順にならない）。', japanese:'あなたは英語の先生がどこに住んでいるか知っていますか。', answer:['Do','you','know','where','your','English','teacher','lives','?']},
    {id:'j3_18_2', explanation:'間接疑問文のwhat節は疑問文の語順でなく平叙文の語順。', japanese:'彼は彼女が手に何を持っていたか知りませんでした。', answer:['He','didn\'t','know','what','she','had','in','her','hands','.']},
    {id:'j3_18_3', explanation:'I don't know when she came to Japan.でwhen節は平叙文の語順。', japanese:'私は彼女が日本に来たときを知りません。', answer:['I','don\'t','know','when','she','came','to','Japan','.']},
    {id:'j3_18_4', explanation:'間接疑問文ではwho＋主語＋動詞の語順。knew＝knowの過去形。', japanese:'彼らはその男性がだれだか知っていました。', answer:['They','knew','who','the','man','was','.']},
    {id:'j3_18_5', explanation:'Do you know where her mother put her bag?の語順。', japanese:'あなたは彼女のお母さんがどこにかばんを置いたか知っていますか。', answer:['Do','you','know','where','her','mother','put','the','bag','?']},
    {id:'j3_18_6', explanation:'疑問詞＋to不定詞で「どう～すべきか」。tell＋人＋疑問詞節（第4文型）。', japanese:'その植物をどのように育てたらよいのか彼らに教えてくれませんか。', answer:['Will','you','tell','them','how','to','grow','the','plant','?']},
    {id:'j3_18_7', explanation:'what kind of＋名詞で「どんな種類の～」。間接疑問文の語順。', japanese:'彼女がどんなセーターを買ったか知りません。', answer:['I','don\'t','know','what','kind','of','sweater','she','bought','.']},
    {id:'j3_18_8', explanation:'間接疑問文。where節の中は平叙文の語順（she lives）。', japanese:'あなたは彼女がどこに住んでいるか知っていますか。', answer:['Do','you','know','where','she','lives','?']},
    {id:'j3_18_9', explanation:'tell＋人＋間接疑問文。what節は平叙文の語順（she should do）。', japanese:'彼女が何をすべきか彼女に話しなさい。', answer:['Tell','her','what','she','should','do','.']},
    {id:'j3_18_10', explanation:'the story he told me.で目的格の関係代名詞が省略。', japanese:'私は彼が話してくれた話を覚えていません。', answer:['I','don\'t','remember','the','story','he','told','me','.']},
  ],
  j3_19: [
    {id:'j3_19_1', explanation:'Be careful when you walk across the street.でBe＋形容詞の命令文。', japanese:'通りを渡るときは注意しなさい。', answer:['Be','careful','when','you','walk','across','the','street','.']},
    {id:'j3_19_2', explanation:'How beautiful these pictures are!でHow＋形容詞＋主語＋動詞！の感嘆文。', japanese:'これらの絵はなんて美しいのでしょう。', answer:['How','beautiful','these','pictures','are','!']},
    {id:'j3_19_3', explanation:'Look carefully, and you'll see what this is.でand「そうすれば」。', japanese:'注意して見なさい。そうすればこれが何かわかるでしょう。', answer:['Look','carefully','and','you\'ll','see','what','this','is','.']},
    {id:'j3_19_4', explanation:'Don't be noisy in the classroom.でDon't be＋形容詞の否定命令文。', japanese:'部屋の中では騒いではいけません。', answer:['Don\'t','be','noisy','in','the','classroom','.']},
    {id:'j3_19_5', explanation:'If you don't～, you'll～.でIfで条件を表す。', japanese:'この機械を注意して使わないと、壊してしまうでしょう。', answer:['If','you','don\'t','use','this','machine','carefully','you\'ll','break','it','.']},
    {id:'j3_19_6', explanation:'How good a pianist she is!でHow＋形容詞（＋名詞）＋主語＋動詞！', japanese:'彼女はなんてじょうずにピアノを弾くのでしょう。', answer:['How','good','a','pianist','she','is','!']},
    {id:'j3_19_7', explanation:'tell＋人＋物（第4文型）。the way to～で「～への道」。', japanese:'郵便局へ行く道を教えてください。', answer:['Please','tell','me','the','way','to','the','post','office','.']},
    {id:'j3_19_8', explanation:'be late for～で「～に遅刻する」。否定命令文でDon't beを使う。', japanese:'学校に遅刻してはいけません。', answer:['Don\'t','be','late','for','school','.']},
    {id:'j3_19_9', explanation:'What a cute cat you have!でWhat（a/an）＋形容詞＋名詞＋主語＋動詞！', japanese:'なんてかわいいネコでしょう。', answer:['What','a','cute','cat','you','have','!']},
  ],
  j3_20: [
    {id:'j3_20_1', explanation:'仮定法過去：If＋主語＋were～, 主語＋would＋動詞原形。IでもwereToを使う。', japanese:'私があなたなら、あなたのお母さんに助けを求めるでしょう。', answer:['If','I','were','you','I','would','ask','your','mother','for','help','.']},
    {id:'j3_20_2', explanation:'If I had the key, I could open this suitcase.でhadは仮定法過去。', japanese:'かぎを持っていれば、このスーツケースを開けることができるのに。', answer:['If','I','had','the','key','I','could','open','this','suitcase','.']},
    {id:'j3_20_3', explanation:'仮定法の条件節はIf＋主語＋動詞の過去形（または現在形）。', japanese:'雨が降っていなければ散歩に行くのに。', answer:['I','would','go','for','a','walk','if','it','were','not','raining','.']},
    {id:'j3_20_4', explanation:'If it were not raining, I would go for a walk.でgo for a walkは「散歩する」。', japanese:'学校がうちの近くにあればいいのに。', answer:['I','wish','school','were','near','my','house','.']},
    {id:'j3_20_5', explanation:'I wish＋主語＋動詞の過去形（仮定法過去）で「～ならいいのに」。', japanese:'こんなに暑くなければいいのに。', answer:['I','wish','it','were','not','so','hot','.']},
    {id:'j3_20_6', explanation:'I wish＋仮定法過去。so＋形容詞で「こんなに～」。', japanese:'母が犬を好きだったらなあ。', answer:['I','wish','my','mother','liked','dogs','.']},
    {id:'j3_20_7', explanation:'I wish my mother liked dogs.でlikedは仮定法過去。', japanese:'ピアノが弾けたらなあ。', answer:['I','wish','I','could','play','the','piano','.']},
    {id:'j3_20_8', explanation:'I wish＋主語＋could＋動詞原形で「～できればいいのに」。', japanese:'もし人々が車を使うのをやめたら、何が起こるでしょうか。', answer:['What','would','happen','if','people','stopped','using','a','car','?']},
    {id:'j3_20_9', explanation:'仮定法過去：If節の動詞は過去形、主節はwould＋動詞原形。', japanese:'彼が私の言うことをもっと注意深く聞いてくれればなあ。', answer:['I','wish','he','listened','to','me','more','carefully','.']},
    {id:'j3_20_10', explanation:'I wish he listened to me more carefully.でlistenedは仮定法過去。', japanese:'もし夏休みがもっと長ければ、本をもっと読めるのに。', answer:['If','our','summer','vacation','were','longer','I','could','read','more','books','.']},
    {id:'j3_20_11', explanation:'仮定法過去。If節にwere、主節にcould。', japanese:'ジムは、あしたひまなら公園に来るでしょう。', answer:['If','Jim','is','free','tomorrow','he','would','come','to','the','park','.']},
  ],
}
