// 中学2年 全問題データ
export const QUESTIONS_J2 = {
  j2_1: [
    {id:'j2_1_1', explanation:'walk→walkedと規則動詞の過去形。',  japanese:'トムはきのう歩いて学校へ行きました。',answer:['Tom','walked','to','school','yesterday','.']},
    {id:'j2_1_2', explanation:'stop→stoppedと語尾の子音字を重ねてed。',  japanese:'そのときその車は止まりました。',answer:['The','car','stopped','then','.']},
    {id:'j2_1_3', explanation:'run→ranと不規則変化。',  japanese:'まことは今朝走って公園へ行きました。',answer:['Makoto','ran','to','the','park','this','morning','.']},
    {id:'j2_1_4', explanation:'say→saidと不規則変化。',  japanese:'父は私に「おはよう」と言いました。',answer:['My','father','said','Good','morning','to','me','.']},
    {id:'j2_1_5', explanation:'see→sawと不規則変化。',  japanese:'私たちは１ぴきの黒いネコを見ました。',answer:['We','saw','a','black','cat','.']},
    {id:'j2_1_6', explanation:'did not callで過去の否定文。call→calledは規則動詞。',  japanese:'ナンシーにきのう電話しませんでした。',answer:['I','did','not','call','Nancy','yesterday','.']},
    {id:'j2_1_7', explanation:'did not takeで過去の否定文。take→tookと不規則変化。',  japanese:'私たちは庭で写真を撮りませんでした。',answer:['We','did','not','take','any','pictures','in','the','garden','.']},
    {id:'j2_1_8', explanation:'buy→boughtと不規則変化。',  japanese:'ユキは新しい自転車を買いませんでした。',answer:['Yuki','did','not','buy','a','new','bike','.']},
    {id:'j2_1_9', explanation:'Did Taro play～?で過去の疑問文。',  japanese:'タロウはギターを弾きましたか。',answer:['Did','Taro','play','the','guitar','?']},
    {id:'j2_1_10', explanation:'go→wentと不規則変化。', japanese:'生徒たちは図書館に行きましたか。',answer:['Did','the','students','go','to','the','library','?']},
    {id:'j2_1_11', explanation:'go→wentと不規則変化。', japanese:'彼は昨日図書館に行きました。',answer:['He','went','to','the','library','yesterday','.']},
    {id:'j2_1_12', explanation:'write→wroteと不規則変化。', japanese:'彼女は手紙を書きました。',answer:['She','wrote','a','letter','.']},
    {id:'j2_1_13', explanation:'come→cameと不規則変化。', japanese:'彼らは去年日本に来ました。',answer:['They','came','to','Japan','last','year','.']},
    {id:'j2_1_14', explanation:'give→gaveと不規則変化。gave me a bikeで「私に自転車をくれた」。', japanese:'彼は私に自転車をくれました。',answer:['He','gave','me','a','bike','.']},
    {id:'j2_1_15', explanation:'know→knewと不規則変化。', japanese:'彼女はそのニュースを知っていました。',answer:['She','knew','the','news','.']},
    {id:'j2_1_16', explanation:'meet→metと不規則変化。', japanese:'私はきのうケンに会いました。',answer:['I','met','Ken','yesterday','.']},
    {id:'j2_1_17', explanation:'come→cameと不規則変化。', japanese:'彼らはきのうここに来ました。',answer:['They','came','here','yesterday','.']},
    {id:'j2_1_18', explanation:'read→readと同形（発音はred）。', japanese:'彼女はその本を読みました。',answer:['She','read','the','book','.']},
    {id:'j2_1_19', explanation:'play→playedと規則動詞の過去形。', japanese:'私はきのうテニスをしました。',answer:['I','played','tennis','yesterday','.']},
    {id:'j2_1_20', explanation:'run→ranと不規則変化。', japanese:'彼はきのう公園を走りました。',answer:['He','ran','in','the','park','yesterday','.']},
    {id:'j2_1_21', explanation:'go→wentと不規則変化。', japanese:'私はきのう図書館に行きました。',answer:['I','went','to','the','library','yesterday','.']},
    {id:'j2_1_22', explanation:'What did she eat?でeat→ate（過去形）。', japanese:'彼女はきのう何を食べましたか。',answer:['What','did','she','eat','yesterday','?']},
    {id:'j2_1_23', explanation:'did not comeで過去の否定文。', japanese:'彼らはきのう学校に来ませんでした。',answer:['They','did','not','come','to','school','yesterday','.']},
    {id:'j2_1_24', explanation:'Where did you go?でgo→went。', japanese:'あなたはきのうどこに行きましたか。',answer:['Where','did','you','go','yesterday','?']},
  ],
  j2_2: [
    {id:'j2_2_1', explanation:'I/He/She→was、You/We/They→were。',  japanese:'私はきのう忙しかったです。',  answer:['I','was','busy','yesterday','.']},
    {id:'j2_2_2', explanation:'They wereで複数→were。',  japanese:'彼らはきのうここにいました。',answer:['They','were','here','yesterday','.']},
    {id:'j2_2_3', explanation:'was notで過去の否定文。',  japanese:'彼女はきのう家にいませんでした。',answer:['She','was','not','at','home','yesterday','.']},
    {id:'j2_2_4', explanation:'Where were you?で過去の疑問文。',  japanese:'あなたはきのうどこにいましたか。',answer:['Where','were','you','yesterday','?']},
    {id:'j2_2_5', explanation:'was＋動詞ing形で過去進行形。',  japanese:'私はそのとき本を読んでいました。',answer:['I','was','reading','a','book','then','.']},
    {id:'j2_2_6', explanation:'Was she～ing?で過去進行形の疑問文。',  japanese:'彼女はそのとき歌を歌っていましたか。',answer:['Was','She','singing','songs','?']},
    {id:'j2_2_7', explanation:'were not～ingで過去進行形の否定。',  japanese:'彼らはそのとき野球をしていませんでした。',answer:['They','were','not','playing','baseball','.']},
    {id:'j2_2_8', explanation:'I/He/She→was、You/We/They→were。',  japanese:'彼はきのう病気でした。',      answer:['He','was','sick','yesterday','.']},
    {id:'j2_2_9', explanation:'She was at school.で場所を表す。',  japanese:'彼女はきのう学校にいました。',answer:['She','was','at','school','yesterday','.']},
    {id:'j2_2_10', explanation:'were notで過去の否定文（複数）。', japanese:'私たちはきのう公園にいませんでした。',answer:['We','were','not','in','the','park','yesterday','.']},
    {id:'j2_2_11', explanation:'What were you doing?で過去進行形の疑問文。', japanese:'あなたはきのう何をしていましたか。',answer:['What','were','you','doing','yesterday','?']},
    {id:'j2_2_12', explanation:'was studying～で過去進行形。', japanese:'彼はそのとき英語を勉強していました。',answer:['He','was','studying','English','then','.']},
    {id:'j2_2_13', explanation:'Was she cooking?で過去進行形の疑問文。', japanese:'彼女はそのとき料理をしていましたか。',answer:['Was','she','cooking','?']},
    {id:'j2_2_14', explanation:'were not listening to～で過去進行形の否定。', japanese:'彼らはそのとき音楽を聴いていませんでした。',answer:['They','were','not','listening','to','music','.']},
  ],
  j2_3: [
    {id:'j2_3_1', explanation:'be going to＋動詞原形で「～するつもり」。',  japanese:'私たちは彼をパーティーに招くつもりです。',answer:['We','are','going','to','invite','him','to','the','party','.']},
    {id:'j2_3_2', explanation:'He is going to take～でisを使う。for a walkで「散歩に」。',  japanese:'彼はきょうの午後、犬を散歩に連れていくつもりです。',answer:['He','is','going','to','take','his','dog','for','a','walk','this','afternoon','.']},
    {id:'j2_3_3', explanation:'My mother is going to play～でisを使う。',  japanese:'私の母はあしたテニスをするつもりです。',answer:['My','mother','is','going','to','play','tennis','tomorrow','.']},
    {id:'j2_3_4', explanation:'am not going toで否定のbe going to。',  japanese:'今晩、ピアノの練習をするつもりはありません。',answer:['I','am','not','going','to','practice','the','piano','this','evening','.']},
    {id:'j2_3_5', explanation:'Are you going to send～?で疑問文。',  japanese:'あなたはこの手紙を彼女に送るつもりですか。',answer:['Are','you','going','to','send','this','letter','to','her','?']},
    {id:'j2_3_6', explanation:'What is he going to do?の語順。',  japanese:'彼はあした何をするつもりですか。',answer:['What','is','he','going','to','do','tomorrow','?']},
    {id:'j2_3_7', explanation:'She is going to see a movie.でseeは「映画を見る」。',  japanese:'彼女はあした映画を見るつもりです。',answer:['She','is','going','to','see','a','movie','tomorrow','.']},
    {id:'j2_3_8', explanation:'They are going to come～でareを使う。',  japanese:'彼らは来週日本に来るつもりです。',answer:['They','are','going','to','come','to','Japan','next','week','.']},
    {id:'j2_3_9', explanation:'I'm not going to study～で否定。',  japanese:'私はあした英語を勉強するつもりはありません。',answer:['I','am','not','going','to','study','English','tomorrow','.']},
    {id:'j2_3_10', explanation:'What are you going to do?の語順。', japanese:'あなたはあした何をするつもりですか。',answer:['What','are','you','going','to','do','tomorrow','?']},
    {id:'j2_3_11', explanation:'is going to go skiing～でgo skiing「スキーに行く」。', japanese:'彼は来週スキーに行くつもりです。',answer:['He','is','going','to','go','skiing','next','week','.']},
  ],
  j2_4: [
    {id:'j2_4_1', explanation:'will＋動詞原形で未来を表す。',  japanese:'私は来週サッカーをするつもりです。',answer:['I','will','play','soccer','next','week','.']},
    {id:'j2_4_2', explanation:'will go to～で「～に行くでしょう」。',  japanese:'彼女はあした図書館に行くでしょう。',answer:['She','will','go','to','the','library','tomorrow','.']},
    {id:'j2_4_3', explanation:'will not come～で否定文（short form: won't）。',  japanese:'彼はあしたここに来ないでしょう。',answer:['He','will','not','come','here','tomorrow','.']},
    {id:'j2_4_4', explanation:'Will you～?で疑問文。',  japanese:'あなたはあした映画を見ますか。',answer:['Will','you','see','a','movie','tomorrow','?']},
    {id:'j2_4_5', explanation:'Where will you go～?の語順。',  japanese:'あなたは来年どこに行きますか。',answer:['Where','will','you','go','next','year','?']},
    {id:'j2_4_6', explanation:'What will she do～?の語順。',  japanese:'彼女はあした何をしますか。',  answer:['What','will','she','do','tomorrow','?']},
    {id:'j2_4_7', explanation:'will meet my friend～でmeetは「会う」。',  japanese:'私はあした友達に会うでしょう。',answer:['I','will','meet','my','friend','tomorrow','.']},
    {id:'j2_4_8', explanation:'will become a doctor～でbecomeは「～になる」。',  japanese:'彼は来年医者になるでしょう。',answer:['He','will','become','a','doctor','next','year','.']},
    {id:'j2_4_9', explanation:'will not come～で否定文。',  japanese:'彼女は来週ここに来ないでしょう。',answer:['She','will','not','come','here','next','week','.']},
    {id:'j2_4_10', explanation:'Will you study English?の語順。', japanese:'あなたは来月英語を勉強しますか。',answer:['Will','you','study','English','next','month','?']},
    {id:'j2_4_11', explanation:'They will come to Japan～でwillの後は原形。', japanese:'彼らは来週日本に来るでしょう。',answer:['They','will','come','to','Japan','next','week','.']},
    {id:'j2_4_12', explanation:'What will you do tomorrow?の語順。', japanese:'あなたはあした何をしますか。',answer:['What','will','you','do','tomorrow','?']},
  ],
  j2_5: [
    {id:'j2_5_1', explanation:'can＋動詞原形で「～できる」。',  japanese:'私はすき焼きを作ることができます。',answer:['I','can','make','sukiyaki','.']},
    {id:'j2_5_2', explanation:'Can Tom play the guitar?でcanの後は原形。',  japanese:'トムはギターを弾くことができます。',answer:['Tom','can','play','the','guitar','.']},
    {id:'j2_5_3', explanation:'can eat this cakeで「食べてもよい」（許可）。',  japanese:'あなたはこのケーキを食べてもいいです。',answer:['You','can','eat','this','cake','.']},
    {id:'j2_5_4', explanation:'couldn't walk fast.でcouldn'tはcould notの短縮形。',  japanese:'彼女は速く歩くことができませんでした。',answer:['She','couldn\'t','walk','fast','.']},
    {id:'j2_5_5', explanation:'You can use this pen.で許可を表す。',  japanese:'あなたはこのペンを使ってもいいですよ。',answer:['You','can','use','this','pen','.']},
    {id:'j2_5_6', explanation:'may come here～でmayは「～かもしれない」。',  japanese:'トムはきょう、ここに来るかもしれません。',answer:['Tom','may','come','here','today','.']},
    {id:'j2_5_7', explanation:'That woman may be Kate's mother.でmayは推量。',  japanese:'あの女の人はケイトのお母さんかもしれません。',answer:['That','woman','may','be','Kate\'s','mother','.']},
    {id:'j2_5_8', explanation:'have to go to school.でhave toは「～しなければならない」。',  japanese:'私はきょう、学校へ行かなければなりません。',answer:['I','have','to','go','to','school','today','.']},
    {id:'j2_5_9', explanation:'Kumi has to read～でhasは3単現。',  japanese:'クミはこの本を読まなければなりません。',answer:['Kumi','has','to','read','this','book','.']},
    {id:'j2_5_10', explanation:'Keiko must be free.でmustは「～にちがいない」。', japanese:'けい子は今、ひまにちがいありません。',answer:['Keiko','must','be','free','now','.']},
    {id:'j2_5_11', explanation:'We should clean this room.でshouldは「～すべき」。', japanese:'私たちはこの部屋をきれいにするべきです。',answer:['We','should','clean','this','room','.']},
    {id:'j2_5_12', explanation:'He should help Yuki.でshouldは「～すべき」。', japanese:'彼はユキを手伝うべきです。',  answer:['He','should','help','Yuki','.']},
    {id:'j2_5_13', explanation:'has breakfast with us～でhaveは「食事をする」。', japanese:'妹は私たちと朝食を食べるべきです。',answer:['My','sister','has','breakfast','with','us','.']},
    {id:'j2_5_14', explanation:'can＋動詞原形で「～できる」。', japanese:'私は英語を話すことができます。',answer:['I','can','speak','English','.']},
    {id:'j2_5_15', explanation:'Can she play the piano?でcanの後は原形。', japanese:'彼女はピアノを弾くことができますか。',answer:['Can','she','play','the','piano','?']},
    {id:'j2_5_16', explanation:'He may come here.でmayは「～かもしれない」。', japanese:'彼はここに来るかもしれません。',answer:['He','may','come','here','.']},
    {id:'j2_5_17', explanation:'have to do my homework.でhave toは「～しなければ」。', japanese:'私はきょう宿題をしなければなりません。',answer:['I','have','to','do','my','homework','today','.']},
    {id:'j2_5_18', explanation:'should study English.でshouldは「～すべき」。', japanese:'彼女は毎日英語を勉強すべきです。',answer:['She','should','study','English','every','day','.']},
    {id:'j2_5_19', explanation:'must not swim here.でmust notは「～してはいけない」（禁止）。', japanese:'あなたはここで泳いではいけません。',answer:['You','must','not','swim','here','.']},
  ],
  j2_6: [
    {id:'j2_6_1', explanation:'Will you～?で「～してくれませんか」（依頼）。',  japanese:'ドアを開けてくれませんか。',  answer:['Will','you','open','the','door','?']},
    {id:'j2_6_2', explanation:'Will you bring me～?でbring me a glass of waterの語順。',  japanese:'お水を１杯持ってきてくれませんか。',answer:['Will','you','bring','me','a','glass','of','water','?']},
    {id:'j2_6_3', explanation:'Would you have some coffee?でWould youはより丁寧な依頼。',  japanese:'コーヒーはいかがですか。',    answer:['Would','you','have','some','coffee','?']},
    {id:'j2_6_4', explanation:'Shall I～?で「～しましょうか」（申し出）。',  japanese:'そのかばんを選びましょうか。',answer:['Shall','I','carry','the','bag','?']},
    {id:'j2_6_5', explanation:'Shall we go on a picnic?でShall weは「一緒に～しましょう」。',  japanese:'今度の日曜日にピクニックに行きましょうか。',answer:['Shall','we','go','on','a','picnic','next','Sunday','?']},
    {id:'j2_6_6', explanation:'You should go to bed early.でshouldは「～すべき」。',  japanese:'あなたは早く寝るべきです。',  answer:['You','should','go','to','bed','early','.']},
    {id:'j2_6_7', explanation:'I would like to visit Okinawa.でwould like toは「～したい」（丁寧）。',  japanese:'私は沖縄をまた訪れたいものです。',answer:['I','would','like','to','visit','Okinawa','again','.']},
    {id:'j2_6_8', explanation:'Would you like some tea?で「～はいかがですか」。',  japanese:'お茶はいかがですか。',        answer:['Would','you','like','some','tea','?']},
    {id:'j2_6_9', explanation:'Will you open the window?で依頼。',  japanese:'窓を開けてくれませんか。',    answer:['Will','you','open','the','window','?']},
    {id:'j2_6_10', explanation:'Shall we play tennis?で勧誘。', japanese:'テニスをしましょうか。',      answer:['Shall','we','play','tennis','?']},
    {id:'j2_6_11', explanation:'Can I help you?で「お手伝いしましょうか」。', japanese:'何かお手伝いしましょうか。',  answer:['Can','I','help','you','?']},
    {id:'j2_6_12', explanation:'Would you like some tea?で「～はいかがですか」。', japanese:'お茶はいかがですか。',        answer:['Would','you','like','some','tea','?']},
    {id:'j2_6_13', explanation:'I'd like to invite him～でwould like toは「～したい」（丁寧）。', japanese:'私は彼を家に招待したいと思っています。',answer:['I','would','like','to','invite','him','to','my','house','.']},
    {id:'j2_6_14', explanation:'Let's play soccer.でLet'sは「～しましょう」。', japanese:'一緒にサッカーをしましょう。',answer:['Let\'s','play','soccer','together','.']},
  ],
  j2_7: [
    {id:'j2_7_1', explanation:'There is＋単数名詞で「～があります」。',  japanese:'机の上に本が１冊あります。',  answer:['There','is','a','book','on','the','desk','.']},
    {id:'j2_7_2', explanation:'There are＋複数名詞で「～があります」。',  japanese:'公園に子どもたちがいます。',  answer:['There','are','children','in','the','park','.']},
    {id:'j2_7_3', explanation:'There are three apples.で複数→are。',  japanese:'テーブルの上にりんごが３つあります。',answer:['There','are','three','apples','on','the','table','.']},
    {id:'j2_7_4', explanation:'There aren't any～で否定文。',  japanese:'庭に花はありません。',        answer:['There','aren\'t','any','flowers','in','the','garden','.']},
    {id:'j2_7_5', explanation:'Is there anything～?で疑問文。',  japanese:'箱の中に何かありますか。',    answer:['Is','there','anything','in','the','box','?']},
    {id:'j2_7_6', explanation:'How many students are there?で数を尋ねる。',  japanese:'部屋に何人の学生がいますか。',answer:['How','many','students','are','there','in','the','room','?']},
    {id:'j2_7_7', explanation:'There is＋単数名詞で「～があります」。',  japanese:'この町には図書館が１つあります。',answer:['There','is','a','library','in','this','town','.']},
    {id:'j2_7_8', explanation:'There are＋複数名詞で「～があります」。',  japanese:'部屋に犬が２匹います。',      answer:['There','are','two','dogs','in','the','room','.']},
    {id:'j2_7_9', explanation:'There isn't anything～で否定文。',  japanese:'テーブルの下には何もありません。',answer:['There','isn\'t','anything','under','the','table','.']},
    {id:'j2_7_10', explanation:'Is there a park near～?で疑問文。', japanese:'学校の近くに公園はありますか。',answer:['Is','there','a','park','near','the','school','?']},
    {id:'j2_7_11', explanation:'How many hospitals are there?で数を尋ねる。', japanese:'この町には病院が何軒ありますか。',answer:['How','many','hospitals','are','there','in','this','town','?']},
  ],
  j2_8: [
    {id:'j2_8_1', explanation:'Please＋動詞原形で丁寧な命令文。',  japanese:'ドアを開けてください。',      answer:['Open','the','door','please','.']},
    {id:'j2_8_2', explanation:'Don't～で否定命令文。',  japanese:'走らないでください。',        answer:['Don\'t','run','.']},
    {id:'j2_8_3', explanation:'Be quiet.でbe動詞の命令文。',  japanese:'静かにしなさい。',            answer:['Be','quiet','.']},
    {id:'j2_8_4', explanation:'What（a/an）＋形容詞＋名詞！で感嘆文。',  japanese:'なんてすばらしい日でしょう！',answer:['What','a','beautiful','day','!']},
    {id:'j2_8_5', explanation:'How good a singer!でHow～の感嘆文。',  japanese:'なんてじょうずな歌手でしょう！',answer:['How','a','good','singer','!']},
    {id:'j2_8_6', explanation:'What a big house!で感嘆文。',  japanese:'なんて大きい家でしょう！',    answer:['What','a','big','house','!']},
    {id:'j2_8_7', explanation:'Study English.で動詞原形で始める命令文。',  japanese:'英語を勉強しなさい。',        answer:['Study','English','.']},
    {id:'j2_8_8', explanation:'Don't swim here.で否定命令文。',  japanese:'ここで泳がないでください。',  answer:['Don\'t','swim','here','.']},
    {id:'j2_8_9', explanation:'What a cute baby!でWhat a＋形容詞＋名詞！',  japanese:'なんてかわいい赤ちゃんでしょう！',answer:['What','a','cute','baby','!']},
    {id:'j2_8_10', explanation:'Be nice to your friends.でbe動詞の命令文。', japanese:'友達と仲良くしなさい。',      answer:['Be','nice','to','your','friends','.']},
    {id:'j2_8_11', explanation:'What a difficult problem!でWhat a＋形容詞＋名詞！', japanese:'なんて難しい問題でしょう！',  answer:['What','a','difficult','problem','!']},
  ],
  j2_9: [
    {id:'j2_9_1', explanation:'Where is she going?で現在進行形の疑問文。',  japanese:'彼女はどこに行くつもりですか。',answer:['Where','is','she','going','to','go','?']},
    {id:'j2_9_2', explanation:'How often～?で頻度を尋ねる。',  japanese:'あなたはどのくらい英語を勉強しますか。',answer:['How','often','do','you','study','English','?']},
    {id:'j2_9_3', explanation:'How old～?で年齢を尋ねる。',  japanese:'彼は何歳ですか。',            answer:['How','old','is','he','?']},
    {id:'j2_9_4', explanation:'How long～?で長さ・期間を尋ねる。',  japanese:'この橋はどのくらいの長さですか。',answer:['How','long','is','this','bridge','?']},
    {id:'j2_9_5', explanation:'How do you come～?で方法を尋ねる。',  japanese:'あなたはどうやって学校に来ますか。',answer:['How','do','you','come','to','school','?']},
    {id:'j2_9_6', explanation:'You like soccer, don't you?で付加疑問文（肯定→否定）。',  japanese:'あなたはサッカーが好きですよね。',answer:['You','like','soccer','don\'t','you','?']},
    {id:'j2_9_7', explanation:'She is from here, isn't she?で付加疑問文。',  japanese:'彼女はここの出身ですよね。',  answer:['She','is','from','here','isn\'t','she','?']},
    {id:'j2_9_8', explanation:'Where do you live?で居住地を尋ねる。',  japanese:'あなたはどこに住んでいますか。',answer:['Where','do','you','live','?']},
    {id:'j2_9_9', explanation:'How often does he go to the library?で3単現に注意。',  japanese:'彼はどのくらいの頻度で図書館に行きますか。',answer:['How','often','does','he','go','to','the','library','?']},
    {id:'j2_9_10', explanation:'How high is this tree?で高さを尋ねる。', japanese:'この木はどのくらいの高さですか。',answer:['How','high','is','this','tree','?']},
    {id:'j2_9_11', explanation:'She likes tennis, doesn't she?で付加疑問文（3単現→doesn't）。', japanese:'彼女はテニスが好きですよね。',answer:['She','likes','tennis','doesn\'t','she','?']},
    {id:'j2_9_12', explanation:'They are not from here, are they?で付加疑問文（否定→肯定）。', japanese:'彼らはここの出身ではありませんよね。',answer:['They','are','not','from','here','?']},
  ],
  j2_10: [
    {id:'j2_10_1', explanation:'want to＋動詞原形で「～したい」（名詞的用法）。',  japanese:'私は英語を勉強したいです。', answer:['I','want','to','study','English','.']},
    {id:'j2_10_2', explanation:'My dream is to become～で補語にto不定詞。',  japanese:'私の夢は医者になることです。',answer:['My','dream','is','to','become','a','doctor','.']},
    {id:'j2_10_3', explanation:'like listening to～で動名詞（目的語）。',  japanese:'私は音楽を聴くことが好きです。',answer:['I','like','listening','to','music','.']},
    {id:'j2_10_4', explanation:'She likes playing tennis.で動名詞が目的語。',  japanese:'彼女はテニスをすることが好きです。',answer:['She','likes','playing','tennis','.']},
    {id:'j2_10_5', explanation:'He can speak English.でcanは助動詞。',  japanese:'彼は英語を話すことができます。',answer:['He','can','speak','English','.']},
    {id:'j2_10_6', explanation:'I want to go to a bookstore.でwant to go to～の語順。',  japanese:'私は本屋に行きたいです。',   answer:['I','want','to','go','to','a','bookstore','.']},
    {id:'j2_10_7', explanation:'She likes cooking.で動名詞が目的語。',  japanese:'彼女は料理をすることが好きです。',answer:['She','likes','cooking','.']},
    {id:'j2_10_8', explanation:'I want to play soccer.でwant to＋原形。',  japanese:'私はサッカーをしたいです。', answer:['I','want','to','play','soccer','.']},
    {id:'j2_10_9', explanation:'My hobby is reading books.で動名詞が補語。',  japanese:'私の趣味は読書です。',       answer:['My','hobby','is','reading','books','.']},
    {id:'j2_10_10', explanation:'What do you want to do?でwant to doに注意。', japanese:'あなたは何をしたいですか。', answer:['What','do','you','want','to','do','?']},
    {id:'j2_10_11', explanation:'She wants to become a singer.でwantsは3単現。', japanese:'彼女は歌手になりたいです。', answer:['She','wants','to','become','a','singer','.']},
    {id:'j2_10_12', explanation:'I like swimming.で動名詞が目的語。', japanese:'私は水泳をすることが好きです。',answer:['I','like','swimming','.']},
    {id:'j2_10_13', explanation:'He is good at cooking.でbe good at＋動名詞。', japanese:'彼は料理をすることが上手です。',answer:['He','is','good','at','cooking','.']},
  ],
  j2_11: [
    {id:'j2_11_1', explanation:'to study English～で「～するために」（副詞的用法・目的）。',  japanese:'私は英語を勉強するために図書館に行きました。',answer:['I','went','to','the','library','to','study','English','.']},
    {id:'j2_11_2', explanation:'to buy a cake～で「～するために」（目的）。',  japanese:'彼女はケーキを買うためにお店に行きました。',answer:['She','went','to','the','shop','to','buy','a','cake','.']},
    {id:'j2_11_3', explanation:'was sad to hear～で「～して悲しい」（感情の原因）。',  japanese:'私はそのニュースを聞いて悲しかったです。',answer:['I','was','sad','to','hear','the','news','.']},
    {id:'j2_11_4', explanation:'was glad to meet～で「～して嬉しい」（感情の原因）。',  japanese:'彼は友達に会えてうれしかったです。',answer:['He','was','glad','to','meet','his','friend','.']},
    {id:'j2_11_5', explanation:'was surprised to meet～で「～して驚いた」。',  japanese:'彼女はあなたに会えて驚きました。',answer:['She','was','surprised','to','meet','you','.']},
    {id:'j2_11_6', explanation:'got up early to practice the piano.で「練習するために早起き」。',  japanese:'彼はピアノを練習するために早く起きました。',answer:['He','got','up','early','to','practice','the','piano','.']},
    {id:'j2_11_7', explanation:'was glad to meet my friend.で感情の原因。',  japanese:'私は友達に会えてうれしかったです。',answer:['I','was','glad','to','meet','my','friend','.']},
    {id:'j2_11_8', explanation:'was sad to hear the news.で感情の原因。',  japanese:'彼女はそのニュースを聞いて悲しかったです。',answer:['She','was','sad','to','hear','the','news','.']},
    {id:'j2_11_9', explanation:'went to school to study English.で目的を表すto不定詞。',  japanese:'彼らは英語を勉強するために学校に行きました。',answer:['They','went','to','school','to','study','English','.']},
    {id:'j2_11_10', explanation:'went to the theater to see a movie.で目的を表すto不定詞。', japanese:'私は映画を見るために映画館に行きました。',answer:['I','went','to','the','theater','to','see','a','movie','.']},
  ],
  j2_12: [
    {id:'j2_12_1', explanation:'things to do～でto不定詞がthingsを修飾（形容詞的用法）。',  japanese:'私はすることがたくさんあります。',answer:['I','have','a','lot','of','things','to','do','.']},
    {id:'j2_12_2', explanation:'a book to read～でto不定詞がbookを修飾。',  japanese:'彼女は読む本を持っています。',answer:['She','has','a','book','to','read','.']},
    {id:'j2_12_3', explanation:'some water to drink～でto不定詞がwaterを修飾。',  japanese:'私は飲む水がほしいです。',   answer:['I','want','some','water','to','drink','.']},
    {id:'j2_12_4', explanation:'a house to live in～でto不定詞がhouseを修飾。前置詞inを忘れずに。',  japanese:'彼は住む家を必要としています。',answer:['He','needs','a','house','to','live','in','.']},
    {id:'j2_12_5', explanation:'some paper to write on～でto不定詞がpaperを修飾。',  japanese:'私は書く紙がほしいです。',   answer:['I','want','some','paper','to','write','on','.']},
    {id:'j2_12_6', explanation:'He has a lot of things to do.で形容詞的用法。',  japanese:'彼にはすることがたくさんあります。',answer:['He','has','a','lot','of','things','to','do','.']},
    {id:'j2_12_7', explanation:'She doesn't have a book to read.で否定文。',  japanese:'彼女は読む本を持っていません。',answer:['She','doesn\'t','have','a','book','to','read','.']},
    {id:'j2_12_8', explanation:'some paper to write on～でto不定詞が修飾。',  japanese:'私は書く紙がほしいです。',   answer:['I','want','some','paper','to','write','on','.']},
    {id:'j2_12_9', explanation:'a place to live in～でto不定詞が修飾。前置詞inを忘れずに。',  japanese:'彼らは住む場所を探しています。',answer:['They','are','looking','for','a','place','to','live','in','.']},
    {id:'j2_12_10', explanation:'a friend to talk with～でwithを忘れずに。', japanese:'私には話す友達がいます。',   answer:['I','have','a','friend','to','talk','with','.']},
  ],
  j2_13: [
    {id:'j2_13_1', explanation:'like listening to music.でlikingではなくlistening（動名詞）。',  japanese:'私は音楽を聴くことが好きです。',answer:['I','like','listening','to','music','.']},
    {id:'j2_13_2', explanation:'Her hobby is cooking.で動名詞が補語。',  japanese:'彼女の趣味は料理をすることです。',answer:['Her','hobby','is','cooking','.']},
    {id:'j2_13_3', explanation:'He is good at playing baseball.でbe good at＋動名詞。',  japanese:'彼は野球をすることが得意です。',answer:['He','is','good','at','playing','baseball','.']},
    {id:'j2_13_4', explanation:'I don't like singing.で動名詞が目的語。',  japanese:'私は歌うことが好きではありません。',answer:['I','don\'t','like','singing','.']},
    {id:'j2_13_5', explanation:'She stopped swimming.でstop＋動名詞で「～するのをやめる」。',  japanese:'彼女は泳ぐことをやめました。',answer:['She','stopped','swimming','.']},
    {id:'j2_13_6', explanation:'Thank you for calling me.でfor＋動名詞。',  japanese:'ありがとうございました。',   answer:['Thank','you','for','calling','me','.']},
    {id:'j2_13_7', explanation:'He finished doing his homework.でfinish＋動名詞。',  japanese:'彼は宿題を終えました。',     answer:['He','finished','doing','his','homework','.']},
    {id:'j2_13_8', explanation:'She likes reading books.で動名詞が目的語。',  japanese:'彼女は読書が好きです。',     answer:['She','likes','reading','books','.']},
    {id:'j2_13_9', explanation:'My hobby is taking pictures.で動名詞が補語。',  japanese:'私の趣味は写真を撮ることです。',answer:['My','hobby','is','taking','pictures','.']},
    {id:'j2_13_10', explanation:'He is good at swimming.でbe good at＋動名詞。', japanese:'彼は水泳が得意です。',       answer:['He','is','good','at','swimming','.']},
    {id:'j2_13_11', explanation:'She stopped watching TV.でstop＋動名詞。', japanese:'彼女はテレビを見るのをやめました。',answer:['She','stopped','watching','TV','.']},
    {id:'j2_13_12', explanation:'They like listening to music.でlisten to musicに注意。', japanese:'彼らは音楽を聴くことが好きです。',answer:['They','like','listening','to','music','.']},
  ],
  j2_14: [
    {id:'j2_14_1', explanation:'look＋形容詞で「～に見える」（第2文型）。',  japanese:'彼女は幸せそうに見えます。', answer:['She','looks','happy','.']},
    {id:'j2_14_2', explanation:'became a doctor.でbecome＋名詞（第2文型）。',  japanese:'彼は医者になりました。',     answer:['He','became','a','doctor','.']},
    {id:'j2_14_3', explanation:'gave me a book.でgive＋人＋物（第4文型）。',  japanese:'彼女は私に本をくれました。', answer:['She','gave','me','a','book','.']},
    {id:'j2_14_4', explanation:'sent her some flowers.でsend＋人＋物（第4文型）。',  japanese:'私は彼女に花を送りました。', answer:['I','sent','her','some','flowers','.']},
    {id:'j2_14_5', explanation:'call her Emi.でcall＋目的語＋名詞（第5文型）。',  japanese:'彼らは彼女をエミと呼びます。',answer:['They','call','her','Emi','.']},
    {id:'j2_14_6', explanation:'found the cake delicious.でfind＋目的語＋形容詞（第5文型）。',  japanese:'彼はそのケーキをおいしいと思いました。',answer:['He','found','the','cake','delicious','.']},
    {id:'j2_14_7', explanation:'He looks sad.でlook＋形容詞（第2文型）。',  japanese:'彼は悲しそうに見えます。',   answer:['He','looks','sad','.']},
    {id:'j2_14_8', explanation:'She became a teacher.でbecome＋名詞（第2文型）。',  japanese:'彼女は先生になりました。',   answer:['She','became','a','teacher','.']},
    {id:'j2_14_9', explanation:'My father gave me a watch.でgive＋人＋物（第4文型）。',  japanese:'父は私に時計をくれました。', answer:['My','father','gave','me','a','watch','.']},
    {id:'j2_14_10', explanation:'We call him Taro.でcall＋目的語＋名詞（第5文型）。', japanese:'私たちは彼をタロウと呼びます。',answer:['We','call','him','Taro','.']},
    {id:'j2_14_11', explanation:'She found the film interesting.でfind＋目的語＋形容詞（第5文型）。', japanese:'彼女はその映画を面白いと思いました。',answer:['She','found','the','film','interesting','.']},
    {id:'j2_14_12', explanation:'He sent me a letter.でsend＋人＋物（第4文型）。', japanese:'彼は私に手紙を送りました。', answer:['He','sent','me','a','letter','.']},
  ],
  j2_15: [
    {id:'j2_15_1', explanation:'It is important to study～で形式主語構文（本当の主語はto以下）。',  japanese:'英語を勉強することは大切です。',answer:['It','is','important','to','study','English','.']},
    {id:'j2_15_2', explanation:'It is nice to meet her.で形式主語構文。',  japanese:'彼女に会うことはうれしいです。',answer:['It','is','nice','to','meet','her','.']},
    {id:'j2_15_3', explanation:'It is dangerous to swim here.で形式主語構文。',  japanese:'ここで泳ぐことは危険です。', answer:['It','is','dangerous','to','swim','here','.']},
    {id:'j2_15_4', explanation:'I don't know where to go.でwhere to go「どこへ行くべきか」（疑問詞＋to不定詞）。',  japanese:'私はどこへ行けばよいかわかりません。',answer:['I','don\'t','know','where','to','go','.']},
    {id:'j2_15_5', explanation:'She doesn't know when to leave.でwhen to leave「いつ出発すべきか」。',  japanese:'彼女はいつ出発すればよいかわかりません。',answer:['She','doesn\'t','know','when','to','leave','.']},
    {id:'j2_15_6', explanation:'He doesn't know how to study English.でhow to study「どうやって学ぶか」。',  japanese:'彼はどうやって英語を勉強すればよいかわかりません。',answer:['He','doesn\'t','know','how','to','study','English','.']},
    {id:'j2_15_7', explanation:'It is good for your health to exercise every day.でfor～toで「～にとって」。',  japanese:'毎日運動することは健康によいです。',answer:['It','is','good','to','exercise','every','day','for','your','health','.']},
    {id:'j2_15_8', explanation:'Please tell me how to contact her.でhow to contactの語順。',  japanese:'彼女に連絡する方法を教えてください。',answer:['Please','tell','me','how','to','contact','her','.']},
    {id:'j2_15_9', explanation:'I don't know where to buy it.でwhere to buyの語順。',  japanese:'どこで買えばよいかわかりません。',answer:['I','don\'t','know','where','to','buy','it','.']},
    {id:'j2_15_10', explanation:'It is difficult to speak English well.で形式主語構文。', japanese:'英語を上手に話すことは難しいです。',answer:['It','is','difficult','to','speak','English','well','.']},
  ],
  j2_16: [
    {id:'j2_16_1', explanation:'but（しかし）で逆接を表す。',  japanese:'私は英語が好きですが、数学は苦手です。',answer:['I','like','English','but','I','am','not','good','at','math','.']},
    {id:'j2_16_2', explanation:'and（そして）で並列を表す。',  japanese:'彼は歌うことと踊ることが好きです。',answer:['He','likes','singing','and','dancing','.']},
    {id:'j2_16_3', explanation:'When I came home, my mother was cooking.でWhen～のとき。',  japanese:'私が家に帰ったとき、母は料理をしていました。',answer:['When','I','came','home','my','mother','was','cooking','.']},
    {id:'j2_16_4', explanation:'because～で「～なので」（理由）。',  japanese:'彼女は疲れていたので、早く寝ました。',answer:['She','went','to','bed','early','because','she','was','tired','.']},
    {id:'j2_16_5', explanation:'I think he is a teacher.でI think that～「～だと思う」。',  japanese:'私は彼が先生だと思います。',answer:['I','think','he','is','a','teacher','.']},
    {id:'j2_16_6', explanation:'She said that she would come tomorrow.でsaid that～「～と言った」。',  japanese:'彼女はあした来ると言っていました。',answer:['She','said','that','she','would','come','tomorrow','.']},
    {id:'j2_16_7', explanation:'He is busy but always looks happy.でbutで逆接。',  japanese:'彼は忙しいけれど、いつも楽しそうです。',answer:['He','is','busy','but','he','always','looks','happy','.']},
    {id:'j2_16_8', explanation:'She likes English and math.でandで並列。',  japanese:'彼女は英語と数学が好きです。',answer:['She','likes','English','and','math','.']},
    {id:'j2_16_9', explanation:'When he came, I was studying.でWhenで時を表す。',  japanese:'彼が来たとき、私は勉強していました。',answer:['When','he','came','I','was','studying','.']},
    {id:'j2_16_10', explanation:'I think she is correct.でI think that～。', japanese:'私は彼女が正しいと思います。',answer:['I','think','she','is','correct','.']},
    {id:'j2_16_11', explanation:'He stayed home because it rained.でbecauseで理由。', japanese:'彼は雨が降ったので家にいました。',answer:['He','stayed','home','because','it','rained','.']},
  ],
  j2_17: [
    {id:'j2_17_1', explanation:'on the deskで「机の上に」。',  japanese:'本は机の上にあります。',     answer:['The','book','is','on','the','desk','.']},
    {id:'j2_17_2', explanation:'in the boxで「箱の中に」。',  japanese:'鉛筆は箱の中にあります。',   answer:['The','pencil','is','in','the','box','.']},
    {id:'j2_17_3', explanation:'in the morningで「朝に」。',  japanese:'彼は朝に英語を勉強します。', answer:['He','studies','English','in','the','morning','.']},
    {id:'j2_17_4', explanation:'on Mondayで「月曜日に」。',  japanese:'私は月曜日にテニスをします。',answer:['I','play','tennis','on','Monday','.']},
    {id:'j2_17_5', explanation:'at sevenで「7時に」。',  japanese:'彼女は7時に起きます。',      answer:['She','gets','up','at','seven','.']},
    {id:'j2_17_6', explanation:'in front of the stationで「駅の前に」。',  japanese:'図書館は駅の前にあります。', answer:['The','library','is','in','front','of','the','station','.']},
    {id:'j2_17_7', explanation:'under the sofaで「ソファの下に」。',  japanese:'ネコはソファの下にいます。', answer:['The','cat','is','under','the','sofa','.']},
    {id:'j2_17_8', explanation:'at nightで「夜に」。',  japanese:'彼は夜に音楽を聴きます。',   answer:['He','listens','to','music','at','night','.']},
    {id:'j2_17_9', explanation:'on the deskで「机の上に」。',  japanese:'花は机の上にあります。',     answer:['The','flowers','are','on','the','desk','.']},
    {id:'j2_17_10', explanation:'on every Saturdayで「毎週土曜日に」。', japanese:'彼女は毎週土曜日にサッカーをします。',answer:['She','plays','soccer','on','every','Saturday','.']},
  ],
  j2_18: [
    {id:'j2_18_1', explanation:'tall→tallerと-erをつけて比較級（than～で比較）。',  japanese:'私はボブより若いです。',     answer:['I','am','younger','than','Bob','.']},
    {id:'j2_18_2', explanation:'fast→fasterと-erをつけて比較級。',  japanese:'メアリーは久美より速く走ります。',answer:['Mary','runs','faster','than','Kumi','.']},
    {id:'j2_18_3', explanation:'large→largerと-erをつけて比較級（最後のeをとる）。',  japanese:'カナダは中国より広いです。', answer:['Canada','is','larger','than','China','.']},
    {id:'j2_18_4', explanation:'early→earlier（y→ier）と比較級。',  japanese:'私の母は父より早く起きます。',answer:['My','mother','gets','up','earlier','than','my','father','.']},
    {id:'j2_18_5', explanation:'big→bigger（子音字を重ねてer）と比較級。',  japanese:'私の犬はこの犬より大きいです。',answer:['My','dog','is','bigger','than','this','one','.']},
    {id:'j2_18_6', explanation:'good→betterと不規則変化の比較級。',  japanese:'このコンピュータは私のよりよいです。',answer:['This','computer','is','better','than','mine','.']},
    {id:'j2_18_7', explanation:'old→oldest（-estで最上級）。the oldestでtheをつける。',  japanese:'私たちの学校は市内でいちばん古いです。',answer:['Our','school','is','the','oldest','in','our','city','.']},
    {id:'j2_18_8', explanation:'high→highest（-estで最上級）。the highestでtheをつける。',  japanese:'富士山は日本でいちばん高い。',answer:['Mt.','Fuji','is','the','highest','in','Japan','.']},
    {id:'j2_18_9', explanation:'large→largest（-estで最上級）。the largestでtheをつける。',  japanese:'あの公園はこの町でいちばん広い。',answer:['That','park','is','the','largest','in','this','town','.']},
    {id:'j2_18_10', explanation:'early→earliest（y→iest）と最上級。the earliestでtheをつける。', japanese:'健は私たち全員の中でいちばん早く起きます。',answer:['Ken','gets','up','the','earliest','of','all','us','.']},
    {id:'j2_18_11', explanation:'tall→tallerと-erをつけて比較級。', japanese:'彼は私より背が高いです。',   answer:['He','is','taller','than','me','.']},
    {id:'j2_18_12', explanation:'good→betterと不規則変化の比較級。', japanese:'彼女は彼よりじょうずに歌います。',answer:['She','sings','better','than','him','.']},
    {id:'j2_18_13', explanation:'interesting→more interestingと-erではなくmore～で比較級。', japanese:'この本はあの本よりも面白いです。',answer:['This','book','is','more','interesting','than','that','one','.']},
    {id:'j2_18_14', explanation:'big→biggest（子音字を重ねてest）と最上級。', japanese:'このりんごは3つの中でいちばん大きいです。',answer:['This','apple','is','the','biggest','of','the','three','.']},
    {id:'j2_18_15', explanation:'fast→fastest（-estで最上級）。the fastestでtheをつける。', japanese:'彼は私の学校でいちばん速く走れます。',answer:['He','runs','the','fastest','in','my','school','.']},
  ],
  j2_19: [
    {id:'j2_19_1', explanation:'as old as～でasを2つ使う同等比較。',  japanese:'由美はマイクと同年です。',   answer:['Yumi','is','as','old','as','Mike','.']},
    {id:'j2_19_2', explanation:'not as busy as～で否定の同等比較。「～ほど…でない」。',  japanese:'私はあなたほど忙しくありません。',answer:['I\'m','not','as','busy','as','you','.']},
    {id:'j2_19_3', explanation:'twice as many books as Tom.でtwice as many～as「2倍の数」。',  japanese:'私はトムの２倍の数の本を持っています。',answer:['I','have','twice','as','many','books','as','Tom','.']},
    {id:'j2_19_4', explanation:'as interesting as～でasを2つ使う。',  japanese:'この映画はあの映画と同じくらいおもしろいです。',answer:['This','film','is','as','interesting','as','that','one','.']},
    {id:'j2_19_5', explanation:'can't run as fast as me.でnot as～as「～ほど…でない」。',  japanese:'彼は私ほど速く走れません。', answer:['He','can\'t','run','as','fast','as','me','.']},
    {id:'j2_19_6', explanation:'She sings as well as him.でas well as「同じくらいじょうずに」。',  japanese:'彼女は彼と同じくらいじょうずに歌います。',answer:['She','sings','as','well','as','him','.']},
    {id:'j2_19_7', explanation:'not as interesting as～で否定の同等比較。',  japanese:'この本はあの本ほどおもしろくありません。',answer:['This','book','is','not','as','interesting','as','that','one','.']},
    {id:'j2_19_8', explanation:'He runs twice as fast as I.でtwice as fast as「2倍の速さ」。',  japanese:'彼は私の２倍の速さで走ります。',answer:['He','runs','twice','as','fast','as','I','.']},
  ],
  j2_20: [
    {id:'j2_20_1', explanation:'Which do you like better, A or B?で2つを比較する疑問文。',  japanese:'あなたはサッカーと野球ではどちらが好きですか。',answer:['Which','do','you','like','better','soccer','or','baseball','?']},
    {id:'j2_20_2', explanation:'Which are you better at, A or B?の語順。',  japanese:'あなたは英語と数学ではどちらが得意ですか。',answer:['Which','are','you','better','at','English','or','math','?']},
    {id:'j2_20_3', explanation:'He is the most tall of us.でthe most～で最上級（長い形容詞）。',  japanese:'彼は私たちの中でいちばん背が高いです。',answer:['He','is','the','most','tall','of','us','.']},
    {id:'j2_20_4', explanation:'Yumi is as old as Mike.でas old asで同等比較。',  japanese:'由美はマイクと同年です。',   answer:['Yumi','is','as','old','as','Mike','.']},
    {id:'j2_20_5', explanation:'I'm not as busy as you.でnot as busyで否定の同等比較。',  japanese:'私はあなたほど忙しくありません。',answer:['I\'m','not','as','busy','as','you','.']},
    {id:'j2_20_6', explanation:'Which film is more interesting?でmore～で比較級（長い形容詞）。',  japanese:'どちらの映画がおもしろいですか。',answer:['Which','film','is','more','interesting','?']},
    {id:'j2_20_7', explanation:'She cooks the best in her family.でwell→bestと不規則最上級。',  japanese:'彼女は家族の中でいちばん料理が上手です。',answer:['She','cooks','the','best','in','her','family','.']},
    {id:'j2_20_8', explanation:'This problem is the most difficult in math.でthe most～で最上級。',  japanese:'この問題は数学でいちばん難しいです。',answer:['This','problem','is','the','most','difficult','in','math','.']},
  ],
  j2_21: [
    {id:'j2_21_1', explanation:'is read by many children.でbe動詞＋過去分詞で受け身。by～で「～によって」。',  japanese:'この本は多くの子どもたちに読まれています。',answer:['This','book','is','read','by','many','children','.']},
    {id:'j2_21_2', explanation:'English is spoken in America.でis spoken「話されている」。',  japanese:'英語はアメリカで話されています。',answer:['English','is','spoken','in','America','.']},
    {id:'j2_21_3', explanation:'is sung all over the world.でis sung「歌われている」。',  japanese:'この歌は世界中で歌われています。',answer:['This','song','is','sung','all','over','the','world','.']},
    {id:'j2_21_4', explanation:'was taken by Tom.でwasを使った過去の受け身。',  japanese:'この写真はトムによって撮られました。',answer:['This','photo','was','taken','by','Tom','.']},
    {id:'j2_21_5', explanation:'is made of wood.でbe made of～「～で作られている」（材料が見える）。',  japanese:'この箱は木で作られています。',answer:['This','box','is','made','of','wood','.']},
    {id:'j2_21_6', explanation:'was built 100 years ago.で過去の受け身。',  japanese:'この建物は１００年前に建てられました。',answer:['This','building','was','built','100','years','ago','.']},
    {id:'j2_21_7', explanation:'was written by Ken.でwrite→writtenと過去分詞。',  japanese:'この本はケンによって書かれました。',answer:['This','book','was','written','by','Ken','.']},
    {id:'j2_21_8', explanation:'Japanese is spoken here.でis spoken「話されている」。',  japanese:'日本語はここで話されています。',answer:['Japanese','is','spoken','here','.']},
    {id:'j2_21_9', explanation:'is loved by many people.でlove→lovedと過去分詞。',  japanese:'この歌は多くの人々に愛されています。',answer:['This','song','is','loved','by','many','people','.']},
    {id:'j2_21_10', explanation:'was built 50 years ago.で過去の受け身。', japanese:'この建物は50年前に建てられました。',answer:['This','building','was','built','50','years','ago','.']},
    {id:'j2_21_11', explanation:'was taken by my father.でtake→takenと過去分詞。', japanese:'この写真は私の父によって撮られました。',answer:['This','photo','was','taken','by','my','father','.']},
  ],
  j2_22: [
    {id:'j2_22_1', explanation:'is cleaned every day.でclean→cleanedと受け身。',  japanese:'この部屋は毎日掃除されます。',answer:['This','room','is','cleaned','every','day','.']},
    {id:'j2_22_2', explanation:'are not used by him.で否定の受け身。',  japanese:'これらの機械は彼によって使われていません。',answer:['These','machines','are','not','used','by','him','.']},
    {id:'j2_22_3', explanation:'Where is this book sold?で受け身の疑問文。sell→soldと過去分詞。',  japanese:'この本はどこで売られていますか。',answer:['Where','is','this','book','sold','?']},
    {id:'j2_22_4', explanation:'When was this photo taken?で過去受け身の疑問文。',  japanese:'この写真はいつ撮られましたか。',answer:['When','was','this','photo','taken','?']},
    {id:'j2_22_5', explanation:'was surprised at the news.でbe surprised at「～に驚く」（慣用表現）。',  japanese:'その知らせにだれもが驚きました。',answer:['Everyone','was','surprised','at','the','news','.']},
    {id:'j2_22_6', explanation:'How many cars were sold last year?で受け身の疑問文。',  japanese:'昨年は何台の車が売れましたか。',answer:['How','many','cars','were','sold','last','year','?']},
    {id:'j2_22_7', explanation:'This desk is made of wood.でbe made of～「～で作られている」。',  japanese:'この机は木で作られています。',answer:['This','desk','is','made','of','wood','.']},
    {id:'j2_22_8', explanation:'Is this room cleaned neatly?で受け身の疑問文。',  japanese:'この部屋はきれいに掃除されましたか。',answer:['Is','this','room','cleaned','neatly','?']},
    {id:'j2_22_9', explanation:'Who is this window broken by?でby whomで「だれによって」。',  japanese:'この窓はだれによって割られましたか。',answer:['Who','is','this','window','broken','by','?']},
    {id:'j2_22_10', explanation:'This book is read in many countries.でread→readと過去分詞（同形）。', japanese:'この本は多くの国で読まれています。',answer:['This','book','is','read','in','many','countries','.']},
    {id:'j2_22_11', explanation:'was destroyed by the earthquake.でdestroy→destroyedと受け身。', japanese:'その建物は地震で壊されました。',answer:['The','building','was','destroyed','by','the','earthquake','.']},
  ],
}
