// 中学1年 全問題データ
export const QUESTIONS_J1 = {
  j1_1: [
    {id:'j1_1_1',  japanese:'私は鈴木健です。',            answer:['I','am','Ken','Suzuki','.']},
    {id:'j1_1_2',  japanese:'私は学生です。',              answer:['I','am','a','student','.']},
    {id:'j1_1_3',  japanese:'私は千葉出身です。',          answer:['I','am','from','Chiba','.']},
    {id:'j1_1_4',  japanese:'あなたは佐藤彩です。',        answer:['You','are','Aya','Sato','.']},
    {id:'j1_1_5',  japanese:'あなたは大阪出身です。',      answer:['You','are','from','Osaka','.']},
    {id:'j1_1_6',  japanese:'あなたは先生です。',          answer:['You','are','a','teacher','.']},
    {id:'j1_1_7',  japanese:'私はタカシではありません。',  answer:['I','am','not','Takashi','.']},
    {id:'j1_1_8',  japanese:'私は東京出身ではありません。',answer:['I','am','not','from','Tokyo','.']},
    {id:'j1_1_9',  japanese:'あなたは中井さんではありません。',answer:['You','are','not','Ms.','Nakai','.']},
    {id:'j1_1_10', japanese:'あなたは先生ではありません。',answer:['You','are','not','a','teacher','.']},
    {id:'j1_1_11', japanese:'あなたは木村さんですか。',    answer:['Are','you','Mr.','Kimura','?']},
    {id:'j1_1_12', japanese:'あなたは奈良出身ですか。',    answer:['Are','you','from','Nara','?']},
    {id:'j1_1_13', japanese:'あなたは学生ですか。',        answer:['Are','you','a','student','?']},
    {id:'j1_1_14', japanese:'私は吉田久美です。',          answer:['I','am','Kumi','Yoshida','.']},
    {id:'j1_1_15', japanese:'私は北海道出身です。',        answer:['I','am','from','Hokkaido','.']},
    {id:'j1_1_16', japanese:'私はサッカー選手です。',      answer:['I','am','a','soccer','player','.']},
    {id:'j1_1_17', japanese:'私は中国出身です。',          answer:['I','am','from','China','.']},
    {id:'j1_1_18', japanese:'あなたはスミスさんです。',    answer:['You','are','Ms.','Smith','.']},
    {id:'j1_1_19', japanese:'あなたはカナダ出身です。',    answer:['You','are','from','Canada','.']},
    {id:'j1_1_20', japanese:'あなたは野球ファンです。',    answer:['You','are','a','baseball','fan','.']},
    {id:'j1_1_21', japanese:'あなたは横浜出身です。',      answer:['You','are','from','Yokohama','.']},
    {id:'j1_1_22', japanese:'あなたは野球選手ですか。',    answer:['Are','you','a','baseball','player','?']},
    {id:'j1_1_23', japanese:'あなたは日本出身ですか。',    answer:['Are','you','from','Japan','?']},
    {id:'j1_1_24', japanese:'あなたは村井さんですか。',    answer:['Are','you','Mr.','Murai','?']},
    {id:'j1_1_25', japanese:'あなたはナンシーですか。',    answer:['Are','you','Nancy','?']},
    {id:'j1_1_26', japanese:'あなたは名古屋出身ですか。',  answer:['Are','you','from','Nagoya','?']},
    {id:'j1_1_27', japanese:'あなたは先生ですか。',        answer:['Are','you','a','teacher','?']},
    {id:'j1_1_28', japanese:'私はエミではありません。',    answer:['I','am','not','Emi','.']},
    {id:'j1_1_29', japanese:'私はお医者さんではありません。',answer:['I','am','not','a','doctor','.']},
    {id:'j1_1_30', japanese:'あなたはテニスの選手です。',  answer:['You','are','a','tennis','player','.']},
    {id:'j1_1_31', japanese:'私はカナダ出身ではありません。',answer:['I','am','not','from','Canada','.']},
    {id:'j1_1_32', japanese:'あなたはサッカーファンですか。',answer:['Are','you','a','soccer','fan','?']},
    {id:'j1_1_33', japanese:'私は京都出身です。',          answer:['I','am','from','Kyoto','.']},
    {id:'j1_1_34', japanese:'あなたはトムではありません。',answer:['You','are','not','Tom','.']},
    {id:'j1_1_35', japanese:'あなたは先生ですか。',        answer:['Are','you','a','teacher','?']},
    {id:'j1_1_36', japanese:'私は英香です。',              answer:['I','am','Mika','.']},
    {id:'j1_1_37', japanese:'あなたは中学生です。',        answer:['You','are','a','junior','high','school','student','.']},
    {id:'j1_1_38', japanese:'あなたは医者ではありません。',answer:['You','are','not','a','doctor','.']},
    {id:'j1_1_39', japanese:'あなたはテニスの選手ですか。',answer:['Are','you','a','tennis','player','?']},
    {id:'j1_1_40', japanese:'あなたはアニメファンですか。',answer:['Are','you','a','anime','fan','?']},
  ],
  j1_2: [
    {id:'j1_2_1',  japanese:'これは本です。',              answer:['This','is','a','book','.']},
    {id:'j1_2_2',  japanese:'あれは学校です。',            answer:['That','is','a','school','.']},
    {id:'j1_2_3',  japanese:'これはペンではありません。',  answer:['This','is','not','a','pen','.']},
    {id:'j1_2_4',  japanese:'あれは公園ではありません。',  answer:['That','is','not','a','park','.']},
    {id:'j1_2_5',  japanese:'これは何ですか。',            answer:['What','is','this','?']},
    {id:'j1_2_6',  japanese:'あれは何ですか。',            answer:['What','is','that','?']},
    {id:'j1_2_7',  japanese:'これはあなたの本ですか。',    answer:['Is','this','your','book','?']},
    {id:'j1_2_8',  japanese:'あれはあなたの自転車ですか。',answer:['Is','that','your','bike','?']},
    {id:'j1_2_9',  japanese:'これは私のかばんです。',      answer:['This','is','my','bag','.']},
    {id:'j1_2_10', japanese:'あれはケンの自転車です。',    answer:['That','is','Ken\'s','bike','.']},
    {id:'j1_2_11', japanese:'これは新しい辞書です。',      answer:['This','is','a','new','dictionary','.']},
    {id:'j1_2_12', japanese:'あれは古い建物です。',        answer:['That','is','an','old','building','.']},
    {id:'j1_2_13', japanese:'これはあなたの本ではありません。',answer:['This','is','not','your','book','.']},
    {id:'j1_2_14', japanese:'あれはエミの自転車ではありません。',answer:['That','is','not','Emi\'s','bike','.']},
    {id:'j1_2_15', japanese:'これは何ですか。これは鳥です。',answer:['What','is','this','?','It\'s','a','bird','.']},
    {id:'j1_2_16', japanese:'あれは何ですか。あれは橋です。',answer:['What','is','that','?','It\'s','a','bridge','.']},
    {id:'j1_2_17', japanese:'これはあなたのペンですか。',  answer:['Is','this','your','pen','?']},
    {id:'j1_2_18', japanese:'あれは動物園ですか。',        answer:['Is','that','a','zoo','?']},
  ],
  j1_3: [
    {id:'j1_3_1',  japanese:'これは何ですか。',            answer:['What','is','this','?']},
    {id:'j1_3_2',  japanese:'あれは何ですか。',            answer:['What','is','that','?']},
    {id:'j1_3_3',  japanese:'これはペンですか、それとも鉛筆ですか。',answer:['Is','this','a','pen','or','a','pencil','?']},
    {id:'j1_3_4',  japanese:'これはネコですか、それともイヌですか。',answer:['Is','this','a','cat','or','a','dog','?']},
    {id:'j1_3_5',  japanese:'これは何ですか。椅子です。',  answer:['What','is','this','?','It\'s','a','chair','.']},
    {id:'j1_3_6',  japanese:'あれは何ですか。テーブルです。',answer:['What','is','that','?','It\'s','a','table','.']},
    {id:'j1_3_7',  japanese:'これはボールですか、バットですか。',answer:['Is','this','a','ball','or','a','bat','?']},
    {id:'j1_3_8',  japanese:'これはりんごですか、みかんですか。',answer:['Is','this','an','apple','or','an','orange','?']},
    {id:'j1_3_9',  japanese:'これはあなたのかばんですか。',answer:['Is','this','your','bag','?']},
    {id:'j1_3_10', japanese:'あれは図書館ですか。',        answer:['Is','that','a','library','?']},
    {id:'j1_3_11', japanese:'これは何ですか。',            answer:['What','is','this','?']},
    {id:'j1_3_12', japanese:'あれは何ですか。',            answer:['What','is','that','?']},
  ],
  j1_4: [
    {id:'j1_4_1',  japanese:'私は新しいかばんを持っています。',answer:['I','have','a','new','bag','.']},
    {id:'j1_4_2',  japanese:'これは古い自転車です。',      answer:['This','is','a','old','bicycle','.']},
    {id:'j1_4_3',  japanese:'あれは大きい犬です。',        answer:['That','is','a','big','dog','.']},
    {id:'j1_4_4',  japanese:'私は赤いペンを持っています。',answer:['I','have','a','red','pen','.']},
    {id:'j1_4_5',  japanese:'これはおいしいケーキです。',  answer:['This','is','a','delicious','cake','.']},
    {id:'j1_4_6',  japanese:'あれは美しい花です。',        answer:['That','is','a','beautiful','flower','.']},
    {id:'j1_4_7',  japanese:'これは面白い本です。',        answer:['This','is','a','interesting','book','.']},
    {id:'j1_4_8',  japanese:'あれは小さいネコです。',      answer:['That','is','a','small','cat','.']},
    {id:'j1_4_9',  japanese:'私は長い鉛筆を持っています。',answer:['I','have','a','long','pencil','.']},
    {id:'j1_4_10', japanese:'これは難しい問題です。',      answer:['This','is','a','difficult','problem','.']},
    {id:'j1_4_11', japanese:'あれは有名な公園です。',      answer:['That','is','a','famous','park','.']},
    {id:'j1_4_12', japanese:'私は白いTシャツを持っています。',answer:['I','have','a','white','T-shirt','.']},
  ],
  j1_5: [
    {id:'j1_5_1',  japanese:'彼はトムです。',              answer:['He','is','Tom','.']},
    {id:'j1_5_2',  japanese:'彼女は先生です。',            answer:['She','is','a','teacher','.']},
    {id:'j1_5_3',  japanese:'彼は医者ではありません。',    answer:['He','is','not','a','doctor','.']},
    {id:'j1_5_4',  japanese:'彼女はここの出身ではありません。',answer:['She','is','not','from','here','.']},
    {id:'j1_5_5',  japanese:'彼はだれですか。',            answer:['Who','is','He','?']},
    {id:'j1_5_6',  japanese:'彼女はだれですか。',          answer:['Who','is','She','?']},
    {id:'j1_5_7',  japanese:'彼はあなたの兄ですか。',      answer:['Is','He','your','brother','?']},
    {id:'j1_5_8',  japanese:'彼女はあなたのお母さんですか。',answer:['Is','she','your','mother','?']},
    {id:'j1_5_9',  japanese:'彼は私の友達です。',          answer:['He','is','my','friend','.']},
    {id:'j1_5_10', japanese:'彼女は有名な歌手です。',      answer:['She','is','a','famous','singer','.']},
    {id:'j1_5_11', japanese:'彼は野球選手ではありません。',answer:['He','is','not','a','baseball','player','.']},
    {id:'j1_5_12', japanese:'彼女は学生ではありません。',  answer:['She','is','not','a','student','.']},
    {id:'j1_5_13', japanese:'あの男性はだれですか。',      answer:['Who','is','that','man','?']},
    {id:'j1_5_14', japanese:'あの女性はだれですか。',      answer:['Who','is','that','woman','?']},
    {id:'j1_5_15', japanese:'彼はあなたのお父さんですか。',answer:['Is','He','your','father','?']},
    {id:'j1_5_16', japanese:'彼女はあなたの姉ですか。',    answer:['Is','she','your','sister','?']},
  ],
  j1_6: [
    {id:'j1_6_1',  japanese:'私はコンピュータを持っています。',answer:['I','have','a','computer','.']},
    {id:'j1_6_2',  japanese:'私はピアノを弾きます。',      answer:['I','play','the','piano','.']},
    {id:'j1_6_3',  japanese:'あなたは音楽が好きです。',    answer:['You','like','music','.']},
    {id:'j1_6_4',  japanese:'あなたは英語を勉強します。',  answer:['You','study','English','.']},
    {id:'j1_6_5',  japanese:'私はこの本を読みます。',      answer:['I','read','this','book','.']},
    {id:'j1_6_6',  japanese:'私はギターをじょうずに弾きます。',answer:['I','play','the','guitar','well','.']},
    {id:'j1_6_7',  japanese:'私はしばしばこの本を読みます。',answer:['I','often','read','this','book','.']},
    {id:'j1_6_8',  japanese:'あなたは速く走ります。',      answer:['You','run','fast','.']},
    {id:'j1_6_9',  japanese:'私はバスケットボールをしません。',answer:['I','do','not','play','basketball','.']},
    {id:'j1_6_10', japanese:'私はイヌを飼っていません。',  answer:['I','do','not','have','a','dog','.']},
    {id:'j1_6_11', japanese:'あなたはカメラを持っていますか。',answer:['Do','you','have','a','camera','?']},
    {id:'j1_6_12', japanese:'あなたは数学が好きですか。',  answer:['Do','you','like','math','?']},
    {id:'j1_6_13', japanese:'あなたは野球をしますか。',    answer:['Do','you','play','baseball','?']},
    {id:'j1_6_14', japanese:'私は自転車を持っています。',  answer:['I','have','a','bike','.']},
    {id:'j1_6_15', japanese:'あなたはサッカーが好きです。',answer:['You','like','soccer','.']},
    {id:'j1_6_16', japanese:'私はテニスをしません。',      answer:['I','do','not','play','tennis','.']},
    {id:'j1_6_17', japanese:'あなたは英語を話しますか。',  answer:['Do','you','speak','English','?']},
    {id:'j1_6_18', japanese:'私は毎日音楽を聴きます。',    answer:['I','listen','to','music','every','day','.']},
    {id:'j1_6_19', japanese:'あなたは何が好きですか。',    answer:['What','do','you','like','?']},
    {id:'j1_6_20', japanese:'あなたはオレンジを持っていますか。',answer:['Do','you','have','an','orange','?']},
    {id:'j1_6_21', japanese:'あなたは英語を勉強しますか。',answer:['Do','you','study','English','?']},
    {id:'j1_6_22', japanese:'私はギターをじょうずに弾きます。',answer:['I','play','the','guitar','well','.']},
    {id:'j1_6_23', japanese:'あなたは何が好きですか。',    answer:['What','do','you','like','?']},
    {id:'j1_6_24', japanese:'あなたは音楽が好きですか。',  answer:['Do','you','like','music','?']},
    {id:'j1_6_25', japanese:'私はバスケットボールをしません。',answer:['I','do','not','play','basketball','.']},
  ],
  j1_7: [
    {id:'j1_7_1',  japanese:'私は本を３冊持っています。',  answer:['I','have','three','books','.']},
    {id:'j1_7_2',  japanese:'私は鉛筆を５本持っています。',answer:['I','have','five','pencils','.']},
    {id:'j1_7_3',  japanese:'私はイヌを２匹飼っています。',answer:['I','have','two','dogs','.']},
    {id:'j1_7_4',  japanese:'机の上に箱が４つあります。',  answer:['There','are','four','boxes','on','the','desks','.']},
    {id:'j1_7_5',  japanese:'あなたはオレンジを持っていますか。',answer:['Do','you','have','any','oranges','?']},
    {id:'j1_7_6',  japanese:'私はリンゴをいくつか持っています。',answer:['I','have','some','apples','.']},
    {id:'j1_7_7',  japanese:'私は花を10本持っています。',  answer:['I','have','ten','flowers','.']},
    {id:'j1_7_8',  japanese:'ここに椅子が３つあります。',  answer:['There','are','three','chairs','here','.']},
    {id:'j1_7_9',  japanese:'あなたは本を何冊持っていますか。',answer:['How','many','books','do','you','have','?']},
    {id:'j1_7_10', japanese:'私はノートを６冊持っています。',answer:['I','have','six','notebooks','.']},
    {id:'j1_7_11', japanese:'机の上に消しゴムが２つあります。',answer:['There','are','two','erasers','on','the','desk','.']},
    {id:'j1_7_12', japanese:'あなたは何本のペンを持っていますか。',answer:['How','many','pens','do','you','have','?']},
  ],
  j1_8: [
    {id:'j1_8_1',  japanese:'私たちは学生です。',          answer:['We','are','students','.']},
    {id:'j1_8_2',  japanese:'あなたたちは友達です。',      answer:['You','are','friends','.']},
    {id:'j1_8_3',  japanese:'彼らは先生です。',            answer:['They','are','teachers','.']},
    {id:'j1_8_4',  japanese:'私たちは学生ではありません。',answer:['We','are','not','students','.']},
    {id:'j1_8_5',  japanese:'彼らは医者ではありません。',  answer:['They','are','not','doctors','.']},
    {id:'j1_8_6',  japanese:'あなたたちは友達ですか。',    answer:['Are','you','friends','?']},
    {id:'j1_8_7',  japanese:'彼らは先生ですか。',          answer:['Are','they','teachers','?']},
    {id:'j1_8_8',  japanese:'私たちは野球ファンです。',    answer:['We','are','baseball','fans','.']},
    {id:'j1_8_9',  japanese:'彼らはサッカー選手です。',    answer:['They','are','soccer','players','.']},
    {id:'j1_8_10', japanese:'私たちは音楽ファンではありません。',answer:['We','are','not','music','fans','.']},
    {id:'j1_8_11', japanese:'彼らはここの出身ではありません。',answer:['They','are','not','from','here','.']},
    {id:'j1_8_12', japanese:'あなたたちは音楽が好きですか。',answer:['Are','you','music','fans','?']},
    {id:'j1_8_13', japanese:'彼らはオーストラリア出身ですか。',answer:['Are','they','from','Australia','?']},
    {id:'j1_8_14', japanese:'私たちはクラスメートです。',  answer:['We','are','classmates','.']},
    {id:'j1_8_15', japanese:'彼女たちは有名な歌手です。',  answer:['They','are','famous','singers','.']},
  ],
  j1_9: [
    {id:'j1_9_1',  japanese:'あなたはどこの出身ですか。',  answer:['Where','are','you','from','?']},
    {id:'j1_9_2',  japanese:'あなたはどこに住んでいますか。',answer:['Where','do','you','live','?']},
    {id:'j1_9_3',  japanese:'あなたはいつ勉強しますか。',  answer:['When','do','you','study','?']},
    {id:'j1_9_4',  japanese:'あなたはいつ起きますか。',    answer:['When','do','you','get','up','?']},
    {id:'j1_9_5',  japanese:'あなたはどんな音楽が好きですか。',answer:['What','music','do','you','like','?']},
    {id:'j1_9_6',  japanese:'あなたはどんなスポーツをしますか。',answer:['What','sport','do','you','play','?']},
    {id:'j1_9_7',  japanese:'あなたはどこでテニスをしますか。',answer:['Where','do','you','play','tennis','?']},
    {id:'j1_9_8',  japanese:'あなたはいつ英語を勉強しますか。',answer:['When','do','you','study','English','?']},
    {id:'j1_9_9',  japanese:'あなたはどんな本を読みますか。',answer:['What','book','do','you','read','?']},
    {id:'j1_9_10', japanese:'あなたはどこで音楽を聴きますか。',answer:['Where','do','you','listen','to','music','?']},
    {id:'j1_9_11', japanese:'あなたはいつピアノを練習しますか。',answer:['When','do','you','practice','the','piano','?']},
    {id:'j1_9_12', japanese:'あなたはどんな食べ物が好きですか。',answer:['What','food','do','you','like','?']},
    {id:'j1_9_13', japanese:'あなたはどこで野球をしますか。',answer:['Where','do','you','play','baseball','?']},
  ],
  j1_10: [
    {id:'j1_10_1',  japanese:'私は英語を話すことができます。',answer:['I','can','speak','English','.']},
    {id:'j1_10_2',  japanese:'彼はギターを弾くことができます。',answer:['He','can','play','the','guitar','.']},
    {id:'j1_10_3',  japanese:'私は速く走ることができません。',answer:['I','can','not','run','fast','.']},
    {id:'j1_10_4',  japanese:'彼女はピアノを弾くことができません。',answer:['She','can','not','play','the','piano','.']},
    {id:'j1_10_5',  japanese:'あなたは泳ぐことができますか。',answer:['Can','you','swim','?']},
    {id:'j1_10_6',  japanese:'彼は料理ができますか。',     answer:['Can','he','cook','?']},
    {id:'j1_10_7',  japanese:'何ができますか。',           answer:['What','can','you','do','?']},
    {id:'j1_10_8',  japanese:'私は自転車に乗ることができます。',answer:['I','can','ride','a','bike','.']},
    {id:'j1_10_9',  japanese:'彼女は上手に歌うことができます。',answer:['She','can','sing','well','.']},
    {id:'j1_10_10', japanese:'私はスキーができません。',   answer:['I','can','not','ski','.']},
    {id:'j1_10_11', japanese:'彼は漢字を書くことができません。',answer:['He','can','not','write','kanji','.']},
    {id:'j1_10_12', japanese:'あなたはギターを弾けますか。',answer:['Can','you','play','the','guitar','?']},
    {id:'j1_10_13', japanese:'彼女は日本語を話せますか。', answer:['Can','she','speak','Japanese','?']},
    {id:'j1_10_14', japanese:'あなたは何ができますか。',   answer:['What','can','you','do','?']},
    {id:'j1_10_15', japanese:'彼は速く走ることができます。',answer:['He','can','run','fast','.']},
    {id:'j1_10_16', japanese:'私は英語を話すことができます。',answer:['I','can','speak','English','.']},
    {id:'j1_10_17', japanese:'彼女はピアノを上手に弾くことができます。',answer:['She','can','play','the','piano','well','.']},
    {id:'j1_10_18', japanese:'あなたは水泳ができますか。', answer:['Can','you','swim','?']},
    {id:'j1_10_19', japanese:'彼は料理をすることができません。',answer:['He','can','not','cook','.']},
  ],
  j1_11: [
    {id:'j1_11_1',  japanese:'これは私の本です。',         answer:['This','is','my','book','.']},
    {id:'j1_11_2',  japanese:'あれはあなたの自転車ですか。',answer:['Is','that','your','bike','?']},
    {id:'j1_11_3',  japanese:'彼の名前はトムです。',       answer:['His','name','is','Tom','.']},
    {id:'j1_11_4',  japanese:'彼女のお母さんは先生です。', answer:['Her','mother','is','a','teacher','.']},
    {id:'j1_11_5',  japanese:'私たちの学校は大きいです。', answer:['Our','school','is','big','.']},
    {id:'j1_11_6',  japanese:'私は彼を知っています。',     answer:['I','know','him','.']},
    {id:'j1_11_7',  japanese:'あなたは彼女が好きですか。', answer:['Do','you','like','her','?']},
    {id:'j1_11_8',  japanese:'これは私たちの教室です。',   answer:['This','is','Our','classroom','.']},
    {id:'j1_11_9',  japanese:'あれは彼らの学校ですか。',   answer:['Is','that','their','school','?']},
    {id:'j1_11_10', japanese:'私はあなたを愛しています。', answer:['I','love','you','.']},
    {id:'j1_11_11', japanese:'彼女は彼を知っています。',   answer:['She','knows','him','.']},
    {id:'j1_11_12', japanese:'私たちは彼女を手伝います。', answer:['We','help','her','.']},
    {id:'j1_11_13', japanese:'私の兄の名前はケンです。',   answer:['My','brother\'s','name','is','Ken','.']},
    {id:'j1_11_14', japanese:'あなたの先生の名前は何ですか。',answer:['What','is','your','teacher\'s','name','?']},
  ],
  j1_12: [
    {id:'j1_12_1',  japanese:'彼は英語を話します。',       answer:['He','speaks','English','.']},
    {id:'j1_12_2',  japanese:'彼女は毎日テニスをします。', answer:['She','plays','tennis','every','day','.']},
    {id:'j1_12_3',  japanese:'彼はサッカーが好きです。',   answer:['He','likes','soccer','.']},
    {id:'j1_12_4',  japanese:'彼女は音楽を勉強します。',   answer:['She','studies','music','.']},
    {id:'j1_12_5',  japanese:'彼は自転車を持っています。', answer:['He','has','a','bike','.']},
    {id:'j1_12_6',  japanese:'彼女は速く走ります。',       answer:['She','runs','fast','.']},
    {id:'j1_12_7',  japanese:'彼は料理をします。',         answer:['He','cooks','.']},
    {id:'j1_12_8',  japanese:'彼はピアノを弾きます。',     answer:['He','plays','the','piano','.']},
    {id:'j1_12_9',  japanese:'彼女は英語を教えます。',     answer:['She','teaches','English','.']},
    {id:'j1_12_10', japanese:'彼は犬を飼っています。',     answer:['He','has','a','dog','.']},
    {id:'j1_12_11', japanese:'彼女は毎朝牛乳を飲みます。', answer:['She','drinks','milk','every','morning','.']},
    {id:'j1_12_12', japanese:'彼は野球をします。',         answer:['He','plays','baseball','.']},
    {id:'j1_12_13', japanese:'彼女は日本語を話します。',   answer:['She','speaks','Japanese','.']},
    {id:'j1_12_14', japanese:'彼は図書館で勉強します。',   answer:['He','studies','in','the','library','.']},
    {id:'j1_12_15', japanese:'彼女は歌うことが好きです。', answer:['She','likes','singing','.']},
    {id:'j1_12_16', japanese:'彼は英語を話します。',       answer:['He','speaks','English','.']},
    {id:'j1_12_17', japanese:'彼女は毎日音楽を聴きます。', answer:['She','listens','to','music','every','day','.']},
    {id:'j1_12_18', japanese:'彼は速く走ります。',         answer:['He','runs','fast','.']},
    {id:'j1_12_19', japanese:'彼女は料理が好きです。',     answer:['She','likes','cooking','.']},
  ],
  j1_13: [
    {id:'j1_13_1',  japanese:'彼はテニスをしません。',     answer:['He','doesn\'t','play','tennis','.']},
    {id:'j1_13_2',  japanese:'彼女は英語を話しません。',   answer:['She','doesn\'t','speak','English','.']},
    {id:'j1_13_3',  japanese:'彼はここに住んでいません。', answer:['He','doesn\'t','live','here','.']},
    {id:'j1_13_4',  japanese:'彼はサッカーをしますか。',   answer:['Does','he','play','soccer','?']},
    {id:'j1_13_5',  japanese:'彼女は音楽が好きですか。',   answer:['Does','she','like','music','?']},
    {id:'j1_13_6',  japanese:'彼は何が好きですか。',       answer:['What','does','he','like','?']},
    {id:'j1_13_7',  japanese:'彼女はどこに住んでいますか。',answer:['Where','does','she','live','?']},
    {id:'j1_13_8',  japanese:'彼は日本語を話しません。',   answer:['He','doesn\'t','speak','Japanese','.']},
    {id:'j1_13_9',  japanese:'彼女はピアノを弾きません。', answer:['She','doesn\'t','play','the','piano','.']},
    {id:'j1_13_10', japanese:'彼はここで勉強しますか。',   answer:['Does','he','study','here','?']},
    {id:'j1_13_11', japanese:'彼女は何を食べますか。',     answer:['What','does','she','eat','?']},
    {id:'j1_13_12', japanese:'彼はいつ起きますか。',       answer:['When','does','he','get','up','?']},
    {id:'j1_13_13', japanese:'彼女はどんな音楽が好きですか。',answer:['What','music','does','she','like','?']},
    {id:'j1_13_14', japanese:'彼は速く走りますか。',       answer:['Does','he','run','fast','?']},
    {id:'j1_13_15', japanese:'彼女は英語を勉強しますか。', answer:['Does','she','study','English','?']},
    {id:'j1_13_16', japanese:'彼はテニスをしません。',     answer:['He','doesn\'t','play','tennis','.']},
    {id:'j1_13_17', japanese:'彼女は英語を話しますか。',   answer:['Does','she','speak','English','?']},
    {id:'j1_13_18', japanese:'彼は何をしますか。',         answer:['What','does','he','do','?']},
    {id:'j1_13_19', japanese:'彼女はどこに住んでいますか。',answer:['Where','does','she','live','?']},
    {id:'j1_13_20', japanese:'彼は毎日サッカーをします。', answer:['He','plays','soccer','every','day','.']},
  ],
  j1_14: [
    {id:'j1_14_1',  japanese:'ドアを開けてください。',     answer:['Open','the','door','please','.']},
    {id:'j1_14_2',  japanese:'座ってください。',           answer:['Please','sit','down','.']},
    {id:'j1_14_3',  japanese:'走らないでください。',       answer:['Don\'t','run','.']},
    {id:'j1_14_4',  japanese:'ここで写真を撮らないでください。',answer:['Don\'t','take','pictures','here','.']},
    {id:'j1_14_5',  japanese:'なんて速い車でしょう！',     answer:['How','a','fast','car','!']},
    {id:'j1_14_6',  japanese:'なんてすばらしい日でしょう！',answer:['What','a','beautiful','day','!']},
    {id:'j1_14_7',  japanese:'静かにしなさい。',           answer:['Be','quiet','.']},
    {id:'j1_14_8',  japanese:'優しくしなさい。',           answer:['Be','kind','.']},
    {id:'j1_14_9',  japanese:'英語を勉強しなさい。',       answer:['Study','English','.']},
    {id:'j1_14_10', japanese:'ここで泳がないでください。', answer:['Don\'t','swim','here','.']},
    {id:'j1_14_11', japanese:'なんてかわいい赤ちゃんでしょう！',answer:['What','a','cute','baby','!']},
    {id:'j1_14_12', japanese:'なんてじょうずな歌手でしょう！',answer:['How','a','good','singer','she','is','!']},
    {id:'j1_14_13', japanese:'はやく起きなさい。',         answer:['Get','up','early','.']},
    {id:'j1_14_14', japanese:'本を読みなさい。',           answer:['Read','a','book','.']},
    {id:'j1_14_15', japanese:'ここでサッカーをしないでください。',answer:['Don\'t','play','soccer','here','.']},
    {id:'j1_14_16', japanese:'なんて難しい問題でしょう！', answer:['What','a','difficult','problem','!']},
    {id:'j1_14_17', japanese:'英語を勉強しなさい。',       answer:['Study','English','.']},
    {id:'j1_14_18', japanese:'ここで走らないでください。', answer:['Don\'t','run','here','.']},
    {id:'j1_14_19', japanese:'なんてすばらしい景色でしょう！',answer:['What','a','beautiful','view','!']},
    {id:'j1_14_20', japanese:'手を洗いなさい。',           answer:['Wash','your','hands','.']},
    {id:'j1_14_21', japanese:'うるさくしないでください。', answer:['Don\'t','Be','noisy','.']},
  ],
  j1_15: [
    {id:'j1_15_1',  japanese:'これはあなたの本ですか。それとも私のですか。',answer:['Is','this','your','book','or','mine','?']},
    {id:'j1_15_2',  japanese:'あれは彼の自転車です。',     answer:['That','is','his','bike','.']},
    {id:'j1_15_3',  japanese:'これは彼女のかばんですか。', answer:['Is','this','her','bag','?']},
    {id:'j1_15_4',  japanese:'これはだれのペンですか。',   answer:['Whose','pen','is','this','?']},
    {id:'j1_15_5',  japanese:'あれはだれの自転車ですか。', answer:['Whose','bike','is','that','?']},
    {id:'j1_15_6',  japanese:'これはだれの本ですか。私のです。',answer:['Whose','book','is','this','?']},
    {id:'j1_15_7',  japanese:'あれはだれの自転車ですか。彼のです。',answer:['Whose','bike','is','that','?']},
    {id:'j1_15_8',  japanese:'このかばんはだれのですか。', answer:['Whose','bag','is','this','?']},
    {id:'j1_15_9',  japanese:'あのペンはあなたのですか。', answer:['Is','that','pen','yours','?']},
    {id:'j1_15_10', japanese:'この辞書は彼女のです。',     answer:['This','dictionary','is','hers','.']},
    {id:'j1_15_11', japanese:'あのコンピュータは私たちのです。',answer:['That','computer','is','ours','.']},
  ],
  j1_16: [
    {id:'j1_16_1',  japanese:'私は英語を勉強したいです。', answer:['I','want','to','study','English','.']},
    {id:'j1_16_2',  japanese:'私は音楽を聴くことが好きです。',answer:['I','like','listening','to','music','.']},
    {id:'j1_16_3',  japanese:'私は本を読むことが好きです。',answer:['I','like','reading','books','.']},
    {id:'j1_16_4',  japanese:'私の趣味は料理をすることです。',answer:['My','hobby','is','cooking','.']},
    {id:'j1_16_5',  japanese:'彼女はテニスをすることが好きです。',answer:['She','likes','playing','tennis','.']},
    {id:'j1_16_6',  japanese:'彼は英語を話すことができます。',answer:['He','can','speak','English','.']},
    {id:'j1_16_7',  japanese:'私は本屋に行きたいです。',   answer:['I','want','to','go','to','a','bookstore','.']},
    {id:'j1_16_8',  japanese:'私はサッカーをしたいです。', answer:['I','want','to','play','soccer','.']},
    {id:'j1_16_9',  japanese:'彼女は歌うことが好きです。', answer:['She','likes','singing','.']},
    {id:'j1_16_10', japanese:'私の夢は医者になることです。',answer:['My','dream','is','to','become','a','doctor','.']},
    {id:'j1_16_11', japanese:'彼は料理をすることが上手です。',answer:['He','is','good','at','cooking','.']},
    {id:'j1_16_12', japanese:'私は映画を見ることが好きです。',answer:['I','like','watching','movies','.']},
    {id:'j1_16_13', japanese:'あなたは何をしたいですか。', answer:['What','do','you','want','to','do','?']},
    {id:'j1_16_14', japanese:'彼女は英語を勉強したいです。',answer:['She','wants','to','study','English','.']},
    {id:'j1_16_15', japanese:'私は水泳をすることが好きです。',answer:['I','like','swimming','.']},
    {id:'j1_16_16', japanese:'私は英語を勉強したいです。', answer:['I','want','to','study','English','.']},
    {id:'j1_16_17', japanese:'彼女は歌うことが好きです。', answer:['She','likes','singing','.']},
    {id:'j1_16_18', japanese:'私の夢はサッカー選手になることです。',answer:['My','dream','is','to','become','a','soccer','player','.']},
    {id:'j1_16_19', japanese:'彼は料理が好きです。',       answer:['He','likes','cooking','.']},
  ],
  j1_17: [
    {id:'j1_17_1',  japanese:'今、何時ですか。３時です。', answer:['It','is','three','o\'clock','.']},
    {id:'j1_17_2',  japanese:'今日は何曜日ですか。月曜日です。',answer:['It','is','Monday','.']},
    {id:'j1_17_3',  japanese:'今日は何日ですか。５月３日です。',answer:['It','is','May','third','.']},
    {id:'j1_17_4',  japanese:'あなたの誕生日はいつですか。',answer:['When','is','your','birthday','?']},
    {id:'j1_17_5',  japanese:'今、７時15分です。',         answer:['It','is','quarter','past','seven','.']},
    {id:'j1_17_6',  japanese:'今、５時半です。',           answer:['It','is','half','past','five','.']},
    {id:'j1_17_7',  japanese:'今、何時ですか。',           answer:['What','time','is','it','?']},
    {id:'j1_17_8',  japanese:'今日は何曜日ですか。',       answer:['What','day','is','it','?']},
    {id:'j1_17_9',  japanese:'今日は何日ですか。',         answer:['What','is','the','date','today','?']},
    {id:'j1_17_10', japanese:'あなたの誕生日は何月何日ですか。',answer:['When','is','your','birthday','?']},
    {id:'j1_17_11', japanese:'学校は何時に始まりますか。', answer:['What','time','does','school','start','?']},
    {id:'j1_17_12', japanese:'今日は木曜日です。',         answer:['It','is','Thursday','.']},
    {id:'j1_17_13', japanese:'私の誕生日は10月14日です。', answer:['It','is','October','fourteenth','.']},
    {id:'j1_17_14', japanese:'今、何時ですか。',           answer:['What','time','is','it','?']},
    {id:'j1_17_15', japanese:'今日は何曜日ですか。',       answer:['What','day','is','it','?']},
    {id:'j1_17_16', japanese:'今日は何日ですか。',         answer:['What','is','the','date','today','?']},
    {id:'j1_17_17', japanese:'あなたの誕生日はいつですか。',answer:['When','is','your','birthday','?']},
  ],
  j1_18: [
    {id:'j1_18_1',  japanese:'本は机の上にあります。',     answer:['The','book','is','on','the','desk','.']},
    {id:'j1_18_2',  japanese:'鉛筆は箱の中にあります。',   answer:['The','pencil','is','in','the','box','.']},
    {id:'j1_18_3',  japanese:'公園の近くに学校があります。',answer:['There','is','a','school','near','the','park','.']},
    {id:'j1_18_4',  japanese:'私は朝に英語を勉強します。', answer:['I','study','English','in','the','morning','.']},
    {id:'j1_18_5',  japanese:'私は月曜日にテニスをします。',answer:['I','play','tennis','on','Monday','.']},
    {id:'j1_18_6',  japanese:'彼女は7時に起きます。',      answer:['She','gets','up','at','seven','.']},
    {id:'j1_18_7',  japanese:'私は疲れているので、早く寝ます。',answer:['I','go','to','bed','early','because','I\'m','tired','.']},
    {id:'j1_18_8',  japanese:'図書館は駅の前にあります。', answer:['The','library','is','in','front','of','the','station','.']},
    {id:'j1_18_9',  japanese:'ネコはソファの下にいます。', answer:['The','cat','is','under','the','sofa','.']},
    {id:'j1_18_10', japanese:'私は毎週土曜日にサッカーをします。',answer:['I','play','soccer','on','every','Saturday','.']},
    {id:'j1_18_11', japanese:'彼女は夜に音楽を聴きます。', answer:['She','listens','to','music','at','night','.']},
    {id:'j1_18_12', japanese:'私は英語が好きですが、数学は得意ではありません。',answer:['I','like','English','but','I','am','not','good','at','math','.']},
    {id:'j1_18_13', japanese:'彼は疲れていたので、早く寝ました。',answer:['He','went','to','bed','early','because','he','was','tired','.']},
    {id:'j1_18_14', japanese:'花は机の上にあります。',     answer:['The','flowers','are','on','the','desk','.']},
    {id:'j1_18_15', japanese:'本は机の上にあります。',     answer:['The','book','is','on','the','desk','.']},
    {id:'j1_18_16', japanese:'私は朝に音楽を聴きます。',   answer:['I','listen','to','music','in','the','morning','.']},
    {id:'j1_18_17', japanese:'彼女は疲れているので、休みます。',answer:['She','will','rest','because','she','is','tired','.']},
    {id:'j1_18_18', japanese:'公園は図書館の近くにあります。',answer:['The','park','is','near','the','library','.']},
  ],
  j1_19: [
    {id:'j1_19_1',  japanese:'どちらが好きですか。',       answer:['Which','do','you','like','?']},
    {id:'j1_19_2',  japanese:'どちらの本が好きですか。',   answer:['Which','book','do','you','like','?']},
    {id:'j1_19_3',  japanese:'あなたはどうやって学校に来ますか。',answer:['How','do','you','come','to','school','?']},
    {id:'j1_19_4',  japanese:'あなたはどのくらいの長さですか。',answer:['How','long','are','you','?']},
    {id:'j1_19_5',  japanese:'あなたはどのくらい背が高いですか。',answer:['How','tall','are','you','?']},
    {id:'j1_19_6',  japanese:'あなたはどのくらいの頻度でテニスをしますか。',answer:['How','often','do','you','play','tennis','?']},
    {id:'j1_19_7',  japanese:'どちらのかばんがあなたのですか。',answer:['Which','bag','is','yours','?']},
    {id:'j1_19_8',  japanese:'あなたはどうやって英語を勉強しますか。',answer:['How','do','you','study','English','?']},
    {id:'j1_19_9',  japanese:'あなたはどのくらいの頻度でサッカーをしますか。',answer:['How','often','do','you','play','soccer','?']},
    {id:'j1_19_10', japanese:'あなたはどのくらいの速さで走りますか。',answer:['How','fast','do','you','run','?']},
    {id:'j1_19_11', japanese:'どちらのペンが好きですか。', answer:['Which','pen','do','you','like','?']},
    {id:'j1_19_12', japanese:'あなたはどうやってここに来ましたか。',answer:['How','did','you','come','here','?']},
    {id:'j1_19_13', japanese:'あなたはどのくらいの高さですか。',answer:['How','tall','are','you','?']},
    {id:'j1_19_14', japanese:'どちらが好きですか。',       answer:['Which','do','you','like','?']},
    {id:'j1_19_15', japanese:'あなたはどうやって学校に来ますか。',answer:['How','do','you','come','to','school','?']},
    {id:'j1_19_16', japanese:'あなたはどのくらいの頻度でピアノを弾きますか。',answer:['How','often','do','you','play','the','piano','?']},
    {id:'j1_19_17', japanese:'どちらのスポーツが好きですか。',answer:['Which','sport','do','you','like','?']},
  ],
  j1_20: [
    {id:'j1_20_1',  japanese:'私は今、テレビを見ています。',answer:['I','am','watching','TV','now','.']},
    {id:'j1_20_2',  japanese:'彼は今、本を読んでいます。', answer:['He','is','reading','a','book','now','.']},
    {id:'j1_20_3',  japanese:'彼女は今、音楽を聴いています。',answer:['She','is','listening','to','music','now','.']},
    {id:'j1_20_4',  japanese:'私は今、夕食を料理していません。',answer:['I','am','not','cooking','dinner','now','.']},
    {id:'j1_20_5',  japanese:'彼らは今、野球について話しています。',answer:['They','are','talking','about','baseball','.']},
    {id:'j1_20_6',  japanese:'私たちは今、歌を歌っています。',answer:['We','are','singing','songs','now','.']},
    {id:'j1_20_7',  japanese:'あなたは今、英語を勉強していますか。',answer:['Are','you','studying','English','now','?']},
    {id:'j1_20_8',  japanese:'彼はピアノを練習していますか。',answer:['Is','he','practicing','the','piano','?']},
    {id:'j1_20_9',  japanese:'私は今、英語の本を読んでいます。',answer:['I','am','reading','an','English','book','.']},
    {id:'j1_20_10', japanese:'ケンは川で泳いでいます。',   answer:['Ken','is','swimming','in','the','river','.']},
    {id:'j1_20_11', japanese:'クミは数学を勉強しています。',answer:['Kumi','is','studying','math','.']},
    {id:'j1_20_12', japanese:'私は今、夕食を作っていません。',answer:['I','am','not','cooking','dinner','now','.']},
    {id:'j1_20_13', japanese:'彼らは野球について話しています。',answer:['They','are','talking','about','baseball','.']},
    {id:'j1_20_14', japanese:'私たちは歌を歌っています。', answer:['We','are','singing','songs','.']},
    {id:'j1_20_15', japanese:'彼女はラジオを聴いています。',answer:['She','is','listening','to','the','radio','.']},
    {id:'j1_20_16', japanese:'あなたは今、英語を勉強していますか。',answer:['Are','you','studying','English','now','?']},
    {id:'j1_20_17', japanese:'私は今、テレビを見ています。',answer:['I','am','watching','TV','now','.']},
    {id:'j1_20_18', japanese:'彼は本を読んでいます。',     answer:['He','is','reading','a','book','.']},
    {id:'j1_20_19', japanese:'彼女は音楽を聴いていますか。',answer:['Is','she','listening','to','music','?']},
    {id:'j1_20_20', japanese:'彼らは公園でサッカーをしています。',answer:['They','are','playing','soccer','in','the','park','.']},
  ],
  j1_21: [
    {id:'j1_21_1',  japanese:'私はきのうサッカーをしました。',answer:['I','played','soccer','yesterday','.']},
    {id:'j1_21_2',  japanese:'彼女はきのう英語を勉強しました。',answer:['She','studied','English','yesterday','.']},
    {id:'j1_21_3',  japanese:'彼はきのう図書館を訪れました。',answer:['He','visited','the','library','yesterday','.']},
    {id:'j1_21_4',  japanese:'私はきのうテレビを見ませんでした。',answer:['I','did','not','watch','TV','yesterday','.']},
    {id:'j1_21_5',  japanese:'彼女はきのう音楽を聴きませんでした。',answer:['She','did','not','listen','to','music','yesterday','.']},
    {id:'j1_21_6',  japanese:'あなたはきのう英語を勉強しましたか。',answer:['Did','you','study','English','yesterday','?']},
    {id:'j1_21_7',  japanese:'あなたはきのう何をしましたか。',answer:['What','did','you','do','yesterday','?']},
    {id:'j1_21_8',  japanese:'彼はきのう公園を歩きました。',answer:['He','walked','in','the','park','yesterday','.']},
    {id:'j1_21_9',  japanese:'彼女はきのう料理をしました。',answer:['She','cooked','yesterday','.']},
    {id:'j1_21_10', japanese:'私はきのう宿題をしました。', answer:['I','did','my','homework','yesterday','.']},
    {id:'j1_21_11', japanese:'彼はきのうテニスをしませんでした。',answer:['He','did','not','play','tennis','yesterday','.']},
    {id:'j1_21_12', japanese:'彼女はきのう学校に行きましたか。',answer:['Did','she','go','to','school','yesterday','?']},
    {id:'j1_21_13', japanese:'あなたはきのう何時に起きましたか。',answer:['What','time','did','you','get','up','yesterday','?']},
    {id:'j1_21_14', japanese:'私はきのう友達と話しました。',answer:['I','talked','with','a','friend','yesterday','.']},
    {id:'j1_21_15', japanese:'私はきのうサッカーをしました。',answer:['I','played','soccer','yesterday','.']},
    {id:'j1_21_16', japanese:'彼女はきのう英語を勉強しましたか。',answer:['Did','she','study','English','yesterday','?']},
    {id:'j1_21_17', japanese:'あなたはきのう何をしましたか。',answer:['What','did','you','do','yesterday','?']},
    {id:'j1_21_18', japanese:'彼はきのう公園を走りませんでした。',answer:['He','did','not','run','in','the','park','yesterday','.']},
  ],
  j1_22: [
    {id:'j1_22_1',  japanese:'私はきのう公園に行きました。',answer:['I','went','to','the','park','yesterday','.']},
    {id:'j1_22_2',  japanese:'彼女はきのう本を読みました。',answer:['She','read','a','book','yesterday','.']},
    {id:'j1_22_3',  japanese:'彼はきのう朝食を食べました。',answer:['He','had','breakfast','yesterday','.']},
    {id:'j1_22_4',  japanese:'私はきのう友達に会いました。',answer:['I','met','a','friend','yesterday','.']},
    {id:'j1_22_5',  japanese:'彼女はきのう何を食べましたか。',answer:['What','did','she','eat','yesterday','?']},
    {id:'j1_22_6',  japanese:'あなたはきのうどこに行きましたか。',answer:['Where','did','you','go','yesterday','?']},
    {id:'j1_22_7',  japanese:'私はきのうテレビを見ました。',answer:['I','watched','TV','yesterday','.']},
    {id:'j1_22_8',  japanese:'彼はきのう図書館に行きました。',answer:['He','went','to','the','library','yesterday','.']},
    {id:'j1_22_9',  japanese:'彼女はきのう手紙を書きました。',answer:['She','wrote','a','letter','yesterday','.']},
    {id:'j1_22_10', japanese:'私はきのう音楽を聴きました。',answer:['I','listened','to','music','yesterday','.']},
    {id:'j1_22_11', japanese:'彼はきのう何を食べましたか。',answer:['What','did','he','eat','yesterday','?']},
    {id:'j1_22_12', japanese:'彼女はきのうどこに行きましたか。',answer:['Where','did','she','go','yesterday','?']},
    {id:'j1_22_13', japanese:'あなたはきのう何時に起きましたか。',answer:['What','time','did','you','get','up','yesterday','?']},
    {id:'j1_22_14', japanese:'私はきのう友達と公園に行きました。',answer:['I','went','to','the','park','with','a','friend','yesterday','.']},
    {id:'j1_22_15', japanese:'私はきのう図書館に行きました。',answer:['I','went','to','the','library','yesterday','.']},
    {id:'j1_22_16', japanese:'彼女はきのう何を食べましたか。',answer:['What','did','she','eat','yesterday','?']},
    {id:'j1_22_17', japanese:'あなたはきのうどこに行きましたか。',answer:['Where','did','you','go','yesterday','?']},
    {id:'j1_22_18', japanese:'彼はきのう本を読みました。', answer:['He','read','a','book','yesterday','.']},
  ],
  j1_23: [
    {id:'j1_23_1',  japanese:'私はきのう忙しかったです。', answer:['I','was','busy','yesterday','.']},
    {id:'j1_23_2',  japanese:'彼女はきのう学校にいました。',answer:['She','was','at','school','yesterday','.']},
    {id:'j1_23_3',  japanese:'彼らはきのうここにいませんでした。',answer:['They','were','not','here','yesterday','.']},
    {id:'j1_23_4',  japanese:'あなたはきのう忙しかったですか。',answer:['Were','you','busy','yesterday','?']},
    {id:'j1_23_5',  japanese:'彼女はきのうどこにいましたか。',answer:['Where','was','she','yesterday','?']},
    {id:'j1_23_6',  japanese:'天気はどうでしたか。',       answer:['What','was','the','weather','like','?']},
    {id:'j1_23_7',  japanese:'彼はきのう病気でした。',     answer:['He','was','sick','yesterday','.']},
    {id:'j1_23_8',  japanese:'私たちはきのう公園にいました。',answer:['We','were','in','the','park','yesterday','.']},
    {id:'j1_23_9',  japanese:'彼女はきのう家にいませんでした。',answer:['She','was','not','at','home','yesterday','.']},
    {id:'j1_23_10', japanese:'あなたはきのうどこにいましたか。',answer:['Where','were','you','yesterday','?']},
    {id:'j1_23_11', japanese:'天気はよかったですか。',     answer:['Was','the','weather','good','?']},
    {id:'j1_23_12', japanese:'彼らはきのう疲れていましたか。',answer:['Were','they','tired','yesterday','?']},
    {id:'j1_23_13', japanese:'私はきのう元気でした。',     answer:['I','was','fine','yesterday','.']},
    {id:'j1_23_14', japanese:'私はきのう忙しかったです。', answer:['I','was','busy','yesterday','.']},
    {id:'j1_23_15', japanese:'彼女はきのうどこにいましたか。',answer:['Where','was','she','yesterday','?']},
    {id:'j1_23_16', japanese:'彼らはきのうここにいませんでした。',answer:['They','were','not','here','yesterday','.']},
    {id:'j1_23_17', japanese:'あなたはきのう元気でしたか。',answer:['Were','you','fine','yesterday','?']},
  ],
  j1_24: [
    {id:'j1_24_1',  japanese:'私はそのとき本を読んでいました。',answer:['I','was','reading','a','book','then','.']},
    {id:'j1_24_2',  japanese:'彼女はそのとき音楽を聴いていました。',answer:['She','was','listening','to','music','then','.']},
    {id:'j1_24_3',  japanese:'彼はそのとき料理をしていませんでした。',answer:['He','was','not','cooking','then','.']},
    {id:'j1_24_4',  japanese:'あなたはそのとき何をしていましたか。',answer:['What','were','you','doing','then','?']},
    {id:'j1_24_5',  japanese:'彼らはそのとき公園で遊んでいましたか。',answer:['Were','they','playing','in','the','park','?']},
    {id:'j1_24_6',  japanese:'彼はそのとき英語を勉強していました。',answer:['He','was','studying','English','then','.']},
    {id:'j1_24_7',  japanese:'彼女はそのとき料理をしていました。',answer:['She','was','cooking','then','.']},
    {id:'j1_24_8',  japanese:'私はそのとき音楽を聴いていませんでした。',answer:['I','was','not','listening','to','music','then','.']},
    {id:'j1_24_9',  japanese:'あなたはそのとき何をしていましたか。',answer:['What','were','you','doing','then','?']},
    {id:'j1_24_10', japanese:'彼らはそのとき歌を歌っていましたか。',answer:['Were','they','singing','songs','?']},
    {id:'j1_24_11', japanese:'彼女はそのとき手紙を書いていました。',answer:['She','was','writing','a','letter','then','.']},
    {id:'j1_24_12', japanese:'私はそのとき本を読んでいました。',answer:['I','was','reading','a','book','then','.']},
    {id:'j1_24_13', japanese:'彼女はそのとき音楽を聴いていましたか。',answer:['Was','she','listening','to','music','?']},
    {id:'j1_24_14', japanese:'彼らはそのとき公園で遊んでいましたか。',answer:['Were','they','playing','in','the','park','?']},
    {id:'j1_24_15', japanese:'あなたはそのとき何をしていましたか。',answer:['What','were','you','doing','then','?']},
  ],
  j1_25: [
    {id:'j1_25_1',  japanese:'彼女は幸せそうに見えます。', answer:['She','looks','happy','.']},
    {id:'j1_25_2',  japanese:'彼は医者になりました。',     answer:['He','became','a','doctor','.']},
    {id:'j1_25_3',  japanese:'彼女は私に本をくれました。', answer:['She','gave','me','a','book','.']},
    {id:'j1_25_4',  japanese:'私は彼女に花を買いました。', answer:['I','bought','her','some','flowers','.']},
    {id:'j1_25_5',  japanese:'彼らは彼女をエミと呼びます。',answer:['They','call','her','Emi','.']},
    {id:'j1_25_6',  japanese:'彼は悲しそうに見えます。',   answer:['He','looks','sad','.']},
    {id:'j1_25_7',  japanese:'彼女は先生になりました。',   answer:['She','became','a','teacher','.']},
    {id:'j1_25_8',  japanese:'父は私に本をくれました。',   answer:['My','father','gave','me','a','book','.']},
    {id:'j1_25_9',  japanese:'彼女は私に花をくれました。', answer:['She','gave','me','some','flowers','.']},
    {id:'j1_25_10', japanese:'私たちは彼をタロウと呼びます。',answer:['We','call','him','Taro','.']},
    {id:'j1_25_11', japanese:'彼女はケーキを美味しそうに見せました。',answer:['She','looked','the','cake','delicious','.']},
  ],
  j1_26: [
    {id:'j1_26_1',  japanese:'机の上に本が１冊あります。', answer:['There','is','a','book','on','the','desk','.']},
    {id:'j1_26_2',  japanese:'公園に子どもたちがいます。', answer:['There','are','children','in','the','park','.']},
    {id:'j1_26_3',  japanese:'テーブルの上にりんごが３つあります。',answer:['There','are','three','apples','on','the','table','.']},
    {id:'j1_26_4',  japanese:'庭に花はありません。',       answer:['There','aren\'t','any','flowers','in','the','garden','.']},
    {id:'j1_26_5',  japanese:'箱の中に何かありますか。',   answer:['Is','there','anything','in','the','box','?']},
    {id:'j1_26_6',  japanese:'公園に何人の子どもがいますか。',answer:['How','many','children','are','there','in','the','park','?']},
    {id:'j1_26_7',  japanese:'この町には図書館が１つあります。',answer:['There','is','a','library','in','this','town','.']},
    {id:'j1_26_8',  japanese:'部屋に犬が２匹います。',     answer:['There','are','two','dogs','in','the','room','.']},
    {id:'j1_26_9',  japanese:'テーブルの下には何もありません。',answer:['There','isn\'t','anything','under','the','table','.']},
    {id:'j1_26_10', japanese:'学校の近くに公園はありますか。',answer:['Is','there','a','park','near','the','school','?']},
    {id:'j1_26_11', japanese:'この町には病院が何軒ありますか。',answer:['How','many','hospitals','are','there','in','this','town','?']},
    {id:'j1_26_12', japanese:'部屋の中に椅子が３つあります。',answer:['There','are','three','chairs','in','the','room','.']},
    {id:'j1_26_13', japanese:'この公園には木が何本ありますか。',answer:['How','many','trees','are','there','in','this','park','?']},
    {id:'j1_26_14', japanese:'机の上に本が１冊あります。', answer:['There','is','a','book','on','the','desk','.']},
    {id:'j1_26_15', japanese:'部屋に子どもたちがいます。', answer:['There','are','children','in','the','room','.']},
    {id:'j1_26_16', japanese:'テーブルの下には何もありません。',answer:['There','isn\'t','anything','under','the','table','.']},
    {id:'j1_26_17', japanese:'公園に何人の子どもがいますか。',answer:['How','many','children','are','there','in','the','park','?']},
  ],
}
