// 中学2年 全問題データ
export const QUESTIONS_J2 = {
  j2_1: [
    {id:'j2_1_1',  japanese:'トムはきのう歩いて学校へ行きました。',answer:['Tom','walked','to','school','yesterday','.']},
    {id:'j2_1_2',  japanese:'そのときその車は止まりました。',answer:['The','car','stopped','then','.']},
    {id:'j2_1_3',  japanese:'まことは今朝走って公園へ行きました。',answer:['Makoto','ran','to','the','park','this','morning','.']},
    {id:'j2_1_4',  japanese:'父は私に「おはよう」と言いました。',answer:['My','father','said','Good','morning','to','me','.']},
    {id:'j2_1_5',  japanese:'私たちは１ぴきの黒いネコを見ました。',answer:['We','saw','a','black','cat','.']},
    {id:'j2_1_6',  japanese:'ナンシーにきのう電話しませんでした。',answer:['I','did','not','call','Nancy','yesterday','.']},
    {id:'j2_1_7',  japanese:'私たちは庭で写真を撮りませんでした。',answer:['We','did','not','take','any','pictures','in','the','garden','.']},
    {id:'j2_1_8',  japanese:'ユキは新しい自転車を買いませんでした。',answer:['Yuki','did','not','buy','a','new','bike','.']},
    {id:'j2_1_9',  japanese:'タロウはギターを弾きましたか。',answer:['Did','Taro','play','the','guitar','?']},
    {id:'j2_1_10', japanese:'生徒たちは図書館に行きましたか。',answer:['Did','the','students','go','to','the','library','?']},
    {id:'j2_1_11', japanese:'彼は昨日図書館に行きました。',answer:['He','went','to','the','library','yesterday','.']},
    {id:'j2_1_12', japanese:'彼女は手紙を書きました。',answer:['She','wrote','a','letter','.']},
    {id:'j2_1_13', japanese:'彼らは去年日本に来ました。',answer:['They','came','to','Japan','last','year','.']},
    {id:'j2_1_14', japanese:'彼は私に自転車をくれました。',answer:['He','gave','me','a','bike','.']},
    {id:'j2_1_15', japanese:'彼女はそのニュースを知っていました。',answer:['She','knew','the','news','.']},
    {id:'j2_1_16', japanese:'私はきのうケンに会いました。',answer:['I','met','Ken','yesterday','.']},
    {id:'j2_1_17', japanese:'彼らはきのうここに来ました。',answer:['They','came','here','yesterday','.']},
    {id:'j2_1_18', japanese:'彼女はその本を読みました。',answer:['She','read','the','book','.']},
    {id:'j2_1_19', japanese:'私はきのうテニスをしました。',answer:['I','played','tennis','yesterday','.']},
    {id:'j2_1_20', japanese:'彼はきのう公園を走りました。',answer:['He','ran','in','the','park','yesterday','.']},
    {id:'j2_1_21', japanese:'私はきのう図書館に行きました。',answer:['I','went','to','the','library','yesterday','.']},
    {id:'j2_1_22', japanese:'彼女はきのう何を食べましたか。',answer:['What','did','she','eat','yesterday','?']},
    {id:'j2_1_23', japanese:'彼らはきのう学校に来ませんでした。',answer:['They','did','not','come','to','school','yesterday','.']},
    {id:'j2_1_24', japanese:'あなたはきのうどこに行きましたか。',answer:['Where','did','you','go','yesterday','?']},
  ],
  j2_2: [
    {id:'j2_2_1',  japanese:'私はきのう忙しかったです。',  answer:['I','was','busy','yesterday','.']},
    {id:'j2_2_2',  japanese:'彼らはきのうここにいました。',answer:['They','were','here','yesterday','.']},
    {id:'j2_2_3',  japanese:'彼女はきのう家にいませんでした。',answer:['She','was','not','at','home','yesterday','.']},
    {id:'j2_2_4',  japanese:'あなたはきのうどこにいましたか。',answer:['Where','were','you','yesterday','?']},
    {id:'j2_2_5',  japanese:'私はそのとき本を読んでいました。',answer:['I','was','reading','a','book','then','.']},
    {id:'j2_2_6',  japanese:'彼女はそのとき歌を歌っていましたか。',answer:['Was','She','singing','songs','?']},
    {id:'j2_2_7',  japanese:'彼らはそのとき野球をしていませんでした。',answer:['They','were','not','playing','baseball','.']},
    {id:'j2_2_8',  japanese:'彼はきのう病気でした。',      answer:['He','was','sick','yesterday','.']},
    {id:'j2_2_9',  japanese:'彼女はきのう学校にいました。',answer:['She','was','at','school','yesterday','.']},
    {id:'j2_2_10', japanese:'私たちはきのう公園にいませんでした。',answer:['We','were','not','in','the','park','yesterday','.']},
    {id:'j2_2_11', japanese:'あなたはきのう何をしていましたか。',answer:['What','were','you','doing','yesterday','?']},
    {id:'j2_2_12', japanese:'彼はそのとき英語を勉強していました。',answer:['He','was','studying','English','then','.']},
    {id:'j2_2_13', japanese:'彼女はそのとき料理をしていましたか。',answer:['Was','she','cooking','?']},
    {id:'j2_2_14', japanese:'彼らはそのとき音楽を聴いていませんでした。',answer:['They','were','not','listening','to','music','.']},
  ],
  j2_3: [
    {id:'j2_3_1',  japanese:'私たちは彼をパーティーに招くつもりです。',answer:['We','are','going','to','invite','him','to','the','party','.']},
    {id:'j2_3_2',  japanese:'彼はきょうの午後、犬を散歩に連れていくつもりです。',answer:['He','is','going','to','take','his','dog','for','a','walk','this','afternoon','.']},
    {id:'j2_3_3',  japanese:'私の母はあしたテニスをするつもりです。',answer:['My','mother','is','going','to','play','tennis','tomorrow','.']},
    {id:'j2_3_4',  japanese:'今晩、ピアノの練習をするつもりはありません。',answer:['I','am','not','going','to','practice','the','piano','this','evening','.']},
    {id:'j2_3_5',  japanese:'あなたはこの手紙を彼女に送るつもりですか。',answer:['Are','you','going','to','send','this','letter','to','her','?']},
    {id:'j2_3_6',  japanese:'彼はあした何をするつもりですか。',answer:['What','is','he','going','to','do','tomorrow','?']},
    {id:'j2_3_7',  japanese:'彼女はあした映画を見るつもりです。',answer:['She','is','going','to','see','a','movie','tomorrow','.']},
    {id:'j2_3_8',  japanese:'彼らは来週日本に来るつもりです。',answer:['They','are','going','to','come','to','Japan','next','week','.']},
    {id:'j2_3_9',  japanese:'私はあした英語を勉強するつもりはありません。',answer:['I','am','not','going','to','study','English','tomorrow','.']},
    {id:'j2_3_10', japanese:'あなたはあした何をするつもりですか。',answer:['What','are','you','going','to','do','tomorrow','?']},
    {id:'j2_3_11', japanese:'彼は来週スキーに行くつもりです。',answer:['He','is','going','to','go','skiing','next','week','.']},
  ],
  j2_4: [
    {id:'j2_4_1',  japanese:'私は来週サッカーをするつもりです。',answer:['I','will','play','soccer','next','week','.']},
    {id:'j2_4_2',  japanese:'彼女はあした図書館に行くでしょう。',answer:['She','will','go','to','the','library','tomorrow','.']},
    {id:'j2_4_3',  japanese:'彼はあしたここに来ないでしょう。',answer:['He','will','not','come','here','tomorrow','.']},
    {id:'j2_4_4',  japanese:'あなたはあした映画を見ますか。',answer:['Will','you','see','a','movie','tomorrow','?']},
    {id:'j2_4_5',  japanese:'あなたは来年どこに行きますか。',answer:['Where','will','you','go','next','year','?']},
    {id:'j2_4_6',  japanese:'彼女はあした何をしますか。',  answer:['What','will','she','do','tomorrow','?']},
    {id:'j2_4_7',  japanese:'私はあした友達に会うでしょう。',answer:['I','will','meet','my','friend','tomorrow','.']},
    {id:'j2_4_8',  japanese:'彼は来年医者になるでしょう。',answer:['He','will','become','a','doctor','next','year','.']},
    {id:'j2_4_9',  japanese:'彼女は来週ここに来ないでしょう。',answer:['She','will','not','come','here','next','week','.']},
    {id:'j2_4_10', japanese:'あなたは来月英語を勉強しますか。',answer:['Will','you','study','English','next','month','?']},
    {id:'j2_4_11', japanese:'彼らは来週日本に来るでしょう。',answer:['They','will','come','to','Japan','next','week','.']},
    {id:'j2_4_12', japanese:'あなたはあした何をしますか。',answer:['What','will','you','do','tomorrow','?']},
  ],
  j2_5: [
    {id:'j2_5_1',  japanese:'私はすき焼きを作ることができます。',answer:['I','can','make','sukiyaki','.']},
    {id:'j2_5_2',  japanese:'トムはギターを弾くことができます。',answer:['Tom','can','play','the','guitar','.']},
    {id:'j2_5_3',  japanese:'あなたはこのケーキを食べてもいいです。',answer:['You','can','eat','this','cake','.']},
    {id:'j2_5_4',  japanese:'彼女は速く歩くことができませんでした。',answer:['She','couldn\'t','walk','fast','.']},
    {id:'j2_5_5',  japanese:'あなたはこのペンを使ってもいいですよ。',answer:['You','can','use','this','pen','.']},
    {id:'j2_5_6',  japanese:'トムはきょう、ここに来るかもしれません。',answer:['Tom','may','come','here','today','.']},
    {id:'j2_5_7',  japanese:'あの女の人はケイトのお母さんかもしれません。',answer:['That','woman','may','be','Kate\'s','mother','.']},
    {id:'j2_5_8',  japanese:'私はきょう、学校へ行かなければなりません。',answer:['I','have','to','go','to','school','today','.']},
    {id:'j2_5_9',  japanese:'クミはこの本を読まなければなりません。',answer:['Kumi','has','to','read','this','book','.']},
    {id:'j2_5_10', japanese:'けい子は今、ひまにちがいありません。',answer:['Keiko','must','be','free','now','.']},
    {id:'j2_5_11', japanese:'私たちはこの部屋をきれいにするべきです。',answer:['We','should','clean','this','room','.']},
    {id:'j2_5_12', japanese:'彼はユキを手伝うべきです。',  answer:['He','should','help','Yuki','.']},
    {id:'j2_5_13', japanese:'妹は私たちと朝食を食べるべきです。',answer:['My','sister','has','breakfast','with','us','.']},
    {id:'j2_5_14', japanese:'私は英語を話すことができます。',answer:['I','can','speak','English','.']},
    {id:'j2_5_15', japanese:'彼女はピアノを弾くことができますか。',answer:['Can','she','play','the','piano','?']},
    {id:'j2_5_16', japanese:'彼はここに来るかもしれません。',answer:['He','may','come','here','.']},
    {id:'j2_5_17', japanese:'私はきょう宿題をしなければなりません。',answer:['I','have','to','do','my','homework','today','.']},
    {id:'j2_5_18', japanese:'彼女は毎日英語を勉強すべきです。',answer:['She','should','study','English','every','day','.']},
    {id:'j2_5_19', japanese:'あなたはここで泳いではいけません。',answer:['You','must','not','swim','here','.']},
  ],
  j2_6: [
    {id:'j2_6_1',  japanese:'ドアを開けてくれませんか。',  answer:['Will','you','open','the','door','?']},
    {id:'j2_6_2',  japanese:'お水を１杯持ってきてくれませんか。',answer:['Will','you','bring','me','a','glass','of','water','?']},
    {id:'j2_6_3',  japanese:'コーヒーはいかがですか。',    answer:['Would','you','have','some','coffee','?']},
    {id:'j2_6_4',  japanese:'そのかばんを選びましょうか。',answer:['Shall','I','carry','the','bag','?']},
    {id:'j2_6_5',  japanese:'今度の日曜日にピクニックに行きましょうか。',answer:['Shall','we','go','on','a','picnic','next','Sunday','?']},
    {id:'j2_6_6',  japanese:'あなたは早く寝るべきです。',  answer:['You','should','go','to','bed','early','.']},
    {id:'j2_6_7',  japanese:'私は沖縄をまた訪れたいものです。',answer:['I','would','like','to','visit','Okinawa','again','.']},
    {id:'j2_6_8',  japanese:'お茶はいかがですか。',        answer:['Would','you','like','some','tea','?']},
    {id:'j2_6_9',  japanese:'窓を開けてくれませんか。',    answer:['Will','you','open','the','window','?']},
    {id:'j2_6_10', japanese:'テニスをしましょうか。',      answer:['Shall','we','play','tennis','?']},
    {id:'j2_6_11', japanese:'何かお手伝いしましょうか。',  answer:['Can','I','help','you','?']},
    {id:'j2_6_12', japanese:'お茶はいかがですか。',        answer:['Would','you','like','some','tea','?']},
    {id:'j2_6_13', japanese:'私は彼を家に招待したいと思っています。',answer:['I','would','like','to','invite','him','to','my','house','.']},
    {id:'j2_6_14', japanese:'一緒にサッカーをしましょう。',answer:['Let\'s','play','soccer','together','.']},
  ],
  j2_7: [
    {id:'j2_7_1',  japanese:'机の上に本が１冊あります。',  answer:['There','is','a','book','on','the','desk','.']},
    {id:'j2_7_2',  japanese:'公園に子どもたちがいます。',  answer:['There','are','children','in','the','park','.']},
    {id:'j2_7_3',  japanese:'テーブルの上にりんごが３つあります。',answer:['There','are','three','apples','on','the','table','.']},
    {id:'j2_7_4',  japanese:'庭に花はありません。',        answer:['There','aren\'t','any','flowers','in','the','garden','.']},
    {id:'j2_7_5',  japanese:'箱の中に何かありますか。',    answer:['Is','there','anything','in','the','box','?']},
    {id:'j2_7_6',  japanese:'部屋に何人の学生がいますか。',answer:['How','many','students','are','there','in','the','room','?']},
    {id:'j2_7_7',  japanese:'この町には図書館が１つあります。',answer:['There','is','a','library','in','this','town','.']},
    {id:'j2_7_8',  japanese:'部屋に犬が２匹います。',      answer:['There','are','two','dogs','in','the','room','.']},
    {id:'j2_7_9',  japanese:'テーブルの下には何もありません。',answer:['There','isn\'t','anything','under','the','table','.']},
    {id:'j2_7_10', japanese:'学校の近くに公園はありますか。',answer:['Is','there','a','park','near','the','school','?']},
    {id:'j2_7_11', japanese:'この町には病院が何軒ありますか。',answer:['How','many','hospitals','are','there','in','this','town','?']},
  ],
  j2_8: [
    {id:'j2_8_1',  japanese:'ドアを開けてください。',      answer:['Open','the','door','please','.']},
    {id:'j2_8_2',  japanese:'走らないでください。',        answer:['Don\'t','run','.']},
    {id:'j2_8_3',  japanese:'静かにしなさい。',            answer:['Be','quiet','.']},
    {id:'j2_8_4',  japanese:'なんてすばらしい日でしょう！',answer:['What','a','beautiful','day','!']},
    {id:'j2_8_5',  japanese:'なんてじょうずな歌手でしょう！',answer:['How','a','good','singer','!']},
    {id:'j2_8_6',  japanese:'なんて大きい家でしょう！',    answer:['What','a','big','house','!']},
    {id:'j2_8_7',  japanese:'英語を勉強しなさい。',        answer:['Study','English','.']},
    {id:'j2_8_8',  japanese:'ここで泳がないでください。',  answer:['Don\'t','swim','here','.']},
    {id:'j2_8_9',  japanese:'なんてかわいい赤ちゃんでしょう！',answer:['What','a','cute','baby','!']},
    {id:'j2_8_10', japanese:'友達と仲良くしなさい。',      answer:['Be','nice','to','your','friends','.']},
    {id:'j2_8_11', japanese:'なんて難しい問題でしょう！',  answer:['What','a','difficult','problem','!']},
  ],
  j2_9: [
    {id:'j2_9_1',  japanese:'彼女はどこに行くつもりですか。',answer:['Where','is','she','going','to','go','?']},
    {id:'j2_9_2',  japanese:'あなたはどのくらい英語を勉強しますか。',answer:['How','often','do','you','study','English','?']},
    {id:'j2_9_3',  japanese:'彼は何歳ですか。',            answer:['How','old','is','he','?']},
    {id:'j2_9_4',  japanese:'この橋はどのくらいの長さですか。',answer:['How','long','is','this','bridge','?']},
    {id:'j2_9_5',  japanese:'あなたはどうやって学校に来ますか。',answer:['How','do','you','come','to','school','?']},
    {id:'j2_9_6',  japanese:'あなたはサッカーが好きですよね。',answer:['You','like','soccer','don\'t','you','?']},
    {id:'j2_9_7',  japanese:'彼女はここの出身ですよね。',  answer:['She','is','from','here','isn\'t','she','?']},
    {id:'j2_9_8',  japanese:'あなたはどこに住んでいますか。',answer:['Where','do','you','live','?']},
    {id:'j2_9_9',  japanese:'彼はどのくらいの頻度で図書館に行きますか。',answer:['How','often','does','he','go','to','the','library','?']},
    {id:'j2_9_10', japanese:'この木はどのくらいの高さですか。',answer:['How','high','is','this','tree','?']},
    {id:'j2_9_11', japanese:'彼女はテニスが好きですよね。',answer:['She','likes','tennis','doesn\'t','she','?']},
    {id:'j2_9_12', japanese:'彼らはここの出身ではありませんよね。',answer:['They','are','not','from','here','?']},
  ],
  j2_10: [
    {id:'j2_10_1',  japanese:'私は英語を勉強したいです。', answer:['I','want','to','study','English','.']},
    {id:'j2_10_2',  japanese:'私の夢は医者になることです。',answer:['My','dream','is','to','become','a','doctor','.']},
    {id:'j2_10_3',  japanese:'私は音楽を聴くことが好きです。',answer:['I','like','listening','to','music','.']},
    {id:'j2_10_4',  japanese:'彼女はテニスをすることが好きです。',answer:['She','likes','playing','tennis','.']},
    {id:'j2_10_5',  japanese:'彼は英語を話すことができます。',answer:['He','can','speak','English','.']},
    {id:'j2_10_6',  japanese:'私は本屋に行きたいです。',   answer:['I','want','to','go','to','a','bookstore','.']},
    {id:'j2_10_7',  japanese:'彼女は料理をすることが好きです。',answer:['She','likes','cooking','.']},
    {id:'j2_10_8',  japanese:'私はサッカーをしたいです。', answer:['I','want','to','play','soccer','.']},
    {id:'j2_10_9',  japanese:'私の趣味は読書です。',       answer:['My','hobby','is','reading','books','.']},
    {id:'j2_10_10', japanese:'あなたは何をしたいですか。', answer:['What','do','you','want','to','do','?']},
    {id:'j2_10_11', japanese:'彼女は歌手になりたいです。', answer:['She','wants','to','become','a','singer','.']},
    {id:'j2_10_12', japanese:'私は水泳をすることが好きです。',answer:['I','like','swimming','.']},
    {id:'j2_10_13', japanese:'彼は料理をすることが上手です。',answer:['He','is','good','at','cooking','.']},
  ],
  j2_11: [
    {id:'j2_11_1',  japanese:'私は英語を勉強するために図書館に行きました。',answer:['I','went','to','the','library','to','study','English','.']},
    {id:'j2_11_2',  japanese:'彼女はケーキを買うためにお店に行きました。',answer:['She','went','to','the','shop','to','buy','a','cake','.']},
    {id:'j2_11_3',  japanese:'私はそのニュースを聞いて悲しかったです。',answer:['I','was','sad','to','hear','the','news','.']},
    {id:'j2_11_4',  japanese:'彼は友達に会えてうれしかったです。',answer:['He','was','glad','to','meet','his','friend','.']},
    {id:'j2_11_5',  japanese:'彼女はあなたに会えて驚きました。',answer:['She','was','surprised','to','meet','you','.']},
    {id:'j2_11_6',  japanese:'彼はピアノを練習するために早く起きました。',answer:['He','got','up','early','to','practice','the','piano','.']},
    {id:'j2_11_7',  japanese:'私は友達に会えてうれしかったです。',answer:['I','was','glad','to','meet','my','friend','.']},
    {id:'j2_11_8',  japanese:'彼女はそのニュースを聞いて悲しかったです。',answer:['She','was','sad','to','hear','the','news','.']},
    {id:'j2_11_9',  japanese:'彼らは英語を勉強するために学校に行きました。',answer:['They','went','to','school','to','study','English','.']},
    {id:'j2_11_10', japanese:'私は映画を見るために映画館に行きました。',answer:['I','went','to','the','theater','to','see','a','movie','.']},
  ],
  j2_12: [
    {id:'j2_12_1',  japanese:'私はすることがたくさんあります。',answer:['I','have','a','lot','of','things','to','do','.']},
    {id:'j2_12_2',  japanese:'彼女は読む本を持っています。',answer:['She','has','a','book','to','read','.']},
    {id:'j2_12_3',  japanese:'私は飲む水がほしいです。',   answer:['I','want','some','water','to','drink','.']},
    {id:'j2_12_4',  japanese:'彼は住む家を必要としています。',answer:['He','needs','a','house','to','live','in','.']},
    {id:'j2_12_5',  japanese:'私は書く紙がほしいです。',   answer:['I','want','some','paper','to','write','on','.']},
    {id:'j2_12_6',  japanese:'彼にはすることがたくさんあります。',answer:['He','has','a','lot','of','things','to','do','.']},
    {id:'j2_12_7',  japanese:'彼女は読む本を持っていません。',answer:['She','doesn\'t','have','a','book','to','read','.']},
    {id:'j2_12_8',  japanese:'私は書く紙がほしいです。',   answer:['I','want','some','paper','to','write','on','.']},
    {id:'j2_12_9',  japanese:'彼らは住む場所を探しています。',answer:['They','are','looking','for','a','place','to','live','in','.']},
    {id:'j2_12_10', japanese:'私には話す友達がいます。',   answer:['I','have','a','friend','to','talk','with','.']},
  ],
  j2_13: [
    {id:'j2_13_1',  japanese:'私は音楽を聴くことが好きです。',answer:['I','like','listening','to','music','.']},
    {id:'j2_13_2',  japanese:'彼女の趣味は料理をすることです。',answer:['Her','hobby','is','cooking','.']},
    {id:'j2_13_3',  japanese:'彼は野球をすることが得意です。',answer:['He','is','good','at','playing','baseball','.']},
    {id:'j2_13_4',  japanese:'私は歌うことが好きではありません。',answer:['I','don\'t','like','singing','.']},
    {id:'j2_13_5',  japanese:'彼女は泳ぐことをやめました。',answer:['She','stopped','swimming','.']},
    {id:'j2_13_6',  japanese:'ありがとうございました。',   answer:['Thank','you','for','calling','me','.']},
    {id:'j2_13_7',  japanese:'彼は宿題を終えました。',     answer:['He','finished','doing','his','homework','.']},
    {id:'j2_13_8',  japanese:'彼女は読書が好きです。',     answer:['She','likes','reading','books','.']},
    {id:'j2_13_9',  japanese:'私の趣味は写真を撮ることです。',answer:['My','hobby','is','taking','pictures','.']},
    {id:'j2_13_10', japanese:'彼は水泳が得意です。',       answer:['He','is','good','at','swimming','.']},
    {id:'j2_13_11', japanese:'彼女はテレビを見るのをやめました。',answer:['She','stopped','watching','TV','.']},
    {id:'j2_13_12', japanese:'彼らは音楽を聴くことが好きです。',answer:['They','like','listening','to','music','.']},
  ],
  j2_14: [
    {id:'j2_14_1',  japanese:'彼女は幸せそうに見えます。', answer:['She','looks','happy','.']},
    {id:'j2_14_2',  japanese:'彼は医者になりました。',     answer:['He','became','a','doctor','.']},
    {id:'j2_14_3',  japanese:'彼女は私に本をくれました。', answer:['She','gave','me','a','book','.']},
    {id:'j2_14_4',  japanese:'私は彼女に花を送りました。', answer:['I','sent','her','some','flowers','.']},
    {id:'j2_14_5',  japanese:'彼らは彼女をエミと呼びます。',answer:['They','call','her','Emi','.']},
    {id:'j2_14_6',  japanese:'彼はそのケーキをおいしいと思いました。',answer:['He','found','the','cake','delicious','.']},
    {id:'j2_14_7',  japanese:'彼は悲しそうに見えます。',   answer:['He','looks','sad','.']},
    {id:'j2_14_8',  japanese:'彼女は先生になりました。',   answer:['She','became','a','teacher','.']},
    {id:'j2_14_9',  japanese:'父は私に時計をくれました。', answer:['My','father','gave','me','a','watch','.']},
    {id:'j2_14_10', japanese:'私たちは彼をタロウと呼びます。',answer:['We','call','him','Taro','.']},
    {id:'j2_14_11', japanese:'彼女はその映画を面白いと思いました。',answer:['She','found','the','film','interesting','.']},
    {id:'j2_14_12', japanese:'彼は私に手紙を送りました。', answer:['He','sent','me','a','letter','.']},
  ],
  j2_15: [
    {id:'j2_15_1',  japanese:'英語を勉強することは大切です。',answer:['It','is','important','to','study','English','.']},
    {id:'j2_15_2',  japanese:'彼女に会うことはうれしいです。',answer:['It','is','nice','to','meet','her','.']},
    {id:'j2_15_3',  japanese:'ここで泳ぐことは危険です。', answer:['It','is','dangerous','to','swim','here','.']},
    {id:'j2_15_4',  japanese:'私はどこへ行けばよいかわかりません。',answer:['I','don\'t','know','where','to','go','.']},
    {id:'j2_15_5',  japanese:'彼女はいつ出発すればよいかわかりません。',answer:['She','doesn\'t','know','when','to','leave','.']},
    {id:'j2_15_6',  japanese:'彼はどうやって英語を勉強すればよいかわかりません。',answer:['He','doesn\'t','know','how','to','study','English','.']},
    {id:'j2_15_7',  japanese:'毎日運動することは健康によいです。',answer:['It','is','good','to','exercise','every','day','for','your','health','.']},
    {id:'j2_15_8',  japanese:'彼女に連絡する方法を教えてください。',answer:['Please','tell','me','how','to','contact','her','.']},
    {id:'j2_15_9',  japanese:'どこで買えばよいかわかりません。',answer:['I','don\'t','know','where','to','buy','it','.']},
    {id:'j2_15_10', japanese:'英語を上手に話すことは難しいです。',answer:['It','is','difficult','to','speak','English','well','.']},
  ],
  j2_16: [
    {id:'j2_16_1',  japanese:'私は英語が好きですが、数学は苦手です。',answer:['I','like','English','but','I','am','not','good','at','math','.']},
    {id:'j2_16_2',  japanese:'彼は歌うことと踊ることが好きです。',answer:['He','likes','singing','and','dancing','.']},
    {id:'j2_16_3',  japanese:'私が家に帰ったとき、母は料理をしていました。',answer:['When','I','came','home','my','mother','was','cooking','.']},
    {id:'j2_16_4',  japanese:'彼女は疲れていたので、早く寝ました。',answer:['She','went','to','bed','early','because','she','was','tired','.']},
    {id:'j2_16_5',  japanese:'私は彼が先生だと思います。',answer:['I','think','he','is','a','teacher','.']},
    {id:'j2_16_6',  japanese:'彼女はあした来ると言っていました。',answer:['She','said','that','she','would','come','tomorrow','.']},
    {id:'j2_16_7',  japanese:'彼は忙しいけれど、いつも楽しそうです。',answer:['He','is','busy','but','he','always','looks','happy','.']},
    {id:'j2_16_8',  japanese:'彼女は英語と数学が好きです。',answer:['She','likes','English','and','math','.']},
    {id:'j2_16_9',  japanese:'彼が来たとき、私は勉強していました。',answer:['When','he','came','I','was','studying','.']},
    {id:'j2_16_10', japanese:'私は彼女が正しいと思います。',answer:['I','think','she','is','correct','.']},
    {id:'j2_16_11', japanese:'彼は雨が降ったので家にいました。',answer:['He','stayed','home','because','it','rained','.']},
  ],
  j2_17: [
    {id:'j2_17_1',  japanese:'本は机の上にあります。',     answer:['The','book','is','on','the','desk','.']},
    {id:'j2_17_2',  japanese:'鉛筆は箱の中にあります。',   answer:['The','pencil','is','in','the','box','.']},
    {id:'j2_17_3',  japanese:'彼は朝に英語を勉強します。', answer:['He','studies','English','in','the','morning','.']},
    {id:'j2_17_4',  japanese:'私は月曜日にテニスをします。',answer:['I','play','tennis','on','Monday','.']},
    {id:'j2_17_5',  japanese:'彼女は7時に起きます。',      answer:['She','gets','up','at','seven','.']},
    {id:'j2_17_6',  japanese:'図書館は駅の前にあります。', answer:['The','library','is','in','front','of','the','station','.']},
    {id:'j2_17_7',  japanese:'ネコはソファの下にいます。', answer:['The','cat','is','under','the','sofa','.']},
    {id:'j2_17_8',  japanese:'彼は夜に音楽を聴きます。',   answer:['He','listens','to','music','at','night','.']},
    {id:'j2_17_9',  japanese:'花は机の上にあります。',     answer:['The','flowers','are','on','the','desk','.']},
    {id:'j2_17_10', japanese:'彼女は毎週土曜日にサッカーをします。',answer:['She','plays','soccer','on','every','Saturday','.']},
  ],
  j2_18: [
    {id:'j2_18_1',  japanese:'私はボブより若いです。',     answer:['I','am','younger','than','Bob','.']},
    {id:'j2_18_2',  japanese:'メアリーは久美より速く走ります。',answer:['Mary','runs','faster','than','Kumi','.']},
    {id:'j2_18_3',  japanese:'カナダは中国より広いです。', answer:['Canada','is','larger','than','China','.']},
    {id:'j2_18_4',  japanese:'私の母は父より早く起きます。',answer:['My','mother','gets','up','earlier','than','my','father','.']},
    {id:'j2_18_5',  japanese:'私の犬はこの犬より大きいです。',answer:['My','dog','is','bigger','than','this','one','.']},
    {id:'j2_18_6',  japanese:'このコンピュータは私のよりよいです。',answer:['This','computer','is','better','than','mine','.']},
    {id:'j2_18_7',  japanese:'私たちの学校は市内でいちばん古いです。',answer:['Our','school','is','the','oldest','in','our','city','.']},
    {id:'j2_18_8',  japanese:'富士山は日本でいちばん高い。',answer:['Mt.','Fuji','is','the','highest','in','Japan','.']},
    {id:'j2_18_9',  japanese:'あの公園はこの町でいちばん広い。',answer:['That','park','is','the','largest','in','this','town','.']},
    {id:'j2_18_10', japanese:'健は私たち全員の中でいちばん早く起きます。',answer:['Ken','gets','up','the','earliest','of','all','us','.']},
    {id:'j2_18_11', japanese:'彼は私より背が高いです。',   answer:['He','is','taller','than','me','.']},
    {id:'j2_18_12', japanese:'彼女は彼よりじょうずに歌います。',answer:['She','sings','better','than','him','.']},
    {id:'j2_18_13', japanese:'この本はあの本よりも面白いです。',answer:['This','book','is','more','interesting','than','that','one','.']},
    {id:'j2_18_14', japanese:'このりんごは3つの中でいちばん大きいです。',answer:['This','apple','is','the','biggest','of','the','three','.']},
    {id:'j2_18_15', japanese:'彼は私の学校でいちばん速く走れます。',answer:['He','runs','the','fastest','in','my','school','.']},
  ],
  j2_19: [
    {id:'j2_19_1',  japanese:'由美はマイクと同年です。',   answer:['Yumi','is','as','old','as','Mike','.']},
    {id:'j2_19_2',  japanese:'私はあなたほど忙しくありません。',answer:['I\'m','not','as','busy','as','you','.']},
    {id:'j2_19_3',  japanese:'私はトムの２倍の数の本を持っています。',answer:['I','have','twice','as','many','books','as','Tom','.']},
    {id:'j2_19_4',  japanese:'この映画はあの映画と同じくらいおもしろいです。',answer:['This','film','is','as','interesting','as','that','one','.']},
    {id:'j2_19_5',  japanese:'彼は私ほど速く走れません。', answer:['He','can\'t','run','as','fast','as','me','.']},
    {id:'j2_19_6',  japanese:'彼女は彼と同じくらいじょうずに歌います。',answer:['She','sings','as','well','as','him','.']},
    {id:'j2_19_7',  japanese:'この本はあの本ほどおもしろくありません。',answer:['This','book','is','not','as','interesting','as','that','one','.']},
    {id:'j2_19_8',  japanese:'彼は私の２倍の速さで走ります。',answer:['He','runs','twice','as','fast','as','I','.']},
  ],
  j2_20: [
    {id:'j2_20_1',  japanese:'あなたはサッカーと野球ではどちらが好きですか。',answer:['Which','do','you','like','better','soccer','or','baseball','?']},
    {id:'j2_20_2',  japanese:'あなたは英語と数学ではどちらが得意ですか。',answer:['Which','are','you','better','at','English','or','math','?']},
    {id:'j2_20_3',  japanese:'彼は私たちの中でいちばん背が高いです。',answer:['He','is','the','most','tall','of','us','.']},
    {id:'j2_20_4',  japanese:'由美はマイクと同年です。',   answer:['Yumi','is','as','old','as','Mike','.']},
    {id:'j2_20_5',  japanese:'私はあなたほど忙しくありません。',answer:['I\'m','not','as','busy','as','you','.']},
    {id:'j2_20_6',  japanese:'どちらの映画がおもしろいですか。',answer:['Which','film','is','more','interesting','?']},
    {id:'j2_20_7',  japanese:'彼女は家族の中でいちばん料理が上手です。',answer:['She','cooks','the','best','in','her','family','.']},
    {id:'j2_20_8',  japanese:'この問題は数学でいちばん難しいです。',answer:['This','problem','is','the','most','difficult','in','math','.']},
  ],
  j2_21: [
    {id:'j2_21_1',  japanese:'この本は多くの子どもたちに読まれています。',answer:['This','book','is','read','by','many','children','.']},
    {id:'j2_21_2',  japanese:'英語はアメリカで話されています。',answer:['English','is','spoken','in','America','.']},
    {id:'j2_21_3',  japanese:'この歌は世界中で歌われています。',answer:['This','song','is','sung','all','over','the','world','.']},
    {id:'j2_21_4',  japanese:'この写真はトムによって撮られました。',answer:['This','photo','was','taken','by','Tom','.']},
    {id:'j2_21_5',  japanese:'この箱は木で作られています。',answer:['This','box','is','made','of','wood','.']},
    {id:'j2_21_6',  japanese:'この建物は１００年前に建てられました。',answer:['This','building','was','built','100','years','ago','.']},
    {id:'j2_21_7',  japanese:'この本はケンによって書かれました。',answer:['This','book','was','written','by','Ken','.']},
    {id:'j2_21_8',  japanese:'日本語はここで話されています。',answer:['Japanese','is','spoken','here','.']},
    {id:'j2_21_9',  japanese:'この歌は多くの人々に愛されています。',answer:['This','song','is','loved','by','many','people','.']},
    {id:'j2_21_10', japanese:'この建物は50年前に建てられました。',answer:['This','building','was','built','50','years','ago','.']},
    {id:'j2_21_11', japanese:'この写真は私の父によって撮られました。',answer:['This','photo','was','taken','by','my','father','.']},
  ],
  j2_22: [
    {id:'j2_22_1',  japanese:'この部屋は毎日掃除されます。',answer:['This','room','is','cleaned','every','day','.']},
    {id:'j2_22_2',  japanese:'これらの機械は彼によって使われていません。',answer:['These','machines','are','not','used','by','him','.']},
    {id:'j2_22_3',  japanese:'この本はどこで売られていますか。',answer:['Where','is','this','book','sold','?']},
    {id:'j2_22_4',  japanese:'この写真はいつ撮られましたか。',answer:['When','was','this','photo','taken','?']},
    {id:'j2_22_5',  japanese:'その知らせにだれもが驚きました。',answer:['Everyone','was','surprised','at','the','news','.']},
    {id:'j2_22_6',  japanese:'昨年は何台の車が売れましたか。',answer:['How','many','cars','were','sold','last','year','?']},
    {id:'j2_22_7',  japanese:'この机は木で作られています。',answer:['This','desk','is','made','of','wood','.']},
    {id:'j2_22_8',  japanese:'この部屋はきれいに掃除されましたか。',answer:['Is','this','room','cleaned','neatly','?']},
    {id:'j2_22_9',  japanese:'この窓はだれによって割られましたか。',answer:['Who','is','this','window','broken','by','?']},
    {id:'j2_22_10', japanese:'この本は多くの国で読まれています。',answer:['This','book','is','read','in','many','countries','.']},
    {id:'j2_22_11', japanese:'その建物は地震で壊されました。',answer:['The','building','was','destroyed','by','the','earthquake','.']},
  ],
}
