// 中学3年 全問題データ
// （中1・中2と同様のデータ形式）
export const QUESTIONS_J3 = {
  j3_1: [
    {id:'j3_1_1', japanese:'私は日本から来ました。', answer:['I','am','from','Japan','.']},
    {id:'j3_1_2', japanese:'ケンと私はよい友達です。', answer:['Ken','and','I','are','good','friends','.']},
    {id:'j3_1_3', japanese:'私のイヌたちは２日前に病気でした。', answer:['My','dogs','were','sick','two','days','ago','.']},
    {id:'j3_1_4', japanese:'ケンは先週大阪にいませんでした。', answer:['Ken','was','not','in','Osaka','last','week','.']},
    {id:'j3_1_5', japanese:'彼女はきのう忙しかったですか。', answer:['Was','she','busy','yesterday','?']},
    {id:'j3_1_6', japanese:'私は神戸に住んでいます。', answer:['I','live','in','Kobe','.']},
    {id:'j3_1_7', japanese:'彼は英語をじょうずに話します。', answer:['He','speaks','English','well','.']},
    {id:'j3_1_8', japanese:'私の母は２台の車を持っています。', answer:['My','mother','has','two','cars','.']},
    {id:'j3_1_9', japanese:'私たちは先週、京都を訪れました。', answer:['We','visited','Kyoto','last','week','.']},
    {id:'j3_1_10', japanese:'私の弟はピアノを弾けません。', answer:['My','brother','cannot','play','the','piano','.']},
    {id:'j3_1_11', japanese:'彼らはきのう、数学を勉強しませんでした。', answer:['They','did','not','study','math','yesterday','.']},
    {id:'j3_1_12', japanese:'あなたは妹の宿題を手伝いましたか。', answer:['Did','you','help','your','sister','with','homework','?']},
    {id:'j3_1_13', japanese:'お父さんは今、コンピュータを使っています。', answer:['My','father','is','using','a','computer','.']},
    {id:'j3_1_14', japanese:'テーブルの下に２ひきのネコがいます。', answer:['There','are','two','cats','under','the','table','.']},
    {id:'j3_1_15', japanese:'あなたの町には図書館がありますか。', answer:['Are','there','any','libraries','in','your','town','?']},
    {id:'j3_1_16', japanese:'バスの中には何人の女の子がいますか。', answer:['How','many','girls','are','there','in','the','bus','?']},
    {id:'j3_1_17', japanese:'私たちは今とても忙しいです。', answer:['We','are','very','busy','now','.']},
    {id:'j3_1_18', japanese:'きのうは雨でした。', answer:['It','was','rainy','yesterday','.']},
    {id:'j3_1_19', japanese:'私は昨夜英語を勉強しました。', answer:['I','studied','English','last','night','.']},
    {id:'j3_1_20', japanese:'私たちは先週の土曜日にパーティーを開きました。', answer:['We','had','a','party','last','Saturday','.']},
    {id:'j3_1_21', japanese:'おじが２年前にこの自転車をくれました。', answer:['My','uncle','gave','me','this','bike','two','years','ago','.']},
    {id:'j3_1_22', japanese:'私はきのう友人に手紙を書きました。', answer:['I','wrote','a','letter','to','my','friend','yesterday','.']},
    {id:'j3_1_23', japanese:'彼らはお昼ご飯を作って食べました。', answer:['They','made','lunch','and','ate','it','.']},
    {id:'j3_1_24', japanese:'私の兄は土曜日はたいてい家にいます。', answer:['My','brother','usually','stays','at','home','on','Saturdays','.']},
    {id:'j3_1_25', japanese:'その動物園にはトラが何頭いますか。', answer:['How','many','tigers','are','there','in','the','zoo','?']},
    {id:'j3_1_26', japanese:'ヨーコは学校へ歩いているとき、イヌを見ました。', answer:['Yoko','saw','a','dog','when','she','was','going','to','school','.']},
    {id:'j3_1_27', japanese:'ケンは床につく前に本を読みます。', answer:['Ken','reads','a','book','before','he','goes','to','bed','.']},
    {id:'j3_1_28', japanese:'ブラウン氏は英語を教えてくれます。', answer:['Mr.','Brown','teaches','us','English','.']},
    {id:'j3_1_29', japanese:'彼女は通りを歩いているとき、かわいい犬を見ました。', answer:['When','she','was','walking','on','the','street','she','saw','a','pretty','dog','.']},
    {id:'j3_1_30', japanese:'私は15歳で、妹は17歳です。', answer:['I','am','fifteen','years','old','and','my','sister','is','seventeen','.']},
    {id:'j3_1_31', japanese:'ここから駅までバスでどれくらいかかりますか。', answer:['How','long','does','it','take','from','here','to','the','station','by','bus','?']},
    {id:'j3_1_32', japanese:'切符が機械から出てきませんでした。', answer:['The','ticket','didn\'t','come','out','of','the','machine','.']},
    {id:'j3_1_33', japanese:'あなたの誕生日はいつですか。', answer:['When','is','your','birthday','?']},
    {id:'j3_1_34', japanese:'山田先生はその絵を見て立ち止まりました。', answer:['Ms.','Yamada','stopped','and','looked','at','the','picture','.']},
    {id:'j3_1_35', japanese:'私たちは今とても忙しいです。', answer:['We','are','very','busy','now','.']},
    {id:'j3_1_36', japanese:'父のカメラは日本で作られました。', answer:['My','father\'s','camera','was','made','in','Japan','.']},
    {id:'j3_1_37', japanese:'お父さんは昨夜疲れていました。', answer:['My','father','was','tired','last','night','.']},
    {id:'j3_1_38', japanese:'トムと私は２時間前に公園にいました。', answer:['Tom','and','I','were','in','the','park','two','hours','ago','.']},
    {id:'j3_1_39', japanese:'お父さんはきのう散歩をしました。', answer:['My','father','took','a','walk','yesterday','.']},
    {id:'j3_1_40', japanese:'彼女はさようならと言って部屋を出ました。', answer:['She','said','goodbye','and','left','the','room','.']},
    {id:'j3_1_41', japanese:'ユキは先週誕生日プレゼントをもらいました。', answer:['Yuki','got','a','birthday','present','last','week','.']},
    {id:'j3_1_42', japanese:'私は昨夜英語を勉強しました。', answer:['I','studied','English','last','night','.']},
    {id:'j3_1_43', japanese:'彼はこれらは正しいと主張しました。', answer:['He','argued','that','these','were','correct','.']},
  ],
  j3_2: [
    {id:'j3_2_1', japanese:'私は来週サッカーをするつもりです。', answer:['I','will','play','soccer','next','week','.']},
    {id:'j3_2_2', japanese:'スミスさんはあした日本を出発するでしょう。', answer:['Mr.','Smith','will','leave','Japan','tomorrow','.']},
    {id:'j3_2_3', japanese:'健は今度の日曜日はひまでしょう。', answer:['Ken','will','be','free','next','Sunday','.']},
    {id:'j3_2_4', japanese:'この箱を開けてくれませんか。', answer:['Will','you','open','this','box','?']},
    {id:'j3_2_5', japanese:'ユキはあした早起きをしないでしょう。', answer:['Yuki','will','not','get','up','early','tomorrow','.']},
    {id:'j3_2_6', japanese:'彼らは来年ロンドンを訪れるでしょうか。', answer:['Will','they','visit','London','next','year','?']},
    {id:'j3_2_7', japanese:'あすは雨が降らないでしょう。', answer:['It','will','not','rain','tomorrow','.']},
    {id:'j3_2_8', japanese:'試合は何時に始まりますか。', answer:['What','time','will','the','game','start','?']},
    {id:'j3_2_9', japanese:'私たちは彼をパーティーに招くつもりです。', answer:['We','are','going','to','invite','him','to','the','party','.']},
    {id:'j3_2_10', japanese:'私の母はあしたテニスをするつもりです。', answer:['My','mother','is','going','to','play','tennis','tomorrow','.']},
    {id:'j3_2_11', japanese:'私の父は来週、新しい車を買います。', answer:['My','father','will','buy','a','new','car','next','week','.']},
    {id:'j3_2_12', japanese:'トムはこのコンピュータを使うつもりです。', answer:['Tom','is','going','to','use','this','computer','.']},
    {id:'j3_2_13', japanese:'あなたはパーティーで楽しく過ごすでしょう。', answer:['You','will','have','a','good','time','at','the','party','.']},
    {id:'j3_2_14', japanese:'あすは東京では雪が降らないでしょう。', answer:['It','will','not','snow','in','Tokyo','tomorrow','.']},
    {id:'j3_2_15', japanese:'由紀は今夜彼に電話をかけるでしょうか。', answer:['Will','Yuki','call','him','this','evening','?']},
    {id:'j3_2_16', japanese:'彼女はあした朝食を作るつもりです。', answer:['She','is','going','to','make','breakfast','tomorrow','morning','.']},
    {id:'j3_2_17', japanese:'あなたはそこで写真を撮るつもりですか。', answer:['Are','you','going','to','take','pictures','there','?']},
    {id:'j3_2_18', japanese:'私は今晩、外出するつもりはありません。', answer:['I','am','not','going','to','go','out','this','evening','.']},
    {id:'j3_2_19', japanese:'あしたは寒くならないでしょう。', answer:['It','will','not','be','cold','tomorrow','.']},
    {id:'j3_2_20', japanese:'私はあなたのことばを忘れないでしょう。', answer:['I','will','never','forget','your','words','.']},
    {id:'j3_2_21', japanese:'健は母親に何を買うつもりですか。', answer:['What','is','Ken','going','to','buy','for','his','mother','?']},
    {id:'j3_2_22', japanese:'あなたはあした何時にトムを訪ねるつもりですか。', answer:['What','time','are','you','going','to','visit','Tom','tomorrow','?']},
    {id:'j3_2_23', japanese:'グリーン先生は何時に学校に来ますか。', answer:['What','time','will','Ms.','Green','come','to','school','?']},
    {id:'j3_2_24', japanese:'どのくらいしたら出発の準備ができますか。', answer:['How','soon','will','you','be','ready','to','start','?']},
    {id:'j3_2_25', japanese:'私はあの楽しい日々を決して忘れません。', answer:['I','will','never','forget','those','happy','days','.']},
    {id:'j3_2_26', japanese:'彼らは今年の夏に山に登るつもりですか。', answer:['Are','they','going','to','climb','the','mountain','this','summer','?']},
    {id:'j3_2_27', japanese:'子どもたちはテレビでサッカーの試合を見るつもりです。', answer:['The','children','are','going','to','watch','soccer','game','on','TV','.']},
    {id:'j3_2_28', japanese:'彼はきょうの午後、犬を散歩に連れて行くつもりです。', answer:['He','is','going','to','take','his','dog','for','a','walk','this','afternoon','.']},
    {id:'j3_2_29', japanese:'私はあした、おじさんに会うつもりです。', answer:['I','am','going','to','see','my','uncle','tomorrow','.']},
    {id:'j3_2_30', japanese:'私たちはそこで英語の歌を歌うつもりです。', answer:['We','are','going','to','sing','English','songs','there','.']},
    {id:'j3_2_31', japanese:'今晩、ピアノの練習をするつもりはありません。', answer:['I','am','not','going','to','practice','the','piano','this','evening','.']},
    {id:'j3_2_32', japanese:'あなたはこの手紙を彼女に送るつもりですか。', answer:['Are','you','going','to','send','this','letter','to','her','?']},
  ],
  j3_3: [
    {id:'j3_3_1', japanese:'私は英語をじょうずに話すことができます。', answer:['I','can','speak','English','well','.']},
    {id:'j3_3_2', japanese:'トムはとても速く泳ぐことができますか。', answer:['Can','Tom','swim','very','fast','?']},
    {id:'j3_3_3', japanese:'お父さんは車を運転できません。', answer:['My','father','cannot','drive','a','car','.']},
    {id:'j3_3_4', japanese:'あなたの辞書を使ってもいいですか。', answer:['May','I','use','your','dictionary','?']},
    {id:'j3_3_5', japanese:'この箱を運んでくれませんか。', answer:['Will','you','carry','this','box','?']},
    {id:'j3_3_6', japanese:'今、テレビを見てもいいですか。', answer:['May','I','watch','TV','now','?']},
    {id:'j3_3_7', japanese:'あしたは雨かもしれません。', answer:['It','may','be','rainy','tomorrow','.']},
    {id:'j3_3_8', japanese:'このコンピュータを使ってもいいですよ。', answer:['You','can','use','this','computer','.']},
    {id:'j3_3_9', japanese:'彼は新入生かもしれません。', answer:['He','may','be','a','new','student','.']},
    {id:'j3_3_10', japanese:'あなたは早く寝るべきです。', answer:['You','should','go','to','bed','early','.']},
    {id:'j3_3_11', japanese:'私は沖縄をまた訪れたいものです。', answer:['I','would','like','to','visit','Okinawa','again','.']},
    {id:'j3_3_12', japanese:'お茶はいかがですか。', answer:['Would','you','like','some','tea','?']},
    {id:'j3_3_13', japanese:'私にその辞書を貸していただけませんか。', answer:['Could','you','lend','me','the','dictionary','?']},
    {id:'j3_3_14', japanese:'あなたはうそをついてはいけません。', answer:['You','should','not','tell','a','lie','.']},
    {id:'j3_3_15', japanese:'私は彼を家に招待したいと思っています。', answer:['I','would','like','to','invite','him','to','my','house','.']},
    {id:'j3_3_16', japanese:'私はいつかあなたの国を訪れてみたいです。', answer:['I','would','like','to','visit','your','country','some','day','.']},
    {id:'j3_3_17', japanese:'私たちはその子どもたちのために何かするべきです。', answer:['We','should','do','something','for','the','children','.']},
    {id:'j3_3_18', japanese:'あなたたちはまたそれらの動物を見ることができるでしょう。', answer:['You','will','be','able','to','see','those','animals','again','.']},
    {id:'j3_3_19', japanese:'何か飲み物はいかがですか。', answer:['Would','you','like','something','to','drink','?']},
    {id:'j3_3_20', japanese:'あなたの電話番号を教えてくれませんか。', answer:['Will','you','tell','me','your','phone','number','?']},
    {id:'j3_3_21', japanese:'私が彼女の子どもを探さなくてはいけないのですか。', answer:['Must','I','look','for','her','child','?']},
    {id:'j3_3_22', japanese:'あなたのお母さんは毎朝早く起きなければなりませんか。', answer:['Does','your','mother','have','to','get','up','early','every','morning','?']},
    {id:'j3_3_23', japanese:'行きたくなければ、行かなくてもいいですよ。', answer:['If','you','don\'t','want','to','go','you','don\'t','have','to','go','.']},
    {id:'j3_3_24', japanese:'あなたはお母さんのピアノが弾けますか。', answer:['Is','your','mother','able','to','play','the','piano','?']},
  ],
  j3_4: [
    {id:'j3_4_1', japanese:'父は病気になりました。', answer:['My','father','got','sick','.']},
    {id:'j3_4_2', japanese:'娘は私に美しい花をくれました。', answer:['My','daughter','gave','me','some','beautiful','flowers','.']},
    {id:'j3_4_3', japanese:'だれが壁を白く塗りましたか。', answer:['Who','painted','the','wall','white','?']},
    {id:'j3_4_4', japanese:'トムは川でたくさんの魚を捕まえました。', answer:['Tom','caught','a','lot','of','fish','in','the','river','.']},
    {id:'j3_4_5', japanese:'試合に勝ったあと、彼女はとても疲れたように感じました。', answer:['She','felt','very','tired','after','she','won','the','game','.']},
    {id:'j3_4_6', japanese:'そのケーキは食べてみると、とてもおいしかったです。', answer:['I','found','the','cake','delicious','.']},
    {id:'j3_4_7', japanese:'車は私たちの生活をよくし、楽しいものにします。', answer:['Cars','make','our','lives','good','and','happy','.']},
    {id:'j3_4_8', japanese:'彼女はなんてじょうずにピアノを弾くのでしょう。', answer:['How','well','she','plays','the','piano','!']},
    {id:'j3_4_9', japanese:'あなたがこの学校の生徒であることを示してください。', answer:['Please','show','us','you','are','a','student','in','this','school','.']},
    {id:'j3_4_10', japanese:'あなたたちはとても幸せに見えますよ。', answer:['You','look','very','happy','.']},
  ],
  j3_5: [
    {id:'j3_5_1', japanese:'このペンはトムによって使われています。', answer:['This','pen','is','used','by','Tom','.']},
    {id:'j3_5_2', japanese:'この公園ではたくさんの鳥が見られます。', answer:['Many','birds','are','seen','in','this','park','.']},
    {id:'j3_5_3', japanese:'父のカメラは日本で作られました。', answer:['My','father\'s','camera','was','made','in','Japan','.']},
    {id:'j3_5_4', japanese:'その仕事は健によってなされなければなりません。', answer:['The','job','must','be','done','by','Ken','.']},
    {id:'j3_5_5', japanese:'このお人形はその店で売られています。', answer:['This','doll','is','sold','at','the','shop','.']},
    {id:'j3_5_6', japanese:'彼のかばんは部屋の中で見つかりました。', answer:['His','bag','was','found','in','the','room','.']},
    {id:'j3_5_7', japanese:'この部屋はジェーンによって掃除されましたか。', answer:['Was','this','room','cleaned','by','Jane','?']},
    {id:'j3_5_8', japanese:'チーズは牛乳から作られます。', answer:['Cheese','is','made','from','milk','.']},
    {id:'j3_5_9', japanese:'ジムは日本の歴史に興味があります。', answer:['Jim','is','interested','in','Japanese','history','.']},
    {id:'j3_5_10', japanese:'その山は雪でおおわれています。', answer:['The','mountain','is','covered','with','snow','.']},
    {id:'j3_5_11', japanese:'コップは水でいっぱいです。', answer:['The','glass','is','filled','with','water','.']},
    {id:'j3_5_12', japanese:'その知らせにだれもが驚きました。', answer:['Everyone','was','surprised','at','the','news','.']},
    {id:'j3_5_13', japanese:'昨年は何台の車が売れましたか。', answer:['How','many','cars','were','sold','last','year','?']},
    {id:'j3_5_14', japanese:'これらの機械は彼が発明したものではありません。', answer:['These','machines','were','not','invented','by','him','.']},
    {id:'j3_5_15', japanese:'彼の本は世界の多くの人に読まれています。', answer:['His','books','are','read','by','many','people','in','the','world','.']},
    {id:'j3_5_16', japanese:'新しい本屋にはよい本がありませんでした。', answer:['No','good','books','were','found','at','the','new','bookstore','.']},
  ],
  j3_6: [
    {id:'j3_6_1', japanese:'私たちは数回その都市を訪れたことがあります。', answer:['We','have','visited','the','city','several','times','.']},
    {id:'j3_6_2', japanese:'健はその本を一度読んだことがあります。', answer:['Ken','has','read','the','book','once','.']},
    {id:'j3_6_3', japanese:'私は以前その少女に会ったことがあります。', answer:['I','have','met','the','girl','before','.']},
    {id:'j3_6_4', japanese:'彼は以前ここでテニスをしたことがあります。', answer:['He','has','played','tennis','here','before','.']},
    {id:'j3_6_5', japanese:'私はこのコンピュータを何度も使ったことがあります。', answer:['I','have','used','this','computer','many','times','.']},
    {id:'j3_6_6', japanese:'私たちは以前広島を訪れたことがあります。', answer:['We','have','visited','Hiroshima','before','.']},
    {id:'j3_6_7', japanese:'私はこの本を一度も読んだことがありません。', answer:['I','have','never','read','this','book','.']},
    {id:'j3_6_8', japanese:'あなたは今までにエミに会ったことがありますか。', answer:['Have','you','ever','met','Emi','?']},
    {id:'j3_6_9', japanese:'私は一度も富士山に登ったことがありません。', answer:['I','have','never','climbed','Mt.','Fuji','.']},
    {id:'j3_6_10', japanese:'あなたは韓国の歴史についての本を読んだことがありますか。', answer:['Have','you','ever','read','a','book','about','Korean','history','?']},
    {id:'j3_6_11', japanese:'このような暑い夏は私には初めてです。', answer:['I','have','never','had','such','a','hot','summer','.']},
    {id:'j3_6_12', japanese:'これまでにその川の写真を撮ったことがありますか。', answer:['Have','you','ever','taken','a','picture','of','the','river','?']},
    {id:'j3_6_13', japanese:'私はおじに会うためにロンドンに行ったことがあります。', answer:['I','have','been','to','London','to','see','my','uncle','.']},
    {id:'j3_6_14', japanese:'私は以前富士山の写真を撮ったことがあります。', answer:['I','have','taken','a','picture','of','Mt.','Fuji','before','.']},
    {id:'j3_6_15', japanese:'ジェーンはその店で２度本を買ったことがあります。', answer:['Jane','has','bought','books','at','the','shop','twice','.']},
    {id:'j3_6_16', japanese:'あなたは今年になってその都市を何度訪ねましたか。', answer:['How','often','have','you','visited','the','city','this','year','?']},
  ],
  j3_7: [
    {id:'j3_7_1', japanese:'私はちょうど昼食を食べ終えたところです。', answer:['I','have','just','eaten','lunch','.']},
    {id:'j3_7_2', japanese:'私たちはちょうど宿題を終えたところです。', answer:['We','have','just','finished','our','homework','.']},
    {id:'j3_7_3', japanese:'彼は手紙を読みましたか。', answer:['Has','he','read','the','letter','?']},
    {id:'j3_7_4', japanese:'あなたはもうご飯を食べましたか。', answer:['Have','you','had','breakfast','yet','?']},
    {id:'j3_7_5', japanese:'ヨーコはフランスへ行ってしまいました。', answer:['Yoko','has','gone','to','France','.']},
    {id:'j3_7_6', japanese:'サラはルームキーをなくしてしまいました。', answer:['Sarah','has','lost','her','room','key','.']},
    {id:'j3_7_7', japanese:'お父さんはちょうど空港へ戻ってきたところです。', answer:['My','father','has','just','returned','to','the','airport','.']},
    {id:'j3_7_8', japanese:'私たちの子どもは、もうそのニュースを聞いてしまいました。', answer:['The','children','have','already','heard','the','news','.']},
    {id:'j3_7_9', japanese:'あなたは、もうその家を売ってしまいましたか。', answer:['Have','you','sold','the','house','yet','?']},
    {id:'j3_7_10', japanese:'彼女の妹はロンドンに行ってしまいました。', answer:['Her','sister','has','gone','to','London','.']},
    {id:'j3_7_11', japanese:'父は、ちょうどその絵を描き終えたところです。', answer:['My','father','has','just','finished','painting','the','picture','.']},
  ],
  j3_8: [
    {id:'j3_8_1', japanese:'私たちはここに３週間滞在しています。', answer:['We','have','been','here','for','three','weeks','.']},
    {id:'j3_8_2', japanese:'私の両親は先週からずっと忙しいです。', answer:['My','parents','have','been','busy','since','last','week','.']},
    {id:'j3_8_3', japanese:'彼のお姉さんは18年間ずっとオーストラリアに住んでいます。', answer:['His','sister','has','been','in','Australia','for','eighteen','years','.']},
    {id:'j3_8_4', japanese:'私たちはトムと知り合って5年になります。', answer:['We','have','known','Tom','for','five','years','.']},
    {id:'j3_8_5', japanese:'彼女は２年前からずっとテニスを練習しています。', answer:['She','has','been','practicing','tennis','for','two','years','.']},
    {id:'j3_8_6', japanese:'私の父は去年の夏からずっと入院しています。', answer:['My','father','has','been','in','the','hospital','since','last','summer','.']},
    {id:'j3_8_7', japanese:'私は彼女と知り合ってから４年になります。', answer:['I','have','known','her','for','four','years','.']},
    {id:'j3_8_8', japanese:'私の妹は30分ずっと電話で話しています。', answer:['My','sister','has','been','talking','on','the','phone','for','thirty','minutes','.']},
    {id:'j3_8_9', japanese:'彼は昨夜からずっと眠っているのですか。', answer:['Has','he','been','sleeping','since','last','night','?']},
    {id:'j3_8_10', japanese:'あなたたちはロンドンに住んでどれくらいになるのですか。', answer:['How','long','have','you','lived','in','London','?']},
  ],
  j3_9: [
    {id:'j3_9_1', japanese:'私はきょうの午後、することがたくさんあります。', answer:['I','have','many','things','to','do','this','afternoon','.']},
    {id:'j3_9_2', japanese:'ボブは始発電車に乗るため、家を早く出ました。', answer:['Bob','left','home','early','to','catch','the','first','train','.']},
    {id:'j3_9_3', japanese:'私はそのニュースを聞いて悲しかったです。', answer:['I','was','sad','to','hear','the','news','.']},
    {id:'j3_9_4', japanese:'私は本を読みに図書館へ行きました。', answer:['I','went','to','the','library','to','read','books','.']},
    {id:'j3_9_5', japanese:'彼はおじさんに会うためにニューヨークへ行きました。', answer:['He','went','to','New','York','to','see','his','uncle','.']},
    {id:'j3_9_6', japanese:'私はあなたに言うことがあるのです。', answer:['I','have','something','to','say','to','you','.']},
    {id:'j3_9_7', japanese:'彼が、その山を登った最初の日本人でした。', answer:['He','was','the','first','Japanese','to','climb','that','mountain','.']},
    {id:'j3_9_8', japanese:'友だちとおしゃべりしているひまはありませんよ。', answer:['You','have','no','time','to','talk','with','your','friends','.']},
    {id:'j3_9_9', japanese:'何かおもしろい読み物を貸してくれませんか。', answer:['Will','you','lend','me','something','interesting','to','read','?']},
    {id:'j3_9_10', japanese:'何か温かいものを飲みませんか。', answer:['Could','you','give','me','something','hot','to','drink','?']},
    {id:'j3_9_11', japanese:'英語を勉強するのによい辞書を探しています。', answer:['I\'m','looking','for','a','good','dictionary','to','study','English','with','.']},
    {id:'j3_9_12', japanese:'ベビーシッティングは小さな子どもの面倒をみる仕事です。', answer:['Baby-sitting','is','a','job','to','take','care','of','small','children','.']},
  ],
  j3_10: [
    {id:'j3_10_1', japanese:'忙しすぎて、お会いできません。', answer:['I','am','too','busy','to','see','you','.']},
    {id:'j3_10_2', japanese:'彼は親切に私に踊り方を教えてくれました。', answer:['He','was','kind','enough','to','show','me','how','to','dance','.']},
    {id:'j3_10_3', japanese:'その子どもにとって静かにしているのは困難なことでした。', answer:['It','was','difficult','for','the','child','to','keep','quiet','.']},
    {id:'j3_10_4', japanese:'彼は彼女に何の花を買えばいいかわかりませんでした。', answer:['He','didn\'t','know','what','flowers','to','buy','for','her','.']},
    {id:'j3_10_5', japanese:'この質問は難しすぎて私には答えられません。', answer:['This','question','is','too','difficult','for','me','to','answer','.']},
    {id:'j3_10_6', japanese:'あなたはいつ夕食を作り始めたらいいか知っていますか。', answer:['Do','you','know','when','to','start','making','dinner','?']},
    {id:'j3_10_7', japanese:'健は親切にも私の宿題を手伝ってくれました。', answer:['Ken','was','kind','enough','to','help','me','with','my','homework','.']},
    {id:'j3_10_8', japanese:'どこで手を洗ったらいいか教えていただけませんか。', answer:['Would','you','tell','me','where','to','wash','my','hands','?']},
    {id:'j3_10_9', japanese:'それらの子どもたちにとって海で泳ぐことは難しくありませんでした。', answer:['It','wasn\'t','difficult','for','those','children','to','swim','in','the','sea','.']},
  ],
  j3_11: [
    {id:'j3_11_1', japanese:'母は私に台所でお皿を洗うように頼みました。', answer:['Mother','asked','me','to','wash','the','dishes','in','the','kitchen','.']},
    {id:'j3_11_2', japanese:'その歌を聞くといつも私は幸せな気分になります。', answer:['The','song','always','makes','me','feel','happy','.']},
    {id:'j3_11_3', japanese:'お母さんが帰宅したら、あなたに知らせます。', answer:['When','my','mother','comes','home','I\'ll','let','you','know','.']},
    {id:'j3_11_4', japanese:'トムに30分待ってもらえますか。', answer:['Will','you','ask','Tom','to','wait','for','thirty','minutes','?']},
    {id:'j3_11_5', japanese:'子どもたちにこの公園で野球をさせないでください。', answer:['Don\'t','let','your','children','play','baseball','in','this','park','.']},
    {id:'j3_11_6', japanese:'美佳は私たちが教室のそうじをするのを手伝ってくれるでしょう。', answer:['Mika','will','help','us','clean','the','classrooms','.']},
    {id:'j3_11_7', japanese:'彼女は自分の宿題を終わらせるのを妹に手伝ってもらいました。', answer:['She','had','her','sister','help','finish','her','homework','.']},
    {id:'j3_11_8', japanese:'きみはお兄さんに、いっしょに大阪に行ってもらいたいですか。', answer:['Does','your','brother','want','to','go','to','Osaka','with','you','?']},
  ],
  j3_12: [
    {id:'j3_12_1', japanese:'それは雨が降りやみました。', answer:['It','stopped','raining','.']},
    {id:'j3_12_2', japanese:'母は音楽を聴いて楽しみました。', answer:['My','mother','enjoyed','listening','to','music','.']},
    {id:'j3_12_3', japanese:'先週電話してくれてありがとう。', answer:['Thank','you','for','calling','me','last','week','.']},
    {id:'j3_12_4', japanese:'あなたはそれを書き終えましたか。', answer:['Have','you','finished','writing','it','?']},
    {id:'j3_12_5', japanese:'私の趣味は友達とテニスをすることです。', answer:['My','hobby','is','playing','tennis','with','my','friends','.']},
    {id:'j3_12_6', japanese:'彼女は私を見ないで部屋を出て行きました。', answer:['She','left','the','room','without','looking','at','me','.']},
    {id:'j3_12_7', japanese:'私は野球を見ることに興味があります。', answer:['I\'m','interested','in','watching','baseball','.']},
    {id:'j3_12_8', japanese:'きょう映画を見に行きませんか。', answer:['How','about','going','to','the','movies','today','?']},
    {id:'j3_12_9', japanese:'英語を話すことを恐がってはいけません。', answer:['Don\'t','be','afraid','of','speaking','English','.']},
    {id:'j3_12_10', japanese:'宿題を終えずにテレビゲームをしてはいけません。', answer:['You','can\'t','play','the','video','game','before','finishing','your','homework','.']},
    {id:'j3_12_11', japanese:'父はちょうどその本を読み終えたところです。', answer:['My','father','has','just','finished','reading','the','book','.']},
    {id:'j3_12_12', japanese:'彼と話すことによって、私は彼を理解することができました。', answer:['By','talking','with','him','I','was','able','to','understand','him','.']},
    {id:'j3_12_13', japanese:'トモ子は先週、友人たちとスキーをして楽しみました。', answer:['Tomoko','enjoyed','skiing','with','her','friends','last','week','.']},
    {id:'j3_12_14', japanese:'コンピュータゲームをすることは、子どもたちにとって楽しいことです。', answer:['Playing','computer','games','is','fun','for','children','.']},
  ],
  j3_13: [
    {id:'j3_13_1', japanese:'これはスーザンによって書かれた手紙です。', answer:['This','is','the','letter','written','by','Susan','.']},
    {id:'j3_13_2', japanese:'カメラは日本で作られたものがよいです。', answer:['Cameras','made','in','Japan','are','good','.']},
    {id:'j3_13_3', japanese:'長い髪をした少女は私の友達です。', answer:['The','girl','with','long','hair','is','my','friend','.']},
    {id:'j3_13_4', japanese:'この国で話されている言語はフランス語です。', answer:['The','language','spoken','in','this','country','is','French','.']},
    {id:'j3_13_5', japanese:'庭で写真を撮っている男性は父です。', answer:['The','man','taking','pictures','in','the','garden','is','my','father','.']},
    {id:'j3_13_6', japanese:'奈良は、多くの人々が訪れる古い都市です。', answer:['Nara','is','an','old','city','visited','by','many','people','.']},
    {id:'j3_13_7', japanese:'そこで売られているもののほとんどは中古品です。', answer:['Most','of','the','things','sold','there','are','used','ones','.']},
    {id:'j3_13_8', japanese:'日本で作られた車はアメリカで人気があります。', answer:['Cars','made','in','Japan','are','popular','in','America','.']},
    {id:'j3_13_9', japanese:'フランス語はカナダで話される言語の１つです。', answer:['French','is','one','of','the','languages','spoken','in','Canada','.']},
    {id:'j3_13_10', japanese:'彼女と踊っているあの男の子はとても幸せそうです。', answer:['That','boy','dancing','with','her','looks','very','happy','.']},
    {id:'j3_13_11', japanese:'簡単な日本語で書かれた物語を読んでみたらどうですか。', answer:['How','about','reading','a','story','written','in','easy','Japanese','?']},
    {id:'j3_13_12', japanese:'向こうに有名なお寺が見える塔があります。', answer:['There','is','a','tower','from','which','you','can','see','a','famous','temple','over','there','.']},
  ],
  j3_14: [
    {id:'j3_14_1', japanese:'私はギターが弾ける先生を知っています。', answer:['I','know','a','teacher','who','can','play','the','guitar','.']},
    {id:'j3_14_2', japanese:'私は地球について教えてくれる本を見つけました。', answer:['I','found','some','books','that','tell','us','about','earth','.']},
    {id:'j3_14_3', japanese:'命を持っているものすべてを愛しなさい。', answer:['Love','everything','that','has','life','.']},
    {id:'j3_14_4', japanese:'彼女は自分を幸せにしてくれる人を探しています。', answer:['She','is','looking','for','a','person','who','makes','her','happy','.']},
    {id:'j3_14_5', japanese:'私たちに宇宙のことをたくさん教えてくれるその本は、とてもおもしろいです。', answer:['The','book','which','tells','us','a','lot','about','space','is','very','interesting','.']},
    {id:'j3_14_6', japanese:'あなたはこの本を書いた人を知っていますか。', answer:['Do','you','know','the','man','who','wrote','this','book','?']},
    {id:'j3_14_7', japanese:'臓器移植を必要としているたくさんの人々がいます。', answer:['There','are','lots','of','people','who','need','organ','transplantation','.']},
    {id:'j3_14_8', japanese:'あちらで歩いているあの少女とそのイヌを見てください。', answer:['Look','at','that','girl','who','is','walking','over','there','and','her','dog','.']},
  ],
  j3_15: [
    {id:'j3_15_1', japanese:'あなたが昨日会った少年はトムです。', answer:['The','boy','you','met','yesterday','was','Tom','.']},
    {id:'j3_15_2', japanese:'これは２年前に訪れた公園です。', answer:['This','is','the','park','we','visited','two','years','ago','.']},
    {id:'j3_15_3', japanese:'これは今まで読んだ中で最も良い本です。', answer:['This','is','the','best','book','I\'ve','ever','read','.']},
    {id:'j3_15_4', japanese:'札幌は私が訪れたいと思っている都市の１つです。', answer:['Sapporo','is','one','of','the','cities','that','I','want','to','visit','.']},
    {id:'j3_15_5', japanese:'きのうテレビで見たニュースにぼくは腹が立ちました。', answer:['The','news','that','I','saw','on','TV','yesterday','made','me','angry','.']},
    {id:'j3_15_6', japanese:'あなたがきのう買った本を見せてください。', answer:['Please','show','me','the','book','that','you','bought','yesterday','.']},
    {id:'j3_15_7', japanese:'私たちは彼女が飼っているネコを見たことがありません。', answer:['We','have','never','seen','the','cat','which','she','has','.']},
    {id:'j3_15_8', japanese:'あなたがコンサートに招待した少女は幸せそうです。', answer:['The','girl','you','invited','to','the','concert','looks','happy','.']},
    {id:'j3_15_9', japanese:'何か私にできることがありますか。', answer:['Is','there','anything','I','can','do','for','you','?']},
    {id:'j3_15_10', japanese:'ジョンは英語を非常によく知っているオーストラリア少年です。', answer:['John','is','an','Australian','boy','who','knows','English','very','well','.']},
    {id:'j3_15_11', japanese:'昨日する予定だった宿題はとても難しかったです。', answer:['The','homework','to','do','yesterday','was','very','difficult','.']},
  ],
  j3_16: [
    {id:'j3_16_1', japanese:'私の兄は母より背が高いです。', answer:['My','brother','is','taller','than','my','mother','.']},
    {id:'j3_16_2', japanese:'この車はあの車より速く走れます。', answer:['This','car','can','run','faster','than','that','one','.']},
    {id:'j3_16_3', japanese:'私はあなたよりたくさんのCDを持っています。', answer:['I','have','more','CDs','than','you','.']},
    {id:'j3_16_4', japanese:'あなたのコンピュータは私のより性能がよいです。', answer:['Your','computer','is','better','than','mine','.']},
    {id:'j3_16_5', japanese:'数学は私にとって英語より難しいです。', answer:['Math','is','more','difficult','than','English','for','me','.']},
    {id:'j3_16_6', japanese:'由美はマイクと同年です。', answer:['Yumi','is','as','old','as','Mike','.']},
    {id:'j3_16_7', japanese:'私はあなたほど忙しくありません。', answer:['I\'m','not','as','busy','as','you','.']},
    {id:'j3_16_8', japanese:'私はトムの２倍の数の本を持っています。', answer:['I','have','twice','as','many','books','as','Tom','.']},
    {id:'j3_16_9', japanese:'彼は世界で最も有名なピアニストの１人です。', answer:['He','is','one','of','the','most','famous','pianists','in','the','world','.']},
    {id:'j3_16_10', japanese:'あなたは英語と数学ではどちらのほうが好きですか。', answer:['Which','do','you','like','better','English','or','math','?']},
    {id:'j3_16_11', japanese:'私はすべてのスポーツの中でサッカーがいちばん好きです。', answer:['I','like','soccer','the','best','of','all','sports','.']},
    {id:'j3_16_12', japanese:'できるだけ速く歩きなさい。', answer:['Walk','as','fast','as','you','can','.']},
  ],
  j3_17: [
    {id:'j3_17_1', japanese:'あなたはきのうの夜、お店に行きましたか。', answer:['Did','you','go','to','the','shop','last','night','?']},
    {id:'j3_17_2', japanese:'それは古い映画ですか。', answer:['Is','it','an','old','movie','?']},
    {id:'j3_17_3', japanese:'ジュンは野球が好きですか。', answer:['Does','Jun','like','baseball','?']},
    {id:'j3_17_4', japanese:'どの電車に乗ったのですか。', answer:['Which','train','did','you','take','?']},
    {id:'j3_17_5', japanese:'あした公園を散歩しませんか。', answer:['How','about','taking','a','walk','in','the','park','tomorrow','?']},
    {id:'j3_17_6', japanese:'ひと月に何冊の本を読みますか。', answer:['How','many','books','do','you','read','a','month','?']},
    {id:'j3_17_7', japanese:'由美は料理が好きですね。', answer:['Yumi','likes','cooking','doesn\'t','she','?']},
    {id:'j3_17_8', japanese:'佐藤先生は歌いませんでしたね。', answer:['Mr.','Sato','didn\'t','sing','did','he','?']},
    {id:'j3_17_9', japanese:'彼らは昨晩、一睡もしなかったのですか。', answer:['Didn\'t','they','sleep','at','all','last','night','?']},
    {id:'j3_17_10', japanese:'食堂に行きましょうか。', answer:['Let\'s','go','to','the','cafeteria','.']},
  ],
  j3_18: [
    {id:'j3_18_1', japanese:'あなたは英語の先生がどこに住んでいるか知っていますか。', answer:['Do','you','know','where','your','English','teacher','lives','?']},
    {id:'j3_18_2', japanese:'彼は彼女が手に何を持っていたか知りませんでした。', answer:['He','didn\'t','know','what','she','had','in','her','hands','.']},
    {id:'j3_18_3', japanese:'私は彼女が日本に来たときを知りません。', answer:['I','don\'t','know','when','she','came','to','Japan','.']},
    {id:'j3_18_4', japanese:'彼らはその男性がだれだか知っていました。', answer:['They','knew','who','the','man','was','.']},
    {id:'j3_18_5', japanese:'あなたは彼女のお母さんがどこにかばんを置いたか知っていますか。', answer:['Do','you','know','where','her','mother','put','the','bag','?']},
    {id:'j3_18_6', japanese:'その植物をどのように育てたらよいのか彼らに教えてくれませんか。', answer:['Will','you','tell','them','how','to','grow','the','plant','?']},
    {id:'j3_18_7', japanese:'彼女がどんなセーターを買ったか知りません。', answer:['I','don\'t','know','what','kind','of','sweater','she','bought','.']},
    {id:'j3_18_8', japanese:'あなたは彼女がどこに住んでいるか知っていますか。', answer:['Do','you','know','where','she','lives','?']},
    {id:'j3_18_9', japanese:'彼女が何をすべきか彼女に話しなさい。', answer:['Tell','her','what','she','should','do','.']},
    {id:'j3_18_10', japanese:'私は彼が話してくれた話を覚えていません。', answer:['I','don\'t','remember','the','story','he','told','me','.']},
  ],
  j3_19: [
    {id:'j3_19_1', japanese:'通りを渡るときは注意しなさい。', answer:['Be','careful','when','you','walk','across','the','street','.']},
    {id:'j3_19_2', japanese:'これらの絵はなんて美しいのでしょう。', answer:['How','beautiful','these','pictures','are','!']},
    {id:'j3_19_3', japanese:'注意して見なさい。そうすればこれが何かわかるでしょう。', answer:['Look','carefully','and','you\'ll','see','what','this','is','.']},
    {id:'j3_19_4', japanese:'部屋の中では騒いではいけません。', answer:['Don\'t','be','noisy','in','the','classroom','.']},
    {id:'j3_19_5', japanese:'この機械を注意して使わないと、壊してしまうでしょう。', answer:['If','you','don\'t','use','this','machine','carefully','you\'ll','break','it','.']},
    {id:'j3_19_6', japanese:'彼女はなんてじょうずにピアノを弾くのでしょう。', answer:['How','good','a','pianist','she','is','!']},
    {id:'j3_19_7', japanese:'郵便局へ行く道を教えてください。', answer:['Please','tell','me','the','way','to','the','post','office','.']},
    {id:'j3_19_8', japanese:'学校に遅刻してはいけません。', answer:['Don\'t','be','late','for','school','.']},
    {id:'j3_19_9', japanese:'なんてかわいいネコでしょう。', answer:['What','a','cute','cat','you','have','!']},
  ],
  j3_20: [
    {id:'j3_20_1', japanese:'私があなたなら、あなたのお母さんに助けを求めるでしょう。', answer:['If','I','were','you','I','would','ask','your','mother','for','help','.']},
    {id:'j3_20_2', japanese:'かぎを持っていれば、このスーツケースを開けることができるのに。', answer:['If','I','had','the','key','I','could','open','this','suitcase','.']},
    {id:'j3_20_3', japanese:'雨が降っていなければ散歩に行くのに。', answer:['I','would','go','for','a','walk','if','it','were','not','raining','.']},
    {id:'j3_20_4', japanese:'学校がうちの近くにあればいいのに。', answer:['I','wish','school','were','near','my','house','.']},
    {id:'j3_20_5', japanese:'こんなに暑くなければいいのに。', answer:['I','wish','it','were','not','so','hot','.']},
    {id:'j3_20_6', japanese:'母が犬を好きだったらなあ。', answer:['I','wish','my','mother','liked','dogs','.']},
    {id:'j3_20_7', japanese:'ピアノが弾けたらなあ。', answer:['I','wish','I','could','play','the','piano','.']},
    {id:'j3_20_8', japanese:'もし人々が車を使うのをやめたら、何が起こるでしょうか。', answer:['What','would','happen','if','people','stopped','using','a','car','?']},
    {id:'j3_20_9', japanese:'彼が私の言うことをもっと注意深く聞いてくれればなあ。', answer:['I','wish','he','listened','to','me','more','carefully','.']},
    {id:'j3_20_10', japanese:'もし夏休みがもっと長ければ、本をもっと読めるのに。', answer:['If','our','summer','vacation','were','longer','I','could','read','more','books','.']},
    {id:'j3_20_11', japanese:'ジムは、あしたひまなら公園に来るでしょう。', answer:['If','Jim','is','free','tomorrow','he','would','come','to','the','park','.']},
  ],
}
